In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt
# import seaborn as sns
import pickle
import gc
import time
from tqdm import tqdm

%matplotlib inline

#每次可以输出多个变量
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from pylab import rcParams
rcParams['figure.figsize'] = 14, 6

import warnings
warnings.filterwarnings("ignore")

#中文字体
import matplotlib
matplotlib.use('qt4agg')
#指定默认字体
matplotlib.rcParams['font.sans-serif'] = ['SimHei']
matplotlib.rcParams['font.family'] = 'sans-serif'
#解决负号'-'显示为方块的问题
matplotlib.rcParams['axes.unicode_minus'] = False

In [4]:
train1 = pd.read_csv('tr_preprocessing_model1_pre5.csv')
train2 = pd.read_csv('tr_preprocessing_model1_6.csv')
train3 = pd.read_csv('tr_preprocessing_model1_fulltime.csv')

train1.shape
train1.head()
train2.shape
train2.head()
train3.shape
train3.head()

(1597063, 77)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,time,day,hour,minute,user_query_day,user_query_day_hour,user_query_minute,user_count,user_day_count,user_hour_count,user_minute_count,user_next_count,user_last_count,user_next_time,user_last_time,next_time_sub,last_time_sub,user_item_num,user_shop_num,user_item_day_num,user_shop_day_num,user_item_num_next,user_item_num_last,user_shop_num_next,user_shop_num_last,user_item_next_time,user_item_last_time,user_shop_next_time,user_shop_last_time,user_item_next_time_sub,user_item_last_time_sub,user_shop_next_time_sub,user_shop_last_time_sub,user_fisrt_num,user_item_fisrt_num,user_shop_fisrt_num,user_count_first_time,user_item_count_first_time,user_shop_count_first_time,user_count_first_time_sub,user_item_count_first_time_sub,user_shop_count_first_time_sub,max_click,is_last_click,max_user_item_click,is_last_user_item_click,max_click_time,max_user_item_click_time,max_click_time_sub,max_user_item_click_time_sub
0,1002640977003914936,4943913163084262584,836752724084922533;768579787521575291,367082587220462692;5131280576272319091;8689439...,3801992748557162347,4374800994578205793,7,9,10,17,1493508356721691818,1,1005,2002,3007,1088197280290283759,1536249600,4001,"836752724084922533:4324484723289924768,3657871...",5829729320339396622,14,1.000000,5012,0.981436,0.980990,0.987401,0,2018-09-07 00:00:00,7,0,0,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0
1,7563693237648713137,1097656060630949565,836752724084922533;3613783563199627217;6370392...,6241534230954727302;367082587220462692;5977512...,8420832032159385750,196257267849351217,7,12,12,20,2535192701541505605,0,1005,2005,3002,4656934049025345586,1536249600,4001,"836752724084922533:1405752240728470138,2125982...",1924781308265458391,19,1.000000,5017,0.981413,0.981040,0.989620,0,2018-09-07 00:00:00,7,0,0,1,1,1,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-03 13:29:48,2018-09-07 00:00:00,2018-09-07 00:00:00,37812,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
2,3325379761110661259,4747706882249246504,836752724084922533;768579787521575291,3540471119339706981;5131280576272319091;302719...,6232396831040542357,8519578687848277273,6,14,13,17,8204445143641875432,0,1003,2004,3007,6544635643285905366,1536249600,4001,"768579787521575291:3540471119339706981,5131280...",8983666490462246326,23,0.995066,5020,0.974091,0.974842,0.967002,0,2018-09-07 00:00:00,7,0,0,2,2,2,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
3,6026863564044534796,6075147184977200133,836752724084922533;1909641874861640857,5977512434884267894;2072967855524022579;263639...,2143736106091506900,6219110439660858399,6,8,8,16,3370515857303357002,-1,-1,-1,-1,1591753168403833710,1536249600,4001,1036082357054043890:-1;8658630417297894718:-1;...,146460612484534365,19,0.979555,5016,0.957083,0.958109,0.951751,0,2018-09-07 00:00:00,7,0,0,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0
4,7074792290685319356,7227779099688226563,836752724084922533;768579787521575291,6241534230954727302;3540471119339706981;462193...,8909918568166119776,3122721854741763495,8,13,13,19,4890272292782939403,0,1002,2005,3009,3421390014084173241,1536249600,4001,768579787521575291:-1;8096917686185033019:9148...,3685789896910492811,17,1.000000,5014,0.983497,0.983812,0.986854,0,2018-09-07 00:00:00,7,0,0,3,3,3,0,0,0,0,1,-1,2018-09-03 17:58:19,NaN,64699,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-01 09:33:42,2018-09-07 00:00:00,2018-09-07 00:00:00,51978,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0

(1597063, 74)

,instance_id,item_id,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,time,day,hour,minute,user_query_day,user_query_day_hour,user_query_minute,user_count,user_day_count,user_hour_count,user_minute_count,user_next_count,user_last_count,user_next_time,user_last_time,next_time_sub,last_time_sub,user_item_num,user_shop_num,user_item_day_num,user_shop_day_num,user_item_num_next,user_item_num_last,user_shop_num_next,user_shop_num_last,user_item_next_time,user_item_last_time,user_shop_next_time,user_shop_last_time,user_item_next_time_sub,user_item_last_time_sub,user_shop_next_time_sub,user_shop_last_time_sub,user_fisrt_num,user_item_fisrt_num,user_shop_fisrt_num,user_count_first_time,user_item_count_first_time,user_shop_count_first_time,user_count_first_time_sub,user_item_count_first_time_sub,user_shop_count_first_time_sub,max_click,is_last_click,max_user_item_click,is_last_user_item_click,max_click_time,max_user_item_click_time,max_click_time_sub,max_user_item_click_time_sub
0,1002640977003914936,4943913163084262584,3801992748557162347,4374800994578205793,7,9,10,17,1493508356721691818,1,1005,2002,3007,1088197280290283759,1536249600,4001,5829729320339396622,14,1.000000,5012,0.981436,0.980990,0.987401,0,2018-09-07 00:00:00,7,0,0,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0
1,7563693237648713137,1097656060630949565,8420832032159385750,196257267849351217,7,12,12,20,2535192701541505605,0,1005,2005,3002,4656934049025345586,1536249600,4001,1924781308265458391,19,1.000000,5017,0.981413,0.981040,0.989620,0,2018-09-07 00:00:00,7,0,0,1,1,1,0,0,0,0,1,-1,NaN,NaN,999999,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
2,3325379761110661259,4747706882249246504,6232396831040542357,8519578687848277273,6,14,13,17,8204445143641875432,0,1003,2004,3007,6544635643285905366,1536249600,4001,8983666490462246326,23,0.995066,5020,0.974091,0.974842,0.967002,0,2018-09-07 00:00:00,7,0,0,2,2,2,0,0,0,0,1,-1,2018-09-06 23:57:11,NaN,86231,999999,0,0,0,0,1,-1,1,-1,2018-09-07 00:00:00,NaN,2018-09-07 00:00:00,NaN,0,999999,0,999999,0,0,0,2018-09-06 23:56:27,2018-09-06 23:56:27,2018-09-06 23:56:27,213,213,213,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
3,6026863564044534796,6075147184977200133,2143736106091506900,6219110439660858399,6,8,8,16,3370515857303357002,-1,-1,-1,-1,1591753168403833710,1536249600,4001,146460612484534365,19,0.979555,5016,0.957083,0.958109,0.951751,0,2018-09-07 00:00:00,7,0,0,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0
4,7074792290685319356,7227779099688226563,8909918568166119776,3122721854741763495,8,13,13,19,4890272292782939403,0,1002,2005,3009,3421390014084173241,1536249600,4001,3685789896910492811,17,1.000000,5014,0.983497,0.983812,0.986854,0,2018-09-07 00:00:00,7,0,0,3,3,3,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-06 23:41:20,2018-09-07 00:00:00,2018-09-07 00:00:00,1120,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0

(1597063, 74)

,instance_id,item_id,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,time,day,hour,minute,user_query_day,user_query_day_hour,user_query_minute,user_count,user_day_count,user_hour_count,user_minute_count,user_next_count,user_last_count,user_next_time,user_last_time,next_time_sub,last_time_sub,user_item_num,user_shop_num,user_item_day_num,user_shop_day_num,user_item_num_next,user_item_num_last,user_shop_num_next,user_shop_num_last,user_item_next_time,user_item_last_time,user_shop_next_time,user_shop_last_time,user_item_next_time_sub,user_item_last_time_sub,user_shop_next_time_sub,user_shop_last_time_sub,user_fisrt_num,user_item_fisrt_num,user_shop_fisrt_num,user_count_first_time,user_item_count_first_time,user_shop_count_first_time,user_count_first_time_sub,user_item_count_first_time_sub,user_shop_count_first_time_sub,max_click,is_last_click,max_user_item_click,is_last_user_item_click,max_click_time,max_user_item_click_time,max_click_time_sub,max_user_item_click_time_sub
0,1002640977003914936,4943913163084262584,3801992748557162347,4374800994578205793,7,9,10,17,1493508356721691818,1,1005,2002,3007,1088197280290283759,1536249600,4001,5829729320339396622,14,1.000000,5012,0.981436,0.980990,0.987401,0,2018-09-07 00:00:00,7,0,0,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0
1,7563693237648713137,1097656060630949565,8420832032159385750,196257267849351217,7,12,12,20,2535192701541505605,0,1005,2005,3002,4656934049025345586,1536249600,4001,1924781308265458391,19,1.000000,5017,0.981413,0.981040,0.989620,0,2018-09-07 00:00:00,7,0,0,1,1,1,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-03 13:29:48,2018-09-07 00:00:00,2018-09-07 00:00:00,37812,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
2,3325379761110661259,4747706882249246504,6232396831040542357,8519578687848277273,6,14,13,17,8204445143641875432,0,1003,2004,3007,6544635643285905366,1536249600,4001,8983666490462246326,23,0.995066,5020,0.974091,0.974842,0.967002,0,2018-09-07 00:00:00,7,0,0,2,2,2,0,0,0,0,1,-1,2018-09-06 23:57:11,NaN,86231,999999,0,0,0,0,1,-1,1,-1,2018-09-07 00:00:00,NaN,2018-09-07 00:00:00,NaN,0,999999,0,999999,0,0,0,2018-09-06 23:56:27,2018-09-06 23:56:27,2018-09-06 23:56:27,213,213,213,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
3,6026863564044534796,6075147184977200133,2143736106091506900,6219110439660858399,6,8,8,16,3370515857303357002,-1,-1,-1,-1,1591753168403833710,1536249600,4001,146460612484534365,19,0.979555,5016,0.957083,0.958109,0.951751,0,2018-09-07 00:00:00,7,0,0,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0
4,7074792290685319356,7227779099688226563,8909918568166119776,3122721854741763495,8,13,13,19,4890272292782939403,0,1002,2005,3009,3421390014084173241,1536249600,4001,3685789896910492811,17,1.000000,5014,0.983497,0.983812,0.986854,0,2018-09-07 00:00:00,7,0,0,3,3,3,0,0,0,0,1,-1,2018-09-03 17:58:19,NaN,64699,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-01 09:33:42,2018-09-07 00:00:00,2018-09-07 00:00:00,51978,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0

In [5]:
origin = [
    'item_id', 'item_brand_id', 'item_city_id',
    'item_price_level', 'item_sales_level', 'item_collected_level',
    'item_pv_level', 'user_id', 'user_gender_id', 'user_age_level',
    'user_occupation_id', 'user_star_level', 'context_id', 'context_timestamp',
    'context_page_id', 'shop_id', 'shop_review_num_level',
    'shop_review_positive_rate', 'shop_star_level', 'shop_score_service',
    'shop_score_delivery', 'shop_score_description'
]

features = [
    'time', 'day', 'hour', 'minute', 'user_query_day', 'user_query_day_hour',
    'user_query_minute', 'item_category_split_count',
    'item_property_split_count', 'pred_category_split_count',
    'pred_property_split_count', 'item_pred_category_score',
    'item_pred_property_score', 'item_pred_category_score_item%',
    'item_pred_property_score_item%', 'item_pred_category_score_pred%',
    'item_pred_property_score_pred%', 'user_shop_count', 'user_item_count',
    'user_context_count', 'user_shop_trade_count', 'user_item_trade_count',
    'user_context_trade_count', 'user_brand_count', 'user_city_count',
    'user_brand_trade_count', 'user_city_trade_count', 'item_occupation_count',
    'item_age_count', 'item_gender_count', 'item_occupation_trade_count',
    'item_age_trade_count', 'item_gender_trade_count', 'shop_score',
    'item_score', 'item_score2', 'item_score3', 'item_hot', 'user_hot',
    'shop_hot', 'brand_hot', 'occupation_hot', 'city_hot', 'item_trade_hot',
    'user_trade_hot', 'shop_trade_hot', 'brand_trade_hot',
    'occupation_trade_hot', 'city_trade_hot', 'user_sell_power',
    'user_sell_power_mean', 'user_sell_power_mean_item_minus',
    'user_sell_trade_power', 'user_sell_trade_power_mean',
    'user_sell_trade_power_mean_item_minus', 'yesterday', 'yesterhour',
    'user_day_query', 'user_yesterday_query', 'user_hour_query',
    'user_yesterhour_query', 'user_minute_query', 'item_day_query',
    'item_hour_query', 'item_minute_query', 'user_item_day_query',
    'user_item_hour_query', 'user_item_minute_query', 'min_time',
    'user_is_his', 'item_is_his', 'brand_is_his', 'user_is_trade_his',
    'item_is_trade_his', 'brand_is_trade_his', 'user_count', 'user_day_count',
    'user_hour_count', 'user_minute_count', 'item_trade_percent',
    'brand_trade_percent', 'user_trade_percent', 'occupation_trade_percent',
    'is_home', 'shop_item_count', 'brand_item_count', 'city_brand_count',
    'city_item_count', 'shop_item_count_his', 'brand_item_count_his',
    'city_brand_count_his', 'city_item_count_his'
]

by = ['instance_id']

target = ['is_trade']

In [8]:
drop_col = ['item_id','item_brand_id','item_city_id','item_price_level','item_sales_level','item_collected_level',
            'item_pv_level','user_id','user_gender_id','user_age_level','user_occupation_id','user_star_level',
            'context_id','context_timestamp','context_page_id','shop_id','shop_review_num_level','shop_review_positive_rate',
            'shop_star_level','shop_score_service','shop_score_delivery','shop_score_description','is_trade',
            'time','day','hour','minute']
len(drop_col)

27

In [5]:
# train1[by + origin + features].to_csv('tr_preprocessing_model1_origin.csv', index=None)

In [15]:
double_columns = list(set(train1.columns) & set(train2.columns))
double_columns.remove('instance_id')
len(double_columns)

33

In [10]:
len(set(train1.columns) & set(train2.columns))
len(set(train1.columns) & set(train3.columns))

0

0

In [9]:
train2 = train2.drop(drop_col, axis=1)
train3 = train3.drop(drop_col, axis=1)

train2_col = []
for i in train2.columns:
    train2_col.append(i + '_6')
train2.columns = train2_col

train3_col = []
for i in train3.columns:
    train3_col.append(i + '_full_time')
train3.columns = train3_col

In [13]:
train = train1.merge(train2, left_on=['instance_id'], right_on=['instance_id_6'], how='left')
train = train.merge(train3, left_on=['instance_id'], right_on=['instance_id_full_time'], how='left')

train.shape
train.head()

(1597063, 171)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,time,day,hour,minute,user_query_day,user_query_day_hour,user_query_minute,user_count,user_day_count,user_hour_count,user_minute_count,user_next_count,user_last_count,user_next_time,user_last_time,next_time_sub,last_time_sub,user_item_num,user_shop_num,user_item_day_num,user_shop_day_num,user_item_num_next,user_item_num_last,user_shop_num_next,user_shop_num_last,user_item_next_time,user_item_last_time,user_shop_next_time,user_shop_last_time,user_item_next_time_sub,user_item_last_time_sub,user_shop_next_time_sub,user_shop_last_time_sub,user_fisrt_num,user_item_fisrt_num,user_shop_fisrt_num,user_count_first_time,user_item_count_first_time,user_shop_count_first_time,user_count_first_time_sub,user_item_count_first_time_sub,user_shop_count_first_time_sub,max_click,is_last_click,max_user_item_click,is_last_user_item_click,max_click_time,max_user_item_click_time,max_click_time_sub,max_user_item_click_time_sub,instance_id_6,user_query_day_6,user_query_day_hour_6,user_query_minute_6,user_count_6,user_day_count_6,user_hour_count_6,user_minute_count_6,user_next_count_6,user_last_count_6,user_next_time_6,user_last_time_6,next_time_sub_6,last_time_sub_6,user_item_num_6,user_shop_num_6,user_item_day_num_6,user_shop_day_num_6,user_item_num_next_6,user_item_num_last_6,user_shop_num_next_6,user_shop_num_last_6,user_item_next_time_6,user_item_last_time_6,user_shop_next_time_6,user_shop_last_time_6,user_item_next_time_sub_6,user_item_last_time_sub_6,user_shop_next_time_sub_6,user_shop_last_time_sub_6,user_fisrt_num_6,user_item_fisrt_num_6,user_shop_fisrt_num_6,user_count_first_time_6,user_item_count_first_time_6,user_shop_count_first_time_6,user_count_first_time_sub_6,user_item_count_first_time_sub_6,user_shop_count_first_time_sub_6,max_click_6,is_last_click_6,max_user_item_click_6,is_last_user_item_click_6,max_click_time_6,max_user_item_click_time_6,max_click_time_sub_6,max_user_item_click_time_sub_6,instance_id_full_time,user_query_day_full_time,user_query_day_hour_full_time,user_query_minute_full_time,user_count_full_time,user_day_count_full_time,user_hour_count_full_time,user_minute_count_full_time,user_next_count_full_time,user_last_count_full_time,user_next_time_full_time,user_last_time_full_time,next_time_sub_full_time,last_time_sub_full_time,user_item_num_full_time,user_shop_num_full_time,user_item_day_num_full_time,user_shop_day_num_full_time,user_item_num_next_full_time,user_item_num_last_full_time,user_shop_num_next_full_time,user_shop_num_last_full_time,user_item_next_time_full_time,user_item_last_time_full_time,user_shop_next_time_full_time,user_shop_last_time_full_time,user_item_next_time_sub_full_time,user_item_last_time_sub_full_time,user_shop_next_time_sub_full_time,user_shop_last_time_sub_full_time,user_fisrt_num_full_time,user_item_fisrt_num_full_time,user_shop_fisrt_num_full_time,user_count_first_time_full_time,user_item_count_first_time_full_time,user_shop_count_first_time_full_time,user_count_first_time_sub_full_time,user_item_count_first_time_sub_full_time,user_shop_count_first_time_sub_full_time,max_click_full_time,is_last_click_full_time,max_user_item_click_full_time,is_last_user_item_click_full_time,max_click_time_full_time,max_user_item_click_time_full_time,max_click_time_sub_full_time,max_user_item_click_time_sub_full_time
0,1002640977003914936,4943913163084262584,836752724084922533;768579787521575291,367082587220462692;5131280576272319091;8689439...,3801992748557162347,4374800994578205793,7,9,10,17,1493508356721691818,1,1005,2002,3007,1088197280290283759,1536249600,4001,"836752724084922533:4324484723289924768,3657871...",5829729320339396622,14,1.000000,5012,0.981436,0.980990,0.987401,0,2018-09-07 00:00:00,7,0,0,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0,1002640977003914936,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0,1002640977003914936,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0
1,7563693237648713137,1097656060630949565,836752724084922533;3613783563199627217;6370392...,6241534230954727302;367082587220462692;5977512...,8420832032159385750,196257267849351217,7,12,12,20,2535192701541505605,0,1005,2005,3002,4656934049025345586,1536249600,4001,"836752724084922533:1405752240728470138,2125982...",1924781308265458391,19,1.000000,5017,0.981413,0.981040,0.989620,0,2018-09-07 00:00:00,7,0,0,1,1,1,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-03 13:29:48,2018-09-07 00:00:00,2018-09-07 00:00:00,37812,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,7563693237648713137,1,1,1,0,0,0,0,1,-1,NaN,NaN,999999,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,7563693237648713137,1,1,1,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-03 13:29:48,2018-09-07 00:00:00,2018-09-07 00:00:00,37812,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
2,3325379761110661259,4747706882249246504,836752724084922533;768579787521575291,3540471119339706981;5131280576272319091;302719...,6232396831040542357,8519578687848277273,6,14,13,17,8204445143641875432,0,1003,2004,3007,6544635643285905366,1536249600,4001,"768579787521575291:3540471119339706981,5131280...",8983666490462246326,23,0.995066,5020,0.974091,0.974842,0.967002,0,2018-09-07 00:00:00,7,0,0,2,2,2,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,3325379761110661259,2,2,2,0,0,0,0,1,-1,2018-09-06 23:57:11,NaN,86231,999999,0,0,0,0,1,-1,1,-1,2018-09-07 00:00:00,NaN,2018-09-07 00:00:00,NaN,0,999999,0,999999,0,0,0,2018-09-06 23:56:27,2018-09-06 23:56:27,2018-09-06 23:56:27,213,213,213,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,3325379761110661259,2,2,2,0,0,0,0,1,-1,2018-09-06 23:57:11,NaN,86231,999999,0,0,0,0,1,-1,1,-1,2018-09-07 00:00:00,NaN,2018-09-07 00:00:00,NaN,0,999999,0,999999,0,0,0,2018-09-06 23:56:27,2018-09-06 23:56:27,2018-09-06 23:56:27,213,213,213,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
3,6026863564044534796,6075147184977200133,836752724084922533;1909641874861640857,5977512434884267894;2072967855524022579;263639...,2143736106091506900,6219110439660858399,6,8,8,16,3370515857303357002,-1,-1,-1,-1,1591753168403833710,1536249600,4001,1036082357054043890:-1;8658630417297894718:-1;...,146460612484534365,19,0.979555,5016,0.957083,0.958109,0.951751,0,2018-09-07 00:00:00,7,0,0,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0,6026863564044534796,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0,6026863564044534796,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0
4,7074792290685319356,7227779099688226563,836752724084922533;768579787521575291,6241534230954727302;3540471119339706981;462193...,8909918568166119776,3122721854741763495,8,13,13,19,4890272292782939403,0,1002,2005,3009,3421390014084173241,1536249600,4001,768579787521575291:-1;8096917686185033019:9148...,3685789896910492811,17,1.000000,5014,0.983497,0.983812,0.986854,0,2018-09-07 00:00:00,7,0,0,3,3,3,0,0,0,0,1,-1,2018-09-03 17:58:19,NaN,64699,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-01 09:33:42,2018-09-07 00:00:00,2018-09-07 00:00:00,51978,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0,7074792290685319356,3,3,3,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-06 23:41:20,2018-09-07 00:00:00,2018-09-07 00:00:00,1120,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0,7074792290685319356,3,3,3,0,0,0,0,1,-1,2018-09-03 17:58:19,NaN,64699,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-01 09:33:42,2018-09-07 00:00:00,2018-09-07 00:00:00,51978,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0

In [18]:
# del train1
# del train2
# del train3
train.to_csv('train_model1_zero_new.csv', index=None)

# 整合原有列

In [10]:
train1 = pd.read_csv('train_zero.csv')
train2 = pd.read_csv('train_model1_zero_new.csv')

train1.shape
train1.head()
train2.shape
train2.head()

(1597063, 341)

,instance_id,item_id,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,time,day,hour,minute,user_query_day,user_query_day_hour,user_query_minute,item_category_split_count,item_property_split_count,pred_category_split_count,pred_property_split_count,item_pred_category_score,item_pred_property_score,item_pred_category_score_item%,item_pred_property_score_item%,item_pred_category_score_pred%,item_pred_property_score_pred%,user_shop_count,user_item_count,user_context_count,user_shop_trade_count,user_item_trade_count,user_context_trade_count,user_brand_count,user_city_count,user_brand_trade_count,user_city_trade_count,item_occupation_count,item_age_count,item_gender_count,item_occupation_trade_count,item_age_trade_count,item_gender_trade_count,shop_score,item_score,item_score2,item_score3,item_hot,user_hot,shop_hot,brand_hot,occupation_hot,city_hot,item_trade_hot,user_trade_hot,shop_trade_hot,brand_trade_hot,occupation_trade_hot,city_trade_hot,user_sell_power,user_sell_power_mean,user_sell_power_mean_item_minus,user_sell_trade_power,user_sell_trade_power_mean,user_sell_trade_power_mean_item_minus,yesterday,yesterhour,user_day_query,user_yesterday_query,user_hour_query,user_yesterhour_query,user_minute_query,item_day_query,item_hour_query,item_minute_query,user_item_day_query,user_item_hour_query,user_item_minute_query,min_time,user_is_his,item_is_his,brand_is_his,user_is_trade_his,item_is_trade_his,brand_is_trade_his,user_count,user_day_count,user_hour_count,user_minute_count,item_trade_percent,brand_trade_percent,user_trade_percent,occupation_trade_percent,is_home,shop_item_count,brand_item_count,city_brand_count,city_item_count,shop_item_count_his,brand_item_count_his,city_brand_count_his,city_item_count_his,user_next_count,user_last_count,user_next_time,user_last_time,next_time_sub,last_time_sub,user_item_num,user_shop_num,user_item_day_num,user_shop_day_num,user_item_num_next,user_item_num_last,user_shop_num_next,user_shop_num_last,user_item_next_time,user_item_last_time,user_shop_next_time,user_shop_last_time,user_item_next_time_sub,user_item_last_time_sub,user_shop_next_time_sub,user_shop_last_time_sub,user_fisrt_num,user_item_fisrt_num,user_shop_fisrt_num,user_count_first_time,user_item_count_first_time,user_shop_count_first_time,user_count_first_time_sub,user_item_count_first_time_sub,user_shop_count_first_time_sub,max_click,is_last_click,max_user_item_click,is_last_user_item_click,max_click_time,max_user_item_click_time,max_click_time_sub,max_user_item_click_time_sub,instance_id_6,time_6,day_6,hour_6,minute_6,user_query_day_6,user_query_day_hour_6,user_query_minute_6,item_category_split_count_6,item_property_split_count_6,pred_category_split_count_6,pred_property_split_count_6,item_pred_category_score_6,item_pred_property_score_6,item_pred_category_score_item%_6,item_pred_property_score_item%_6,item_pred_category_score_pred%_6,item_pred_property_score_pred%_6,user_shop_count_6,user_item_count_6,user_context_count_6,user_shop_trade_count_6,user_item_trade_count_6,user_context_trade_count_6,user_brand_count_6,user_city_count_6,user_brand_trade_count_6,user_city_trade_count_6,item_occupation_count_6,item_age_count_6,item_gender_count_6,item_occupation_trade_count_6,item_age_trade_count_6,item_gender_trade_count_6,shop_score_6,item_score_6,item_score2_6,item_score3_6,item_hot_6,user_hot_6,shop_hot_6,brand_hot_6,occupation_hot_6,city_hot_6,item_trade_hot_6,user_trade_hot_6,shop_trade_hot_6,brand_trade_hot_6,occupation_trade_hot_6,city_trade_hot_6,user_sell_power_6,user_sell_power_mean_6,user_sell_power_mean_item_minus_6,user_sell_trade_power_6,user_sell_trade_power_mean_6,user_sell_trade_power_mean_item_minus_6,yesterday_6,yesterhour_6,user_day_query_6,user_yesterday_query_6,user_hour_query_6,user_yesterhour_query_6,user_minute_query_6,item_day_query_6,item_hour_query_6,item_minute_query_6,user_item_day_query_6,user_item_hour_query_6,user_item_minute_query_6,min_time_6,user_is_his_6,item_is_his_6,brand_is_his_6,user_is_trade_his_6,item_is_trade_his_6,brand_is_trade_his_6,user_count_6,user_day_count_6,user_hour_count_6,user_minute_count_6,item_trade_percent_6,brand_trade_percent_6,user_trade_percent_6,occupation_trade_percent_6,is_home_6,shop_item_count_6,brand_item_count_6,city_brand_count_6,city_item_count_6,shop_item_count_his_6,brand_item_count_his_6,city_brand_count_his_6,city_item_count_his_6,user_next_count_6,user_last_count_6,user_next_time_6,user_last_time_6,next_time_sub_6,last_time_sub_6,user_item_num_6,user_shop_num_6,user_item_day_num_6,user_shop_day_num_6,user_item_num_next_6,user_item_num_last_6,user_shop_num_next_6,user_shop_num_last_6,user_item_next_time_6,user_item_last_time_6,user_shop_next_time_6,user_shop_last_time_6,user_item_next_time_sub_6,user_item_last_time_sub_6,user_shop_next_time_sub_6,user_shop_last_time_sub_6,user_fisrt_num_6,user_item_fisrt_num_6,user_shop_fisrt_num_6,user_count_first_time_6,user_item_count_first_time_6,user_shop_count_first_time_6,user_count_first_time_sub_6,user_item_count_first_time_sub_6,user_shop_count_first_time_sub_6,max_click_6,is_last_click_6,max_user_item_click_6,is_last_user_item_click_6,max_click_time_6,max_user_item_click_time_6,max_click_time_sub_6,max_user_item_click_time_sub_6,instance_id_full_time,item_category_list_full_time,item_property_list_full_time,predict_category_property_full_time,time_full_time,day_full_time,hour_full_time,minute_full_time,user_query_day_full_time,user_query_day_hour_full_time,user_query_minute_full_time,user_count_full_time,user_day_count_full_time,user_hour_count_full_time,user_minute_count_full_time,user_next_count_full_time,user_last_count_full_time,user_next_time_full_time,user_last_time_full_time,next_time_sub_full_time,last_time_sub_full_time,user_item_num_full_time,user_shop_num_full_time,user_item_day_num_full_time,user_shop_day_num_full_time,user_item_num_next_full_time,user_item_num_last_full_time,user_shop_num_next_full_time,user_shop_num_last_full_time,user_item_next_time_full_time,user_item_last_time_full_time,user_shop_next_time_full_time,user_shop_last_time_full_time,user_item_next_time_sub_full_time,user_item_last_time_sub_full_time,user_shop_next_time_sub_full_time,user_shop_last_time_sub_full_time,user_fisrt_num_full_time,user_item_fisrt_num_full_time,user_shop_fisrt_num_full_time,user_count_first_time_full_time,user_item_count_first_time_full_time,user_shop_count_first_time_full_time,user_count_first_time_sub_full_time,user_item_count_first_time_sub_full_time,user_shop_count_first_time_sub_full_time,max_click_full_time,is_last_click_full_time,max_user_item_click_full_time,is_last_user_item_click_full_time,max_click_time_full_time,max_user_item_click_time_full_time,max_click_time_sub_full_time,max_user_item_click_time_sub_full_time
0,1002640977003914936,4943913163084262584,3801992748557162347,4374800994578205793,7,9,10,17,1493508356721691818,1,1005,2002,3007,1088197280290283759,1536249600,0,5829729320339396622,14,1.000000,13,0.981436,0.980990,0.987401,0,2018-09-07 00:00:00,7,0,5,2,2,1,2,19,3,3,1,1,3.333333,0.500000,2.500000,2.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,77.0,55.0,26.0,0.0,0.0,0.0,25.667487,179,19.888889,9.944444,145.0,0.0,426.0,7564.0,2484989,26039.0,0.0,0.0,0.0,8.0,29558,193.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,2,0.0,2,0.0,1,171,62,8,1,1,1,0.0,1,0,1,1,1,0,0,0,0,0,0.000000,0.105764,0.0,1.189462,0,3,105,70,346,3.0,113.0,108.0,564.0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0,1002640977003914936,2018-09-07 00:00:00,7,0,5,2,2,1,2,19,3,3,1,1,3.333333,0.500000,2.500000,2.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,48.0,43.0,29.0,0.0,0.0,0.0,25.667487,179,19.888889,9.944444,123.0,0.0,272.0,3025.0,664288,9429.0,0.0,0.0,0.0,0.0,3098,26.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,2,0.0,2,0.0,1,171,62,8,1,1,1,0.0,1,0,1,1,1,1,0,0,0,0,0.000000,0.000000,0.0,0.466364,0,3,105,70,346,3.0,92.0,80.0,376.0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0,1002640977003914936,836752724084922533;768579787521575291,367082587220462692;5131280576272319091;8689439...,"836752724084922533:4324484723289924768,3657871...",2018-09-07 00:00:00,7,0,0,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0
1,7563693237648713137,1097656060630949565,8420832032159385750,196257267849351217,7,12,12,20,2535192701541505605,0,1005,2005,3002,4656934049025345586,1536249600,0,1924781308265458391,19,1.000000,18,0.981413,0.981040,0.989620,0,2018-09-07 00:00:00,7,0,5,1,1,1,3,25,1,1,1,0,2.500000,0.000000,5.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3369.0,1275.0,4040.0,2.0,1.0,2.0,35.254001,252,28.000000,14.000000,5376.0,1.0,19723.0,27115.0,4405710,1210626.0,3.0,0.0,30.0,86.0,55540,8360.0,7.0,3.500000,3.500000,0.0,0.0,7.0,6,23,1,0.0,1,0.0,1,723,79,12,1,1,1,0.0,0,0,1,1,0,0,0,0,0,0,0.055804,0.317168,0.0,1.260637,0,52,78,940,5348,85.0,132.0,1189.0,7995.0,1,-1,2018-09-03 13:29:48,NaN,48588,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,7563693237648713137,2018-09-07 00:00:00,7,0,5,1,1,1,3,25,1,1,1,0,2.500000,0.000000,5.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,860.0,304.0,1064.0,0.0,0.0,0.0,35.254001,252,28.000000,14.000000,1413.0,0.0,5612.0,7070.0,1125867,330746.0,0.0,0.0,0.0,2.0,6846,877.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,1,0.0,1,0.0,1,723,79,12,1,1,1,0.0,1,0,1,1,1,0,0,0,0,0,0.000000,0.028289,0.0,0.608065,0,52,78,940,5348,53.0,81.0,952.0,5582.0,1,-1,NaN,NaN,999999,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,7563693237648713137,836752724084922533;3613783563199627217;6370392...,6241534230954727302;367082587220462692;5977512...,"836752724084922533:1405752240728470138,2125982...",2018-09-07 00:00:00,7,0,0,1,1,1,0,0,0,0,1,-1,2018-09-03 13:29:48,NaN,48588,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
2,3325379761110661259,4747706882249246504,6232396831040542357,8519578687848277273,6,14,13,17,8204445143641875432,0,1003,2004,3007,6544635643285905366,1536249600,0,8983666490462246326,23,0.995066,21,0.974091,0.974842,0.967002,0,2018-09-07 00:00:00,7,0,5,2,2,2,2,24,2,1,2,0,6.666667,0.000000,6.666667,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,243.0,410.0,0.0,2.0,2.0,40.298827,235,29.375000,14.687500,546.0,0.0,18742.0,12654.0,412495,71554.0,4.0,0.0,88.0,68.0,4728,563.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,2,0.0,2,0.0,2,364,14,2,1,1,1,0.0,1,0,1,1,0,0,0,0,0,0,0.732601,0.537379,0.0,1.146196,0,176,58,44,509,199.0,72.0,51.0,661.0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,3325379761110661259,2018-09-07 00:00:00,7,0,5,2,2,2,2,24,2,1,2,0,6.666667,0.000000,6.666667,0.000000,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,33.0,328.0,480.0,0.0,0.0,1.0,40.298827,235,29.375000,14.687500,599.0,2.0,10131.0,7157.0,109743,23811.0,1.0,0.0,15.0,13.0,520,65.0,11.0,3.666667,2.333333,0.0,0.0,6.0,6,23,2,0.0,2,0.0,2,364,14,2,1,1,1,0.0,0,0,1,1,0,0,0,0,0,0,0.166945,0.181640,0.0,0.473834,0,176,58,44,509,204.0,65.0,44.0,530.0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,2018-09-06 23:56:27,NaN,2018-09-06 23:56:27,NaN,86187,999999,86187,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,3325379761110661259,836752724084922533;768579787521575291,3540471119339706981;5131280576272319091;302719...,"768579787521575291:3540471119339706981,5131280...",2018-09-07 00:00:00,7,0,0,2,2,2,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,2018-09-06 23:56:27,NaN,2018-09-06 23:56:27,NaN,86187,999999,86187,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
3,6026863564044534796,6075147184977200133,2143736106091506900,6219110439660858399,6,8,8,16,3370515857303357002,-1,-1,-1,-1,1591753168403833710,1536249600,0,146460612484534365,19,0.979555,17,0.957083,0.958109,0.951751,0,2018-09-07 00:00:00,7,0,5,4,2,2,2,20,6,1,2,0,6.666667,0.000000,2.857143,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,6.0,0.0,0.0,0.0,31.079815,136,17.000000,8.500000,147.0,0.0,6382.0,6861.0,17104,1309878.0,0.0,0.0,63.0,64.0,217,12905.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,4,0.0,2,2.0,2,133,12,1,1,1,1,0.0,1,0,1,1,1,0,0,0,0,0,0.000000,0.932809,0.0,1.268709,0,10,12,1958,6805,14.0,18.0,2497.0,9983.0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0,6026863564044534796,2018-09-07 00:00:00,7,0,5,4,2,2,2,20,6,1,2,0,6.666667,0.000000,2.857143,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,31.079815,136,17.000000,8.500000,80.0,0.0,1257.0,1330.0,4490,342180.0,0.0,0.0,8.0,9.0,45,1554.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,4,0.0,2,2.0,2,133,12,1,1,1,1,0.0,1,0,1,1,1,0,0,0,0,0,0.000000,0.676692,0.0,1.002227,0,10,12,1958,6805,10.0,13.0,1948.0,6822.0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0,6026863564044534796,836752724084922533;1909641874861640857,5977512434884267894;2072967855524022579;263639...,1036082357054043890:-1;8658630417297894718:-1;...,2018-09-07 00:00:00,7,0,0,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0
4,7074792290685319356,7227779099688226563,8909918568166119776,3122721854741763495,8,13,13,19,4890272292782939403,0,1002,2005,3009,3421390014084173241,1536249600,0,3685789896910492811,17,1.000000,15,0.983497,0.983812,0.986854,0,2018-09-07 00:00:00,7,0,5,3,3,3,2,34,5,2,2,1,6.666667,0.285714,3.333333,3.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,945.0,170.0,1761.0,2.0,0.0,2.0,30.555430,260,26.000000,13.000000,2197.0,2.0,4177.0,4177.0,4405710,133820.0,4.0,0.0,9.0,9.0,55540,1636.0,11.0,3.666667,4.333333,0.0,0.0,8.0,6,23,3,0.0,3,0.0,3,1014,182,15,1,1,1,0.0,0,0,1,1,0,0,0,0,0,0,0.182066,0.215466,0.0,1.260637,0,43,43,152,687,51.0,51.0,190.0,1115.0,1,-1,2018-09-07 00:00:21,NaN,21,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0,7074792290685319356,2018-09-07 00:00:00,7,0,5,3,3,3,2,34,5,2,2,1,6.666667,0.285714,3.333333,3.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,431.0,97.0,796.0,0.0,0.0,0.0,30.555430,260,26.000000,13.000000,1011.0,1.0,2589.0,2589.0,1125867,33116.0,0.0,0.0,2.0,2.0,6846,153.0,6.0,3.000000,5.000000,0.0,0.0,8.0,6,23,3,0.0,3,0.0,3,1014,182,15,1,1,1,0.0,0,0,1,1,1,0,0,0,0,0,0.000000,0.077250,0.0,0.608065,0,43,43,152,687,28.0,28.0,161.0,713.0,1,-1,2018-09-07 00:00:21,NaN,21,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0,7074792290685319356,836752724084922533;768579787521575291,6241534230954727302;3540471119339706981;462193...,768579787521575291:-1;8096917686185033019:9148...,2018-09-07 00:00:00,7,0,0,3,3,3,0,0,0,0,1,-1,2018-09-07 00:00:21,NaN,21,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0

(1597063, 171)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,time,day,hour,minute,user_query_day,user_query_day_hour,user_query_minute,user_count,user_day_count,user_hour_count,user_minute_count,user_next_count,user_last_count,user_next_time,user_last_time,next_time_sub,last_time_sub,user_item_num,user_shop_num,user_item_day_num,user_shop_day_num,user_item_num_next,user_item_num_last,user_shop_num_next,user_shop_num_last,user_item_next_time,user_item_last_time,user_shop_next_time,user_shop_last_time,user_item_next_time_sub,user_item_last_time_sub,user_shop_next_time_sub,user_shop_last_time_sub,user_fisrt_num,user_item_fisrt_num,user_shop_fisrt_num,user_count_first_time,user_item_count_first_time,user_shop_count_first_time,user_count_first_time_sub,user_item_count_first_time_sub,user_shop_count_first_time_sub,max_click,is_last_click,max_user_item_click,is_last_user_item_click,max_click_time,max_user_item_click_time,max_click_time_sub,max_user_item_click_time_sub,instance_id_6,user_query_day_6,user_query_day_hour_6,user_query_minute_6,user_count_6,user_day_count_6,user_hour_count_6,user_minute_count_6,user_next_count_6,user_last_count_6,user_next_time_6,user_last_time_6,next_time_sub_6,last_time_sub_6,user_item_num_6,user_shop_num_6,user_item_day_num_6,user_shop_day_num_6,user_item_num_next_6,user_item_num_last_6,user_shop_num_next_6,user_shop_num_last_6,user_item_next_time_6,user_item_last_time_6,user_shop_next_time_6,user_shop_last_time_6,user_item_next_time_sub_6,user_item_last_time_sub_6,user_shop_next_time_sub_6,user_shop_last_time_sub_6,user_fisrt_num_6,user_item_fisrt_num_6,user_shop_fisrt_num_6,user_count_first_time_6,user_item_count_first_time_6,user_shop_count_first_time_6,user_count_first_time_sub_6,user_item_count_first_time_sub_6,user_shop_count_first_time_sub_6,max_click_6,is_last_click_6,max_user_item_click_6,is_last_user_item_click_6,max_click_time_6,max_user_item_click_time_6,max_click_time_sub_6,max_user_item_click_time_sub_6,instance_id_full_time,user_query_day_full_time,user_query_day_hour_full_time,user_query_minute_full_time,user_count_full_time,user_day_count_full_time,user_hour_count_full_time,user_minute_count_full_time,user_next_count_full_time,user_last_count_full_time,user_next_time_full_time,user_last_time_full_time,next_time_sub_full_time,last_time_sub_full_time,user_item_num_full_time,user_shop_num_full_time,user_item_day_num_full_time,user_shop_day_num_full_time,user_item_num_next_full_time,user_item_num_last_full_time,user_shop_num_next_full_time,user_shop_num_last_full_time,user_item_next_time_full_time,user_item_last_time_full_time,user_shop_next_time_full_time,user_shop_last_time_full_time,user_item_next_time_sub_full_time,user_item_last_time_sub_full_time,user_shop_next_time_sub_full_time,user_shop_last_time_sub_full_time,user_fisrt_num_full_time,user_item_fisrt_num_full_time,user_shop_fisrt_num_full_time,user_count_first_time_full_time,user_item_count_first_time_full_time,user_shop_count_first_time_full_time,user_count_first_time_sub_full_time,user_item_count_first_time_sub_full_time,user_shop_count_first_time_sub_full_time,max_click_full_time,is_last_click_full_time,max_user_item_click_full_time,is_last_user_item_click_full_time,max_click_time_full_time,max_user_item_click_time_full_time,max_click_time_sub_full_time,max_user_item_click_time_sub_full_time
0,1002640977003914936,4943913163084262584,836752724084922533;768579787521575291,367082587220462692;5131280576272319091;8689439...,3801992748557162347,4374800994578205793,7,9,10,17,1493508356721691818,1,1005,2002,3007,1088197280290283759,1536249600,4001,"836752724084922533:4324484723289924768,3657871...",5829729320339396622,14,1.000000,5012,0.981436,0.980990,0.987401,0,2018-09-07 00:00:00,7,0,0,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0,1002640977003914936,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0,1002640977003914936,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0
1,7563693237648713137,1097656060630949565,836752724084922533;3613783563199627217;6370392...,6241534230954727302;367082587220462692;5977512...,8420832032159385750,196257267849351217,7,12,12,20,2535192701541505605,0,1005,2005,3002,4656934049025345586,1536249600,4001,"836752724084922533:1405752240728470138,2125982...",1924781308265458391,19,1.000000,5017,0.981413,0.981040,0.989620,0,2018-09-07 00:00:00,7,0,0,1,1,1,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-03 13:29:48,2018-09-07 00:00:00,2018-09-07 00:00:00,37812,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,7563693237648713137,1,1,1,0,0,0,0,1,-1,NaN,NaN,999999,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,7563693237648713137,1,1,1,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-03 13:29:48,2018-09-07 00:00:00,2018-09-07 00:00:00,37812,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
2,3325379761110661259,4747706882249246504,836752724084922533;768579787521575291,3540471119339706981;5131280576272319091;302719...,6232396831040542357,8519578687848277273,6,14,13,17,8204445143641875432,0,1003,2004,3007,6544635643285905366,1536249600,4001,"768579787521575291:3540471119339706981,5131280...",8983666490462246326,23,0.995066,5020,0.974091,0.974842,0.967002,0,2018-09-07 00:00:00,7,0,0,2,2,2,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,3325379761110661259,2,2,2,0,0,0,0,1,-1,2018-09-06 23:57:11,NaN,86231,999999,0,0,0,0,1,-1,1,-1,2018-09-07 00:00:00,NaN,2018-09-07 00:00:00,NaN,0,999999,0,999999,0,0,0,2018-09-06 23:56:27,2018-09-06 23:56:27,2018-09-06 23:56:27,213,213,213,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,3325379761110661259,2,2,2,0,0,0,0,1,-1,2018-09-06 23:57:11,NaN,86231,999999,0,0,0,0,1,-1,1,-1,2018-09-07 00:00:00,NaN,2018-09-07 00:00:00,NaN,0,999999,0,999999,0,0,0,2018-09-06 23:56:27,2018-09-06 23:56:27,2018-09-06 23:56:27,213,213,213,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
3,6026863564044534796,6075147184977200133,836752724084922533;1909641874861640857,5977512434884267894;2072967855524022579;263639...,2143736106091506900,6219110439660858399,6,8,8,16,3370515857303357002,-1,-1,-1,-1,1591753168403833710,1536249600,4001,1036082357054043890:-1;8658630417297894718:-1;...,146460612484534365,19,0.979555,5016,0.957083,0.958109,0.951751,0,2018-09-07 00:00:00,7,0,0,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0,6026863564044534796,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0,6026863564044534796,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0
4,7074792290685319356,7227779099688226563,836752724084922533;768579787521575291,6241534230954727302;3540471119339706981;462193...,8909918568166119776,3122721854741763495,8,13,13,19,4890272292782939403,0,1002,2005,3009,3421390014084173241,1536249600,4001,768579787521575291:-1;8096917686185033019:9148...,3685789896910492811,17,1.000000,5014,0.983497,0.983812,0.986854,0,2018-09-07 00:00:00,7,0,0,3,3,3,0,0,0,0,1,-1,2018-09-03 17:58:19,NaN,64699,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-01 09:33:42,2018-09-07 00:00:00,2018-09-07 00:00:00,51978,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0,7074792290685319356,3,3,3,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-06 23:41:20,2018-09-07 00:00:00,2018-09-07 00:00:00,1120,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0,7074792290685319356,3,3,3,0,0,0,0,1,-1,2018-09-03 17:58:19,NaN,64699,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-01 09:33:42,2018-09-07 00:00:00,2018-09-07 00:00:00,51978,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0

In [11]:
len(set(train1.columns) & set(train2.columns))
new_col = list(set(train1.columns) & set(train2.columns))
new_col.remove('instance_id')

168

In [12]:
train1 = train1.drop(new_col, axis=1)

train = train1.merge(train2, on=['instance_id'], how='left')
train.shape
train.head()

(1597063, 344)

,instance_id,item_category_split_count,item_property_split_count,pred_category_split_count,pred_property_split_count,item_pred_category_score,item_pred_property_score,item_pred_category_score_item%,item_pred_property_score_item%,item_pred_category_score_pred%,item_pred_property_score_pred%,user_shop_count,user_item_count,user_context_count,user_shop_trade_count,user_item_trade_count,user_context_trade_count,user_brand_count,user_city_count,user_brand_trade_count,user_city_trade_count,item_occupation_count,item_age_count,item_gender_count,item_occupation_trade_count,item_age_trade_count,item_gender_trade_count,shop_score,item_score,item_score2,item_score3,item_hot,user_hot,shop_hot,brand_hot,occupation_hot,city_hot,item_trade_hot,user_trade_hot,shop_trade_hot,brand_trade_hot,occupation_trade_hot,city_trade_hot,user_sell_power,user_sell_power_mean,user_sell_power_mean_item_minus,user_sell_trade_power,user_sell_trade_power_mean,user_sell_trade_power_mean_item_minus,yesterday,yesterhour,user_day_query,user_yesterday_query,user_hour_query,user_yesterhour_query,user_minute_query,item_day_query,item_hour_query,item_minute_query,user_item_day_query,user_item_hour_query,user_item_minute_query,min_time,user_is_his,item_is_his,brand_is_his,user_is_trade_his,item_is_trade_his,brand_is_trade_his,item_trade_percent,brand_trade_percent,user_trade_percent,occupation_trade_percent,is_home,shop_item_count,brand_item_count,city_brand_count,city_item_count,shop_item_count_his,brand_item_count_his,city_brand_count_his,city_item_count_his,time_6,day_6,hour_6,minute_6,item_category_split_count_6,item_property_split_count_6,pred_category_split_count_6,pred_property_split_count_6,item_pred_category_score_6,item_pred_property_score_6,item_pred_category_score_item%_6,item_pred_property_score_item%_6,item_pred_category_score_pred%_6,item_pred_property_score_pred%_6,user_shop_count_6,user_item_count_6,user_context_count_6,user_shop_trade_count_6,user_item_trade_count_6,user_context_trade_count_6,user_brand_count_6,user_city_count_6,user_brand_trade_count_6,user_city_trade_count_6,item_occupation_count_6,item_age_count_6,item_gender_count_6,item_occupation_trade_count_6,item_age_trade_count_6,item_gender_trade_count_6,shop_score_6,item_score_6,item_score2_6,item_score3_6,item_hot_6,user_hot_6,shop_hot_6,brand_hot_6,occupation_hot_6,city_hot_6,item_trade_hot_6,user_trade_hot_6,shop_trade_hot_6,brand_trade_hot_6,occupation_trade_hot_6,city_trade_hot_6,user_sell_power_6,user_sell_power_mean_6,user_sell_power_mean_item_minus_6,user_sell_trade_power_6,user_sell_trade_power_mean_6,user_sell_trade_power_mean_item_minus_6,yesterday_6,yesterhour_6,user_day_query_6,user_yesterday_query_6,user_hour_query_6,user_yesterhour_query_6,user_minute_query_6,item_day_query_6,item_hour_query_6,item_minute_query_6,user_item_day_query_6,user_item_hour_query_6,user_item_minute_query_6,min_time_6,user_is_his_6,item_is_his_6,brand_is_his_6,user_is_trade_his_6,item_is_trade_his_6,brand_is_trade_his_6,item_trade_percent_6,brand_trade_percent_6,user_trade_percent_6,occupation_trade_percent_6,is_home_6,shop_item_count_6,brand_item_count_6,city_brand_count_6,city_item_count_6,shop_item_count_his_6,brand_item_count_his_6,city_brand_count_his_6,city_item_count_his_6,item_category_list_full_time,item_property_list_full_time,predict_category_property_full_time,time_full_time,day_full_time,hour_full_time,minute_full_time,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,time,day,hour,minute,user_query_day,user_query_day_hour,user_query_minute,user_count,user_day_count,user_hour_count,user_minute_count,user_next_count,user_last_count,user_next_time,user_last_time,next_time_sub,last_time_sub,user_item_num,user_shop_num,user_item_day_num,user_shop_day_num,user_item_num_next,user_item_num_last,user_shop_num_next,user_shop_num_last,user_item_next_time,user_item_last_time,user_shop_next_time,user_shop_last_time,user_item_next_time_sub,user_item_last_time_sub,user_shop_next_time_sub,user_shop_last_time_sub,user_fisrt_num,user_item_fisrt_num,user_shop_fisrt_num,user_count_first_time,user_item_count_first_time,user_shop_count_first_time,user_count_first_time_sub,user_item_count_first_time_sub,user_shop_count_first_time_sub,max_click,is_last_click,max_user_item_click,is_last_user_item_click,max_click_time,max_user_item_click_time,max_click_time_sub,max_user_item_click_time_sub,instance_id_6,user_query_day_6,user_query_day_hour_6,user_query_minute_6,user_count_6,user_day_count_6,user_hour_count_6,user_minute_count_6,user_next_count_6,user_last_count_6,user_next_time_6,user_last_time_6,next_time_sub_6,last_time_sub_6,user_item_num_6,user_shop_num_6,user_item_day_num_6,user_shop_day_num_6,user_item_num_next_6,user_item_num_last_6,user_shop_num_next_6,user_shop_num_last_6,user_item_next_time_6,user_item_last_time_6,user_shop_next_time_6,user_shop_last_time_6,user_item_next_time_sub_6,user_item_last_time_sub_6,user_shop_next_time_sub_6,user_shop_last_time_sub_6,user_fisrt_num_6,user_item_fisrt_num_6,user_shop_fisrt_num_6,user_count_first_time_6,user_item_count_first_time_6,user_shop_count_first_time_6,user_count_first_time_sub_6,user_item_count_first_time_sub_6,user_shop_count_first_time_sub_6,max_click_6,is_last_click_6,max_user_item_click_6,is_last_user_item_click_6,max_click_time_6,max_user_item_click_time_6,max_click_time_sub_6,max_user_item_click_time_sub_6,instance_id_full_time,user_query_day_full_time,user_query_day_hour_full_time,user_query_minute_full_time,user_count_full_time,user_day_count_full_time,user_hour_count_full_time,user_minute_count_full_time,user_next_count_full_time,user_last_count_full_time,user_next_time_full_time,user_last_time_full_time,next_time_sub_full_time,last_time_sub_full_time,user_item_num_full_time,user_shop_num_full_time,user_item_day_num_full_time,user_shop_day_num_full_time,user_item_num_next_full_time,user_item_num_last_full_time,user_shop_num_next_full_time,user_shop_num_last_full_time,user_item_next_time_full_time,user_item_last_time_full_time,user_shop_next_time_full_time,user_shop_last_time_full_time,user_item_next_time_sub_full_time,user_item_last_time_sub_full_time,user_shop_next_time_sub_full_time,user_shop_last_time_sub_full_time,user_fisrt_num_full_time,user_item_fisrt_num_full_time,user_shop_fisrt_num_full_time,user_count_first_time_full_time,user_item_count_first_time_full_time,user_shop_count_first_time_full_time,user_count_first_time_sub_full_time,user_item_count_first_time_sub_full_time,user_shop_count_first_time_sub_full_time,max_click_full_time,is_last_click_full_time,max_user_item_click_full_time,is_last_user_item_click_full_time,max_click_time_full_time,max_user_item_click_time_full_time,max_click_time_sub_full_time,max_user_item_click_time_sub_full_time
0,1002640977003914936,2,19,3,3,1,1,3.333333,0.500000,2.500000,2.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,77.0,55.0,26.0,0.0,0.0,0.0,25.667487,179,19.888889,9.944444,145.0,0.0,426.0,7564.0,2484989,26039.0,0.0,0.0,0.0,8.0,29558,193.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,2,0.0,2,0.0,1,171,62,8,1,1,1,0.0,1,0,1,1,1,0,0.000000,0.105764,0.0,1.189462,0,3,105,70,346,3.0,113.0,108.0,564.0,2018-09-07 00:00:00,7,0,5,2,19,3,3,1,1,3.333333,0.500000,2.500000,2.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,48.0,43.0,29.0,0.0,0.0,0.0,25.667487,179,19.888889,9.944444,123.0,0.0,272.0,3025.0,664288,9429.0,0.0,0.0,0.0,0.0,3098,26.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,2,0.0,2,0.0,1,171,62,8,1,1,1,0.0,1,0,1,1,1,1,0.000000,0.000000,0.0,0.466364,0,3,105,70,346,3.0,92.0,80.0,376.0,836752724084922533;768579787521575291,367082587220462692;5131280576272319091;8689439...,"836752724084922533:4324484723289924768,3657871...",2018-09-07 00:00:00,7,0,0,4943913163084262584,836752724084922533;768579787521575291,367082587220462692;5131280576272319091;8689439...,3801992748557162347,4374800994578205793,7,9,10,17,1493508356721691818,1,1005,2002,3007,1088197280290283759,1536249600,4001,"836752724084922533:4324484723289924768,3657871...",5829729320339396622,14,1.000000,5012,0.981436,0.980990,0.987401,0,2018-09-07 00:00:00,7,0,0,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0,1002640977003914936,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0,1002640977003914936,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0
1,7563693237648713137,3,25,1,1,1,0,2.500000,0.000000,5.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3369.0,1275.0,4040.0,2.0,1.0,2.0,35.254001,252,28.000000,14.000000,5376.0,1.0,19723.0,27115.0,4405710,1210626.0,3.0,0.0,30.0,86.0,55540,8360.0,7.0,3.500000,3.500000,0.0,0.0,7.0,6,23,1,0.0,1,0.0,1,723,79,12,1,1,1,0.0,0,0,1,1,0,0,0.055804,0.317168,0.0,1.260637,0,52,78,940,5348,85.0,132.0,1189.0,7995.0,2018-09-07 00:00:00,7,0,5,3,25,1,1,1,0,2.500000,0.000000,5.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,860.0,304.0,1064.0,0.0,0.0,0.0,35.254001,252,28.000000,14.000000,1413.0,0.0,5612.0,7070.0,1125867,330746.0,0.0,0.0,0.0,2.0,6846,877.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,1,0.0,1,0.0,1,723,79,12,1,1,1,0.0,1,0,1,1,1,0,0.000000,0.028289,0.0,0.608065,0,52,78,940,5348,53.0,81.0,952.0,5582.0,836752724084922533;3613783563199627217;6370392...,6241534230954727302;367082587220462692;5977512...,"836752724084922533:1405752240728470138,2125982...",2018-09-07 00:00:00,7,0,0,1097656060630949565,836752724084922533;3613783563199627217;6370392...,6241534230954727302;367082587220462692;5977512...,8420832032159385750,196257267849351217,7,12,12,20,2535192701541505605,0,1005,2005,3002,4656934049025345586,1536249600,4001,"836752724084922533:1405752240728470138,2125982...",1924781308265458391,19,1.000000,5017,0.981413,0.981040,0.989620,0,2018-09-07 00:00:00,7,0,0,1,1,1,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-03 13:29:48,2018-09-07 00:00:00,2018-09-07 00:00:00,37812,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,7563693237648713137,1,1,1,0,0,0,0,1,-1,NaN,NaN,999999,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,7563693237648713137,1,1,1,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-03 13:29:48,2018-09-07 00:00:00,2018-09-07 00:00:00,37812,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
2,3325379761110661259,2,24,2,1,2,0,6.666667,0.000000,6.666667,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,243.0,410.0,0.0,2.0,2.0,40.298827,235,29.375000,14.687500,546.0,0.0,18742.0,12654.0,412495,71554.0,4.0,0.0,88.0,68.0,4728,563.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,2,0.0,2,0.0,2,364,14,2,1,1,1,0.0,1,0,1,1,0,0,0.732601,0.537379,0.0,1.146196,0,176,58,44,509,199.0,72.0,51.0,661.0,2018-09-07 00:00:00,7,0,5,2,24,2,1,2,0,6.666667,0.000000,6.666667,0.000000,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,33.0,328.0,480.0,0.0,0.0,1.0,40.298827,235,29.375000,14.687500,599.0,2.0,10131.0,7157.0,109743,23811.0,1.0,0.0,15.0,13.0,520,65.0,11.0,3.666667,2.333333,0.0,0.0,6.0,6,23,2,0.0,2,0.0,2,364,14,2,1,1,1,0.0,0,0,1,1,0,0,0.166945,0.181640,0.0,0.473834,0,176,58,44,509,204.0,65.0,44.0,530.0,836752724084922533;768579787521575291,3540471119339706981;5131280576272319091;302719...,"768579787521575291:3540471119339706981,5131280...",2018-09-07 00:00:00,7,0,0,4747706882249246504,836752724084922533;768579787521575291,3540471119339706981;5131280576272319091;302719...,6232396831040542357,8519578687848277273,6,14,13,17,8204445143641875432,0,1003,2004,3007,6544635643285905366,1536249600,4001,"768579787521575291:3540471119339706981,5131280...",8983666490462246326,23,0.995066,5020,0.974091,0.974842,0.967002,0,2018-09-07 00:00:00,7,0,0,2,2,2,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,3325379761110661259,2,2,2,0,0,0,0,1,-1,2018-09-06 23:57:11,NaN,86231,999999,0,0,0,0,1,-1,1,-1,2018-09-07 00:00:00,NaN,2018-09-07 00:00:00,NaN,0,999999,0,999999,0,0,0,2018-09-06 23:56:27,2018-09-06 23:56:27,2018-09-06 23:56:27,213,213,213,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,3325379761110661259,2,2,2,0,0,0,0,1,-1,2018-09-06 23:57:11,NaN,86231,999999,0,0,0,0,1,-1,1,-1,2018-09-07 00:00:00,NaN,2018-09-07 00:00:00,NaN,0,999999,0,999999,0,0,0,2018-09-06 23:56:27,2018-09-06 23:56:27,2018-09-06 23:56:27,213,213,213,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
3,6026863564044534796,2,20,6,1,2,0,6.666667,0.000000,2.857143,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,6.0,0.0,0.0,0.0,31.079815,136,17.000000,8.500000,147.0,0.0,6382.0,6861.0,17104,1309878.0,0.0,0.0,63.0,64.0,217,12905.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,4,0.0,2,2.0,2,133,12,1,1,1,1,0.0,1,0,1,1,1,0,0.000000,0.932809,0.0,1.268709,0,10,12,1958,6805,14.0,18.0,2497.0,9983.0,2018-09-07 00:00:00,7,0,5,2,20,6,1,2,0,6.666667,0.000000,2.857143,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,31.079815,136,17.000000,8.500000,80.0,0.0,1257.0,1330.0,4490,342180.0,0.0,0.0,8.0,9.0,45,1554.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,4,0.0,2,2.0,2,133,12,1,1,1,1,0.0,1,0,1,1,1,0,0.000000,0.676692,0.0,1.002227,0,10,12,1958,6805,10.0,13.0,1948.0,6822.0,836752724084922533;1909641874861640857,5977512434884267894;2072967855524022579;263639...,1036082357054043890:-1;8658630417297894718:-1;...,2018-09-07 00:00:00,7,0,0,6075147184977200133,836752724084922533;1909641874861640857,5977512434884267894;2072967855524022579;263639...,2143736106091506900,6219110439660858399,6,8,8,16,3370515857303357002,-1,-1,-1,-1,1591753168403833710,1536249600,4001,1036082357054043890:-1;8658630417297894718:-1;...,146460612484534365,19,0.979555,5016,0.957083,0.958109,0.951751,0,2018-09-07 00:00:00,7,0,0,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0,6026863564044534796,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0,6026863564044534796,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0
4,7074792290685319356,2,34,5,2,2,1,6.666667,0.285714,3.333333,3.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,945.0,170.0,1761.0,2.0,0.0,2.0,30.555430,260,26.000000,13.000000,2197.0,2.0,4177.0,4177.0,4405710,133820.0,4.0,0.0,9.0,9.0,55540,1636.0,11.0,3.666667,4.333333,0.0,0.0,8.0,6,23,3,0.0,3,0.0,3,1014,182,15,1,1,1,0.0,0,0,1,1,0,0,0.182066,0.215466,0.0,1.260637,0,43,43,152,687,51.0,51.0,190.0,1115.0,2018-09-07 00:00:00,7,0,5,2,34,5,2,2,1,6.666667,0.285714,3.333333,3.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,431.0,97.0,796.0,0.0,0.0,0.0,30.555430,260,26.000000,13.000000,1011.0,1.0,2589.0,2589.0,1125867,33116.0,0.0,0.0,2.0,2.0,6846,153.0,6.0,3.000000,5.000000,0.0,0.0,8.0,6,23,3,0.0,3,0.0,3,1014,182,15,1,1,1,0.0,0,0,1,1,1,0,0.000000,0.077250,0.0,0.608065,0,43,43,152,687,28.0,28.0,161.0,713.0,836752724084922533;768579787521575291,6241534230954727302;3540471119339706981;462193...,768579787521575291:-1;8096917686185033019:9148...,2018-09-07 00:00:00,7,0,0,7227779099688226563,836752724084922533;768579787521575291,6241534230954727302;3540471119339706981;462193...,8909918568166119776,3122721854741763495,8,13,13,19,4890272292782939403,0,1002,2005,3009,3421390014084173241,1536249600,4001,768579787521575291:-1;8096917686185033019:9148...,3685789896910492811,17,1.000000,5014,0.983497,0.983812,0.986854,0,2018-09-07 00:00:00,7,0,0,3,3,3,0,0,0,0,1,-1,2018-09-03 17:58:19,NaN,64699,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-01 09:33:42,2018-09-07 00:00:00,2018-09-07 00:00:00,51978,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0,7074792290685319356,3,3,3,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-06 23:41:20,2018-09-07 00:00:00,2018-09-07 00:00:00,1120,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0,7074792290685319356,3,3,3,0,0,0,0,1,-1,2018-09-03 17:58:19,NaN,64699,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-01 09:33:42,2018-09-07 00:00:00,2018-09-07 00:00:00,51978,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0

In [16]:
train.to_csv('train_zero_new.csv', index=None)

In [2]:
train = pd.read_csv('train_zero_new.csv')

train.shape
train.head()

(1597063, 344)

,instance_id,item_category_split_count,item_property_split_count,pred_category_split_count,pred_property_split_count,item_pred_category_score,item_pred_property_score,item_pred_category_score_item%,item_pred_property_score_item%,item_pred_category_score_pred%,item_pred_property_score_pred%,user_shop_count,user_item_count,user_context_count,user_shop_trade_count,user_item_trade_count,user_context_trade_count,user_brand_count,user_city_count,user_brand_trade_count,user_city_trade_count,item_occupation_count,item_age_count,item_gender_count,item_occupation_trade_count,item_age_trade_count,item_gender_trade_count,shop_score,item_score,item_score2,item_score3,item_hot,user_hot,shop_hot,brand_hot,occupation_hot,city_hot,item_trade_hot,user_trade_hot,shop_trade_hot,brand_trade_hot,occupation_trade_hot,city_trade_hot,user_sell_power,user_sell_power_mean,user_sell_power_mean_item_minus,user_sell_trade_power,user_sell_trade_power_mean,user_sell_trade_power_mean_item_minus,yesterday,yesterhour,user_day_query,user_yesterday_query,user_hour_query,user_yesterhour_query,user_minute_query,item_day_query,item_hour_query,item_minute_query,user_item_day_query,user_item_hour_query,user_item_minute_query,min_time,user_is_his,item_is_his,brand_is_his,user_is_trade_his,item_is_trade_his,brand_is_trade_his,item_trade_percent,brand_trade_percent,user_trade_percent,occupation_trade_percent,is_home,shop_item_count,brand_item_count,city_brand_count,city_item_count,shop_item_count_his,brand_item_count_his,city_brand_count_his,city_item_count_his,time_6,day_6,hour_6,minute_6,item_category_split_count_6,item_property_split_count_6,pred_category_split_count_6,pred_property_split_count_6,item_pred_category_score_6,item_pred_property_score_6,item_pred_category_score_item%_6,item_pred_property_score_item%_6,item_pred_category_score_pred%_6,item_pred_property_score_pred%_6,user_shop_count_6,user_item_count_6,user_context_count_6,user_shop_trade_count_6,user_item_trade_count_6,user_context_trade_count_6,user_brand_count_6,user_city_count_6,user_brand_trade_count_6,user_city_trade_count_6,item_occupation_count_6,item_age_count_6,item_gender_count_6,item_occupation_trade_count_6,item_age_trade_count_6,item_gender_trade_count_6,shop_score_6,item_score_6,item_score2_6,item_score3_6,item_hot_6,user_hot_6,shop_hot_6,brand_hot_6,occupation_hot_6,city_hot_6,item_trade_hot_6,user_trade_hot_6,shop_trade_hot_6,brand_trade_hot_6,occupation_trade_hot_6,city_trade_hot_6,user_sell_power_6,user_sell_power_mean_6,user_sell_power_mean_item_minus_6,user_sell_trade_power_6,user_sell_trade_power_mean_6,user_sell_trade_power_mean_item_minus_6,yesterday_6,yesterhour_6,user_day_query_6,user_yesterday_query_6,user_hour_query_6,user_yesterhour_query_6,user_minute_query_6,item_day_query_6,item_hour_query_6,item_minute_query_6,user_item_day_query_6,user_item_hour_query_6,user_item_minute_query_6,min_time_6,user_is_his_6,item_is_his_6,brand_is_his_6,user_is_trade_his_6,item_is_trade_his_6,brand_is_trade_his_6,item_trade_percent_6,brand_trade_percent_6,user_trade_percent_6,occupation_trade_percent_6,is_home_6,shop_item_count_6,brand_item_count_6,city_brand_count_6,city_item_count_6,shop_item_count_his_6,brand_item_count_his_6,city_brand_count_his_6,city_item_count_his_6,item_category_list_full_time,item_property_list_full_time,predict_category_property_full_time,time_full_time,day_full_time,hour_full_time,minute_full_time,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,time,day,hour,minute,user_query_day,user_query_day_hour,user_query_minute,user_count,user_day_count,user_hour_count,user_minute_count,user_next_count,user_last_count,user_next_time,user_last_time,next_time_sub,last_time_sub,user_item_num,user_shop_num,user_item_day_num,user_shop_day_num,user_item_num_next,user_item_num_last,user_shop_num_next,user_shop_num_last,user_item_next_time,user_item_last_time,user_shop_next_time,user_shop_last_time,user_item_next_time_sub,user_item_last_time_sub,user_shop_next_time_sub,user_shop_last_time_sub,user_fisrt_num,user_item_fisrt_num,user_shop_fisrt_num,user_count_first_time,user_item_count_first_time,user_shop_count_first_time,user_count_first_time_sub,user_item_count_first_time_sub,user_shop_count_first_time_sub,max_click,is_last_click,max_user_item_click,is_last_user_item_click,max_click_time,max_user_item_click_time,max_click_time_sub,max_user_item_click_time_sub,instance_id_6,user_query_day_6,user_query_day_hour_6,user_query_minute_6,user_count_6,user_day_count_6,user_hour_count_6,user_minute_count_6,user_next_count_6,user_last_count_6,user_next_time_6,user_last_time_6,next_time_sub_6,last_time_sub_6,user_item_num_6,user_shop_num_6,user_item_day_num_6,user_shop_day_num_6,user_item_num_next_6,user_item_num_last_6,user_shop_num_next_6,user_shop_num_last_6,user_item_next_time_6,user_item_last_time_6,user_shop_next_time_6,user_shop_last_time_6,user_item_next_time_sub_6,user_item_last_time_sub_6,user_shop_next_time_sub_6,user_shop_last_time_sub_6,user_fisrt_num_6,user_item_fisrt_num_6,user_shop_fisrt_num_6,user_count_first_time_6,user_item_count_first_time_6,user_shop_count_first_time_6,user_count_first_time_sub_6,user_item_count_first_time_sub_6,user_shop_count_first_time_sub_6,max_click_6,is_last_click_6,max_user_item_click_6,is_last_user_item_click_6,max_click_time_6,max_user_item_click_time_6,max_click_time_sub_6,max_user_item_click_time_sub_6,instance_id_full_time,user_query_day_full_time,user_query_day_hour_full_time,user_query_minute_full_time,user_count_full_time,user_day_count_full_time,user_hour_count_full_time,user_minute_count_full_time,user_next_count_full_time,user_last_count_full_time,user_next_time_full_time,user_last_time_full_time,next_time_sub_full_time,last_time_sub_full_time,user_item_num_full_time,user_shop_num_full_time,user_item_day_num_full_time,user_shop_day_num_full_time,user_item_num_next_full_time,user_item_num_last_full_time,user_shop_num_next_full_time,user_shop_num_last_full_time,user_item_next_time_full_time,user_item_last_time_full_time,user_shop_next_time_full_time,user_shop_last_time_full_time,user_item_next_time_sub_full_time,user_item_last_time_sub_full_time,user_shop_next_time_sub_full_time,user_shop_last_time_sub_full_time,user_fisrt_num_full_time,user_item_fisrt_num_full_time,user_shop_fisrt_num_full_time,user_count_first_time_full_time,user_item_count_first_time_full_time,user_shop_count_first_time_full_time,user_count_first_time_sub_full_time,user_item_count_first_time_sub_full_time,user_shop_count_first_time_sub_full_time,max_click_full_time,is_last_click_full_time,max_user_item_click_full_time,is_last_user_item_click_full_time,max_click_time_full_time,max_user_item_click_time_full_time,max_click_time_sub_full_time,max_user_item_click_time_sub_full_time
0,1002640977003914936,2,19,3,3,1,1,3.333333,0.500000,2.500000,2.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,77.0,55.0,26.0,0.0,0.0,0.0,25.667487,179,19.888889,9.944444,145.0,0.0,426.0,7564.0,2484989,26039.0,0.0,0.0,0.0,8.0,29558,193.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,2,0.0,2,0.0,1,171,62,8,1,1,1,0.0,1,0,1,1,1,0,0.000000,0.105764,0.0,1.189462,0,3,105,70,346,3.0,113.0,108.0,564.0,2018-09-07 00:00:00,7,0,5,2,19,3,3,1,1,3.333333,0.500000,2.500000,2.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,48.0,43.0,29.0,0.0,0.0,0.0,25.667487,179,19.888889,9.944444,123.0,0.0,272.0,3025.0,664288,9429.0,0.0,0.0,0.0,0.0,3098,26.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,2,0.0,2,0.0,1,171,62,8,1,1,1,0.0,1,0,1,1,1,1,0.000000,0.000000,0.0,0.466364,0,3,105,70,346,3.0,92.0,80.0,376.0,836752724084922533;768579787521575291,367082587220462692;5131280576272319091;8689439...,"836752724084922533:4324484723289924768,3657871...",2018-09-07 00:00:00,7,0,0,4943913163084262584,836752724084922533;768579787521575291,367082587220462692;5131280576272319091;8689439...,3801992748557162347,4374800994578205793,7,9,10,17,1493508356721691818,1,1005,2002,3007,1088197280290283759,1536249600,4001,"836752724084922533:4324484723289924768,3657871...",5829729320339396622,14,1.000000,5012,0.981436,0.980990,0.987401,0,2018-09-07 00:00:00,7,0,0,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0,1002640977003914936,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0,1002640977003914936,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0
1,7563693237648713137,3,25,1,1,1,0,2.500000,0.000000,5.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3369.0,1275.0,4040.0,2.0,1.0,2.0,35.254001,252,28.000000,14.000000,5376.0,1.0,19723.0,27115.0,4405710,1210626.0,3.0,0.0,30.0,86.0,55540,8360.0,7.0,3.500000,3.500000,0.0,0.0,7.0,6,23,1,0.0,1,0.0,1,723,79,12,1,1,1,0.0,0,0,1,1,0,0,0.055804,0.317168,0.0,1.260637,0,52,78,940,5348,85.0,132.0,1189.0,7995.0,2018-09-07 00:00:00,7,0,5,3,25,1,1,1,0,2.500000,0.000000,5.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,860.0,304.0,1064.0,0.0,0.0,0.0,35.254001,252,28.000000,14.000000,1413.0,0.0,5612.0,7070.0,1125867,330746.0,0.0,0.0,0.0,2.0,6846,877.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,1,0.0,1,0.0,1,723,79,12,1,1,1,0.0,1,0,1,1,1,0,0.000000,0.028289,0.0,0.608065,0,52,78,940,5348,53.0,81.0,952.0,5582.0,836752724084922533;3613783563199627217;6370392...,6241534230954727302;367082587220462692;5977512...,"836752724084922533:1405752240728470138,2125982...",2018-09-07 00:00:00,7,0,0,1097656060630949565,836752724084922533;3613783563199627217;6370392...,6241534230954727302;367082587220462692;5977512...,8420832032159385750,196257267849351217,7,12,12,20,2535192701541505605,0,1005,2005,3002,4656934049025345586,1536249600,4001,"836752724084922533:1405752240728470138,2125982...",1924781308265458391,19,1.000000,5017,0.981413,0.981040,0.989620,0,2018-09-07 00:00:00,7,0,0,1,1,1,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-03 13:29:48,2018-09-07 00:00:00,2018-09-07 00:00:00,37812,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,7563693237648713137,1,1,1,0,0,0,0,1,-1,NaN,NaN,999999,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,7563693237648713137,1,1,1,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-03 13:29:48,2018-09-07 00:00:00,2018-09-07 00:00:00,37812,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
2,3325379761110661259,2,24,2,1,2,0,6.666667,0.000000,6.666667,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,243.0,410.0,0.0,2.0,2.0,40.298827,235,29.375000,14.687500,546.0,0.0,18742.0,12654.0,412495,71554.0,4.0,0.0,88.0,68.0,4728,563.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,2,0.0,2,0.0,2,364,14,2,1,1,1,0.0,1,0,1,1,0,0,0.732601,0.537379,0.0,1.146196,0,176,58,44,509,199.0,72.0,51.0,661.0,2018-09-07 00:00:00,7,0,5,2,24,2,1,2,0,6.666667,0.000000,6.666667,0.000000,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,33.0,328.0,480.0,0.0,0.0,1.0,40.298827,235,29.375000,14.687500,599.0,2.0,10131.0,7157.0,109743,23811.0,1.0,0.0,15.0,13.0,520,65.0,11.0,3.666667,2.333333,0.0,0.0,6.0,6,23,2,0.0,2,0.0,2,364,14,2,1,1,1,0.0,0,0,1,1,0,0,0.166945,0.181640,0.0,0.473834,0,176,58,44,509,204.0,65.0,44.0,530.0,836752724084922533;768579787521575291,3540471119339706981;5131280576272319091;302719...,"768579787521575291:3540471119339706981,5131280...",2018-09-07 00:00:00,7,0,0,4747706882249246504,836752724084922533;768579787521575291,3540471119339706981;5131280576272319091;302719...,6232396831040542357,8519578687848277273,6,14,13,17,8204445143641875432,0,1003,2004,3007,6544635643285905366,1536249600,4001,"768579787521575291:3540471119339706981,5131280...",8983666490462246326,23,0.995066,5020,0.974091,0.974842,0.967002,0,2018-09-07 00:00:00,7,0,0,2,2,2,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,3325379761110661259,2,2,2,0,0,0,0,1,-1,2018-09-06 23:57:11,NaN,86231,999999,0,0,0,0,1,-1,1,-1,2018-09-07 00:00:00,NaN,2018-09-07 00:00:00,NaN,0,999999,0,999999,0,0,0,2018-09-06 23:56:27,2018-09-06 23:56:27,2018-09-06 23:56:27,213,213,213,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,3325379761110661259,2,2,2,0,0,0,0,1,-1,2018-09-06 23:57:11,NaN,86231,999999,0,0,0,0,1,-1,1,-1,2018-09-07 00:00:00,NaN,2018-09-07 00:00:00,NaN,0,999999,0,999999,0,0,0,2018-09-06 23:56:27,2018-09-06 23:56:27,2018-09-06 23:56:27,213,213,213,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
3,6026863564044534796,2,20,6,1,2,0,6.666667,0.000000,2.857143,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,6.0,0.0,0.0,0.0,31.079815,136,17.000000,8.500000,147.0,0.0,6382.0,6861.0,17104,1309878.0,0.0,0.0,63.0,64.0,217,12905.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,4,0.0,2,2.0,2,133,12,1,1,1,1,0.0,1,0,1,1,1,0,0.000000,0.932809,0.0,1.268709,0,10,12,1958,6805,14.0,18.0,2497.0,9983.0,2018-09-07 00:00:00,7,0,5,2,20,6,1,2,0,6.666667,0.000000,2.857143,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,31.079815,136,17.000000,8.500000,80.0,0.0,1257.0,1330.0,4490,342180.0,0.0,0.0,8.0,9.0,45,1554.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,4,0.0,2,2.0,2,133,12,1,1,1,1,0.0,1,0,1,1,1,0,0.000000,0.676692,0.0,1.002227,0,10,12,1958,6805,10.0,13.0,1948.0,6822.0,836752724084922533;1909641874861640857,5977512434884267894;2072967855524022579;263639...,1036082357054043890:-1;8658630417297894718:-1;...,2018-09-07 00:00:00,7,0,0,6075147184977200133,836752724084922533;1909641874861640857,5977512434884267894;2072967855524022579;263639...,2143736106091506900,6219110439660858399,6,8,8,16,3370515857303357002,-1,-1,-1,-1,1591753168403833710,1536249600,4001,1036082357054043890:-1;8658630417297894718:-1;...,146460612484534365,19,0.979555,5016,0.957083,0.958109,0.951751,0,2018-09-07 00:00:00,7,0,0,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0,6026863564044534796,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0,6026863564044534796,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0
4,7074792290685319356,2,34,5,2,2,1,6.666667,0.285714,3.333333,3.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,945.0,170.0,1761.0,2.0,0.0,2.0,30.555430,260,26.000000,13.000000,2197.0,2.0,4177.0,4177.0,4405710,133820.0,4.0,0.0,9.0,9.0,55540,1636.0,11.0,3.666667,4.333333,0.0,0.0,8.0,6,23,3,0.0,3,0.0,3,1014,182,15,1,1,1,0.0,0,0,1,1,0,0,0.182066,0.215466,0.0,1.260637,0,43,43,152,687,51.0,51.0,190.0,1115.0,2018-09-07 00:00:00,7,0,5,2,34,5,2,2,1,6.666667,0.285714,3.333333,3.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,431.0,97.0,796.0,0.0,0.0,0.0,30.555430,260,26.000000,13.000000,1011.0,1.0,2589.0,2589.0,1125867,33116.0,0.0,0.0,2.0,2.0,6846,153.0,6.0,3.000000,5.000000,0.0,0.0,8.0,6,23,3,0.0,3,0.0,3,1014,182,15,1,1,1,0.0,0,0,1,1,1,0,0.000000,0.077250,0.0,0.608065,0,43,43,152,687,28.0,28.0,161.0,713.0,836752724084922533;768579787521575291,6241534230954727302;3540471119339706981;462193...,768579787521575291:-1;8096917686185033019:9148...,2018-09-07 00:00:00,7,0,0,7227779099688226563,836752724084922533;768579787521575291,6241534230954727302;3540471119339706981;462193...,8909918568166119776,3122721854741763495,8,13,13,19,4890272292782939403,0,1002,2005,3009,3421390014084173241,1536249600,4001,768579787521575291:-1;8096917686185033019:9148...,3685789896910492811,17,1.000000,5014,0.983497,0.983812,0.986854,0,2018-09-07 00:00:00,7,0,0,3,3,3,0,0,0,0,1,-1,2018-09-03 17:58:19,NaN,64699,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-01 09:33:42,2018-09-07 00:00:00,2018-09-07 00:00:00,51978,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0,7074792290685319356,3,3,3,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-06 23:41:20,2018-09-07 00:00:00,2018-09-07 00:00:00,1120,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0,7074792290685319356,3,3,3,0,0,0,0,1,-1,2018-09-03 17:58:19,NaN,64699,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-01 09:33:42,2018-09-07 00:00:00,2018-09-07 00:00:00,51978,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0

In [3]:
origin = [
    'item_price_level', 'item_sales_level', 'item_collected_level',
    'item_pv_level', 'user_gender_id', 'user_age_level', 'user_star_level',
    'context_page_id', 'shop_id', 'shop_review_num_level',
    'shop_review_positive_rate', 'shop_star_level', 'shop_score_service',
    'shop_score_delivery', 'shop_score_description'
]

features_pre5 = [
    'day', 'hour', 'minute', 'user_query_day', 'user_query_day_hour',
    'user_query_minute', 'item_category_split_count',
    'item_property_split_count', 'pred_category_split_count',
    'pred_property_split_count', 'item_pred_category_score',
    'item_pred_property_score', 'item_pred_category_score_item%',
    'item_pred_property_score_item%', 'item_pred_category_score_pred%',
    'item_pred_property_score_pred%', 'user_shop_count', 'user_item_count',
    'user_context_count', 'user_shop_trade_count', 'user_item_trade_count',
    'user_context_trade_count', 'user_brand_count', 'user_city_count',
    'user_brand_trade_count', 'user_city_trade_count', 'item_occupation_count',
    'item_age_count', 'item_gender_count', 'item_occupation_trade_count',
    'item_age_trade_count', 'item_gender_trade_count', 'shop_score',
    'item_score', 'item_score2', 'item_score3', 'item_hot', 'user_hot',
    'shop_hot', 'brand_hot', 'occupation_hot', 'city_hot', 'item_trade_hot',
    'user_trade_hot', 'shop_trade_hot', 'brand_trade_hot',
    'occupation_trade_hot', 'city_trade_hot', 'user_sell_power',
    'user_sell_power_mean', 'user_sell_power_mean_item_minus',
    'user_sell_trade_power', 'user_sell_trade_power_mean',
    'user_sell_trade_power_mean_item_minus', 'yesterday', 'yesterhour',
    'user_day_query', 'user_yesterday_query', 'user_hour_query',
    'user_yesterhour_query', 'user_minute_query', 'item_day_query',
    'item_hour_query', 'item_minute_query', 'user_item_day_query',
    'user_item_hour_query', 'user_item_minute_query', 'min_time',
    'user_is_his', 'item_is_his', 'brand_is_his', 'user_is_trade_his',
    'item_is_trade_his', 'brand_is_trade_his', 'user_count', 'user_day_count',
    'user_hour_count', 'user_minute_count', 'item_trade_percent',
    'brand_trade_percent', 'user_trade_percent', 'occupation_trade_percent',
    'is_home', 'shop_item_count', 'brand_item_count', 'city_brand_count',
    'city_item_count', 'shop_item_count_his', 'brand_item_count_his',
    'city_brand_count_his', 'city_item_count_his', 'next_time_sub',
    'last_time_sub', 'user_item_num', 'user_shop_num', 'user_item_day_num',
    'user_shop_day_num', 'user_item_next_time_sub', 'user_item_last_time_sub',
    'user_shop_next_time_sub', 'user_shop_last_time_sub',
    'user_count_first_time_sub', 'user_item_count_first_time_sub',
    'user_shop_count_first_time_sub', 'max_click', 'is_last_click',
    'max_user_item_click', 'is_last_user_item_click', 'max_click_time_sub',
    'max_user_item_click_time_sub'
]

features_6 = [
    'user_shop_count_6', 'user_item_count_6', 'user_context_count_6',
    'user_shop_trade_count_6', 'user_item_trade_count_6',
    'user_context_trade_count_6', 'user_brand_count_6', 'user_city_count_6',
    'user_brand_trade_count_6', 'user_city_trade_count_6',
    'item_occupation_count_6', 'item_age_count_6', 'item_gender_count_6',
    'item_occupation_trade_count_6', 'item_age_trade_count_6',
    'item_gender_trade_count_6', 'shop_score_6', 'item_score_6',
    'item_score2_6', 'item_score3_6', 'item_hot_6', 'user_hot_6', 'shop_hot_6',
    'brand_hot_6', 'occupation_hot_6', 'city_hot_6', 'item_trade_hot_6',
    'user_trade_hot_6', 'shop_trade_hot_6', 'brand_trade_hot_6',
    'occupation_trade_hot_6', 'city_trade_hot_6', 'user_sell_power_6',
    'user_sell_power_mean_6', 'user_sell_power_mean_item_minus_6',
    'user_sell_trade_power_6', 'user_sell_trade_power_mean_6',
    'user_sell_trade_power_mean_item_minus_6', 'yesterday_6', 'yesterhour_6',
    'user_day_query_6', 'user_yesterday_query_6', 'user_hour_query_6',
    'user_yesterhour_query_6', 'user_minute_query_6', 'item_day_query_6',
    'item_hour_query_6', 'item_minute_query_6', 'user_item_day_query_6',
    'user_item_hour_query_6', 'user_item_minute_query_6', 'min_time_6',
    'user_is_his_6', 'item_is_his_6', 'brand_is_his_6', 'user_is_trade_his_6',
    'item_is_trade_his_6', 'brand_is_trade_his_6', 'user_count_6',
    'user_day_count_6', 'user_hour_count_6', 'user_minute_count_6',
    'item_trade_percent_6', 'brand_trade_percent_6', 'user_trade_percent_6',
    'occupation_trade_percent_6', 'is_home_6', 'shop_item_count_6',
    'brand_item_count_6', 'city_brand_count_6', 'city_item_count_6',
    'shop_item_count_his_6', 'brand_item_count_his_6',
    'city_brand_count_his_6', 'city_item_count_his_6', 'next_time_sub_6',
    'last_time_sub_6', 'user_item_num_6', 'user_shop_num_6',
    'user_item_day_num_6', 'user_shop_day_num_6', 'user_item_next_time_sub_6',
    'user_item_last_time_sub_6', 'user_shop_next_time_sub_6',
    'user_shop_last_time_sub_6', 'user_count_first_time_sub_6',
    'user_item_count_first_time_sub_6', 'user_shop_count_first_time_sub_6',
    'max_click_6', 'is_last_click_6', 'max_user_item_click_6',
    'is_last_user_item_click_6', 'max_click_time_sub_6',
    'max_user_item_click_time_sub_6'
]

features_fulltime = [
    'user_count_full_time', 'user_day_count_full_time',
    'user_hour_count_full_time', 'user_minute_count_full_time',
    'next_time_sub_full_time', 'last_time_sub_full_time',
    'user_item_num_full_time', 'user_shop_num_full_time',
    'user_item_day_num_full_time', 'user_shop_day_num_full_time',
    'user_item_next_time_sub_full_time', 'user_item_last_time_sub_full_time',
    'user_shop_next_time_sub_full_time', 'user_shop_last_time_sub_full_time',
    'user_count_first_time_sub_full_time',
    'user_item_count_first_time_sub_full_time',
    'user_shop_count_first_time_sub_full_time', 'max_click_full_time',
    'is_last_click_full_time', 'max_user_item_click_full_time',
    'is_last_user_item_click_full_time', 'max_user_item_click_time_sub_full_time'
]

target = ['is_trade']

In [4]:
sub_features = []
for i in features_6:
    tmp = str(i[:-2] + '_pre5_6_sub')
    train[tmp] = abs(train[i[:-2]] - train[i])
    sub_features.append(tmp)
len(sub_features)

94

In [5]:
# train.to_csv('train_zero_new.csv', index=None)

In [13]:
predictors = [
    'brand_hot', 'brand_is_trade_his', 'brand_item_count',
    'brand_item_count_his', 'brand_trade_hot', 'brand_trade_percent',
    'city_brand_count', 'city_brand_count_his', 'city_hot', 'city_item_count',
    'city_item_count_his', 'city_trade_hot', 'hour', 'item_age_trade_count',
    'item_category_split_count', 'item_day_query', 'item_gender_count',
    'item_gender_trade_count', 'item_hot', 'item_is_trade_his',
    'item_minute_query', 'item_occupation_count',
    'item_occupation_trade_count', 'item_pred_category_score',
    'item_pred_category_score_item%', 'item_pred_property_score',
    'item_pred_property_score_item%', 'item_pred_property_score_pred%',
    'item_property_split_count', 'item_trade_hot', 'item_trade_percent',
    'last_time_sub', 'min_time', 'next_time_sub', 'shop_hot',
    'shop_item_count', 'shop_item_count_his', 'shop_score', 'shop_trade_hot',
    'user_brand_count', 'user_city_count', 'user_count', 'user_day_count',
    'user_day_query', 'user_hot', 'user_hour_count', 'user_hour_query',
    'user_is_his', 'user_item_count', 'user_item_day_num',
    'user_item_day_query', 'user_item_hour_query', 'user_item_next_time_sub',
    'user_item_num', 'user_minute_count', 'user_minute_query',
    'user_query_day', 'user_query_day_hour', 'user_query_minute',
    'user_sell_power', 'user_sell_power_mean',
    'user_sell_power_mean_item_minus', 'user_shop_count', 'user_shop_day_num',
    'user_shop_num', 'yesterhour', 'user_item_last_time_sub',
    'user_shop_next_time_sub', 'user_shop_last_time_sub',
    'user_count_first_time_sub', 'user_item_count_first_time_sub',
    'user_shop_count_first_time_sub', 'max_click', 'is_last_click',
    'max_user_item_click', 'is_last_user_item_click', 'max_click_time_sub',
    'max_user_item_click_time_sub', 'user_shop_count_6', 'user_item_count_6',
    'user_brand_count_6', 'user_city_count_6', 'item_gender_count_6',
    'item_occupation_trade_count_6', 'item_age_trade_count_6',
    'item_gender_trade_count_6', 'shop_score_6', 'item_hot_6', 'user_hot_6',
    'shop_hot_6', 'brand_hot_6', 'city_hot_6', 'item_trade_hot_6',
    'shop_trade_hot_6', 'brand_trade_hot_6', 'city_trade_hot_6',
    'user_sell_power_6', 'user_sell_power_mean_6',
    'user_sell_power_mean_item_minus_6', 'yesterhour_6', 'user_day_query_6',
    'user_hour_query_6', 'user_minute_query_6', 'item_day_query_6',
    'item_minute_query_6', 'user_item_day_query_6', 'user_item_hour_query_6',
    'min_time_6', 'user_is_his_6', 'item_is_trade_his_6',
    'brand_is_trade_his_6', 'user_count_6', 'user_day_count_6',
    'user_hour_count_6', 'user_minute_count_6', 'item_trade_percent_6',
    'brand_trade_percent_6', 'shop_item_count_6', 'brand_item_count_6',
    'city_brand_count_6', 'city_item_count_6', 'shop_item_count_his_6',
    'brand_item_count_his_6', 'city_brand_count_his_6',
    'city_item_count_his_6', 'next_time_sub_6', 'last_time_sub_6',
    'user_item_num_6', 'user_shop_num_6', 'user_item_day_num_6',
    'user_shop_day_num_6', 'user_item_next_time_sub_6',
    'user_item_last_time_sub_6', 'user_shop_next_time_sub_6',
    'user_shop_last_time_sub_6', 'user_count_first_time_sub_6',
    'user_item_count_first_time_sub_6', 'user_shop_count_first_time_sub_6',
    'max_click_6', 'is_last_click_6', 'max_user_item_click_6',
    'is_last_user_item_click_6', 'max_click_time_sub_6',
    'max_user_item_click_time_sub_6', 'user_count_full_time',
    'user_day_count_full_time', 'user_hour_count_full_time',
    'user_minute_count_full_time', 'next_time_sub_full_time',
    'last_time_sub_full_time', 'user_item_num_full_time',
    'user_shop_num_full_time', 'user_item_day_num_full_time',
    'user_shop_day_num_full_time', 'user_item_next_time_sub_full_time',
    'user_item_last_time_sub_full_time', 'user_shop_next_time_sub_full_time',
    'user_shop_last_time_sub_full_time', 'user_count_first_time_sub_full_time',
    'user_item_count_first_time_sub_full_time',
    'user_shop_count_first_time_sub_full_time', 'max_click_full_time',
    'is_last_click_full_time', 'max_user_item_click_full_time',
    'is_last_user_item_click_full_time',
    'max_user_item_click_time_sub_full_time', 'user_shop_count_pre5_6_sub',
    'user_item_count_pre5_6_sub', 'user_brand_count_pre5_6_sub',
    'item_occupation_count_pre5_6_sub', 'item_gender_count_pre5_6_sub',
    'item_occupation_trade_count_pre5_6_sub',
    'item_age_trade_count_pre5_6_sub', 'item_gender_trade_count_pre5_6_sub',
    'item_hot_pre5_6_sub', 'user_hot_pre5_6_sub', 'shop_hot_pre5_6_sub',
    'brand_hot_pre5_6_sub', 'city_hot_pre5_6_sub', 'item_trade_hot_pre5_6_sub',
    'user_trade_hot_pre5_6_sub', 'shop_trade_hot_pre5_6_sub',
    'brand_trade_hot_pre5_6_sub', 'city_trade_hot_pre5_6_sub',
    'user_sell_power_pre5_6_sub', 'user_sell_power_mean_pre5_6_sub',
    'user_sell_power_mean_item_minus_pre5_6_sub',
    'brand_is_trade_his_pre5_6_sub', 'item_trade_percent_pre5_6_sub',
    'brand_trade_percent_pre5_6_sub', 'shop_item_count_his_pre5_6_sub',
    'brand_item_count_his_pre5_6_sub', 'city_brand_count_his_pre5_6_sub',
    'city_item_count_his_pre5_6_sub', 'next_time_sub_pre5_6_sub',
    'user_item_next_time_sub_pre5_6_sub', 'user_shop_next_time_sub_pre5_6_sub'
]

len(predictors)

197