In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import time
from tqdm import tqdm

%matplotlib inline

#每次可以输出多个变量
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from pylab import rcParams
rcParams['figure.figsize'] = 14, 6

import warnings
warnings.filterwarnings("ignore")

#中文字体
import matplotlib
matplotlib.use('qt4agg')
#指定默认字体
matplotlib.rcParams['font.sans-serif'] = ['SimHei']
matplotlib.rcParams['font.family'] = 'sans-serif'
#解决负号'-'显示为方块的问题
matplotlib.rcParams['axes.unicode_minus'] = False

In [21]:
df = pd.read_csv('df.txt', sep=' ')
test = pd.read_csv('test.txt', sep=' ')

df.shape
df.head()
test.shape
test.head()

(478138, 27)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade
0,108641074714126964,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,4505772604969228686,1,1003,2005,3003,282924576738839389,1537236544,4006,5799347067982556520:-1;509660095530134768:-1;5...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
1,5754713551599725161,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2692638157208937547,0,1002,2005,3006,4007979028023783431,1537243232,4001,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
2,842679481291040981,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,5247924392014515924,0,1003,2005,3004,4884875192608989870,1537211052,4001,5799347067982556520:5131280576272319091;725801...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
3,937088850059189027,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2681414445369714628,1,1004,2005,3006,840119421106178602,1537222670,4016,509660095530134768:-1;5799347067982556520:-1;7...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
4,7975697065017708072,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2729475788342039013,0,1002,2005,3001,1736769971710354684,1537271320,4001,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0

(18371, 26)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description
0,2475218615076601065,2275895163219263378,7908382889764677758;8277336076276184272,2636395404473730413;7515802706813700848;302719...,7838285046767229711,7534238860363577544,7,6,8,14,4379490381248358680,0,1002,2005,3001,2858926263178884522,1537885700,4005,8277336076276184272:-1;5799347067982556520:-1;...,5275548996133547595,13,0.985244,5011,0.964023,0.966550,0.955378
1,398316874173557226,7096238490711246967,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;734498...,8126195666233054089,3948283326616421003,6,9,8,16,2629129219935839101,1,1004,2002,3006,4014843148303402290,1537862843,4001,"5755694407684602296:216555019471416386,2636395...",329470548383752413,14,0.989068,5012,0.963794,0.964225,0.959134
2,6586402638209028583,7096238490711246967,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;734498...,8126195666233054089,3948283326616421003,6,9,8,16,1092007111346257147,0,1004,2002,3004,8141706531104182980,1537858222,4011,5755694407684602296:2636395404473730413;871073...,329470548383752413,14,0.989068,5012,0.963794,0.964225,0.959134
3,1040996105851528465,7096238490711246967,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;734498...,8126195666233054089,3948283326616421003,6,9,8,16,5353289677517820939,1,1003,2002,3007,5878932623083097102,1537860915,4001,8710739180200009128:-1;5755694407684602296:263...,329470548383752413,14,0.989068,5012,0.963794,0.964225,0.959134
4,6316278569655873454,7096238490711246967,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;734498...,8126195666233054089,3948283326616421003,6,9,8,16,1098833840660870025,0,1002,2003,3002,7218739953079190510,1537859074,4001,5755694407684602296:5131280576272319091;871073...,329470548383752413,14,0.989068,5012,0.963794,0.964225,0.959134

In [22]:
test['is_trade'] = -1

df = pd.concat([df, test])

In [23]:
df['item_category_split'] = df.item_category_list.apply(lambda x: x.split(';'))
df['item_property_split'] = df.item_property_list.apply(lambda x: x.split(';'))
df['predict_category_split'] = df.predict_category_property.apply(
    lambda x: x.split(';'))

df['item_category_split_count'] = df.item_category_split.apply(
    lambda x: len(x))
df['item_property_split_count'] = df.item_property_split.apply(
    lambda x: len(x))
df['predict_category_split_count'] = df.predict_category_split.apply(
    lambda x: len(x))

In [24]:
int((max(df.context_timestamp) - min(df.context_timestamp)) / 3)
min(df.context_timestamp) + 201595

230388

1537401596

In [25]:
#4天做历史数据，2天做训练和验证数据
his = df[(df.context_timestamp > 1537401596) & (df.is_trade != -1)]
train = df[(df.context_timestamp <= 1537401596) | (df.is_trade == -1)]

# del df

his.shape
train.shape

his_trade = his[his.is_trade == 1]

(323527, 33)

(172982, 33)

In [26]:
#user_shop_count user_item_count user_context_count
user_shop_count = his.groupby(
    ['user_id', 'shop_id'], as_index=False)['user_id'].agg({
        'user_shop_count':
        'count'
    })
train = train.merge(user_shop_count, on=['user_id', 'shop_id'], how='left')

user_item_count = his.groupby(
    ['user_id', 'item_id'], as_index=False)['user_id'].agg({
        'user_item_count':
        'count'
    })
train = train.merge(user_item_count, on=['user_id', 'item_id'], how='left')

user_context_count = his.groupby(
    ['user_id', 'context_id'], as_index=False)['user_id'].agg({
        'user_context_count':
        'count'
    })
train = train.merge(
    user_context_count, on=['user_id', 'context_id'], how='left')

#trade
user_shop_trade_count = his_trade.groupby(
    ['user_id', 'shop_id'], as_index=False)['user_id'].agg({
        'user_shop_trade_count':
        'count'
    })
train = train.merge(
    user_shop_trade_count, on=['user_id', 'shop_id'], how='left')

user_item_trade_count = his_trade.groupby(
    ['user_id', 'item_id'], as_index=False)['user_id'].agg({
        'user_item_trade_count':
        'count'
    })
train = train.merge(
    user_item_trade_count, on=['user_id', 'item_id'], how='left')

user_context_trade_count = his_trade.groupby(
    ['user_id', 'context_id'], as_index=False)['user_id'].agg({
        'user_context_trade_count':
        'count'
    })
train = train.merge(
    user_context_trade_count, on=['user_id', 'context_id'], how='left')

train[[
    'user_shop_count', 'user_item_count', 'user_context_count',
    'user_shop_trade_count', 'user_item_trade_count',
    'user_context_trade_count'
]] = train[[
    'user_shop_count', 'user_item_count', 'user_context_count',
    'user_shop_trade_count', 'user_item_trade_count',
    'user_context_trade_count'
]].fillna(0)

In [27]:
#user_brand_count user_city_count
user_brand_count = his.groupby(
    ['user_id', 'item_brand_id'], as_index=False)['user_id'].agg({
        'user_brand_count':
        'count'
    })
train = train.merge(
    user_brand_count, on=['user_id', 'item_brand_id'], how='left')

user_city_count = his.groupby(
    ['user_id', 'item_city_id'], as_index=False)['user_id'].agg({
        'user_city_count':
        'count'
    })
train = train.merge(
    user_city_count, on=['user_id', 'item_city_id'], how='left')

#trade
user_brand_trade_count = his_trade.groupby(
    ['user_id', 'item_brand_id'], as_index=False)['user_id'].agg({
        'user_brand_trade_count':
        'count'
    })
train = train.merge(
    user_brand_trade_count, on=['user_id', 'item_brand_id'], how='left')

user_city_trade_count = his_trade.groupby(
    ['user_id', 'item_city_id'], as_index=False)['user_id'].agg({
        'user_city_trade_count':
        'count'
    })
train = train.merge(
    user_city_trade_count, on=['user_id', 'item_city_id'], how='left')

train[[
    'user_brand_count', 'user_city_count', 'user_brand_trade_count',
    'user_city_trade_count'
]] = train[[
    'user_brand_count', 'user_city_count', 'user_brand_trade_count',
    'user_city_trade_count'
]].fillna(0)

In [28]:
#item_occupation_count item_age_count item_gender_count
item_occupation_count = his.groupby(
    ['item_id', 'user_occupation_id'], as_index=False)['item_id'].agg({
        'item_occupation_count':
        'count'
    })
train = train.merge(
    item_occupation_count, on=['item_id', 'user_occupation_id'], how='left')

item_age_count = his.groupby(
    ['item_id', 'user_age_level'], as_index=False)['item_id'].agg({
        'item_age_count':
        'count'
    })
train = train.merge(
    item_age_count, on=['item_id', 'user_age_level'], how='left')

item_gender_count = his.groupby(
    ['item_id', 'user_gender_id'], as_index=False)['item_id'].agg({
        'item_gender_count':
        'count'
    })
train = train.merge(
    item_gender_count, on=['item_id', 'user_gender_id'], how='left')

#trade
item_occupation_trade_count = his_trade.groupby(
    ['item_id', 'user_occupation_id'], as_index=False)['item_id'].agg({
        'item_occupation_trade_count':
        'count'
    })
train = train.merge(
    item_occupation_trade_count,
    on=['item_id', 'user_occupation_id'],
    how='left')

item_age_trade_count = his_trade.groupby(
    ['item_id', 'user_age_level'], as_index=False)['item_id'].agg({
        'item_age_trade_count':
        'count'
    })
train = train.merge(
    item_age_trade_count, on=['item_id', 'user_age_level'], how='left')

item_gender_trade_count = his_trade.groupby(
    ['item_id', 'user_gender_id'], as_index=False)['item_id'].agg({
        'item_gender_trade_count':
        'count'
    })
train = train.merge(
    item_gender_trade_count, on=['item_id', 'user_gender_id'], how='left')

train[[
    'item_occupation_count', 'item_age_count', 'item_gender_count',
    'item_occupation_trade_count', 'item_age_trade_count',
    'item_gender_trade_count'
]] = train[[
    'item_occupation_count', 'item_age_count', 'item_gender_count',
    'item_occupation_trade_count', 'item_age_trade_count',
    'item_gender_trade_count'
]].fillna(0)

In [29]:
#shop_score = (star + review_num * review_positive) * service * delivery * description
train.shop_star_level = train.shop_star_level - min(train.shop_star_level)

train['shop_score'] = (
    train.shop_star_level +
    train.shop_review_num_level * train.shop_review_positive_rate
) * train.shop_score_service * train.shop_score_delivery * train.shop_score_description

In [30]:
train.context_page_id = train.context_page_id - min(train.context_page_id)

In [31]:
#item_score = (sales + collected + pv)
#item_score2 = (sales + collected + pv) / price
#item_score2 = ((sales + collected + pv) / price) / (page + 1)

train['item_score'] = (
    train.item_sales_level + train.item_collected_level * train.item_pv_level)
train['item_score2'] = (
    train.item_sales_level + train.item_collected_level * train.item_pv_level
) / train.item_price_level
train['item_score3'] = (
    (train.item_sales_level + train.item_collected_level * train.item_pv_level
     ) / train.item_price_level) / (train.context_page_id + 1)

In [32]:
def pred_split(x):
    pred = []
    tmp = x.split(';')
    for i in range(0, len(tmp)):
        pred.append(tmp[i].split(':'))
    return pred


def predict_category_split(x):
    pred = []
    for i in range(0, len(x)):
        pred.append(x[i][0])
    return pred


def predict_property_split(x):
    pred = []
    for i in range(0, len(x)):
        for j in range(1, len(x[i])):
            if (x[i][j] != '-1'):
                pred.append(x[i][j])
    return pred

In [33]:
train[
    'predict_category_property_split'] = train.predict_category_property.apply(
        lambda x: pred_split(x))

train['predict_category_split'] = train.predict_category_property_split.apply(
    lambda x: predict_category_split(x))

train['predict_property_split'] = train.predict_category_property_split.apply(
    lambda x: predict_property_split(x))

In [34]:
def item_pred_category_score(x):
    return len(
        list(
            set(x.item_category_split).intersection(
                set(x.predict_category_split))))


def item_pred_property_score(x):
    return len(
        list(
            set(x.item_property_split).intersection(
                set(x.predict_property_split))))

In [35]:
train['pred_category_split_count'] = train.predict_category_split.apply(
    lambda x: len(x))
train['pred_property_split_count'] = train.predict_property_split.apply(
    lambda x: len(x))

train['item_pred_category_score'] = train.apply(
    item_pred_category_score, axis=1)
train['item_pred_property_score'] = train.apply(
    item_pred_property_score, axis=1)

train[
    'item_pred_category_score_item%'] = train.item_pred_category_score / train.item_category_split_count
train[
    'item_pred_property_score_item%'] = train.item_pred_property_score / train.item_property_split_count

train[
    'item_pred_category_score_pred%'] = train.item_pred_category_score / train.pred_category_split_count
train[
    'item_pred_property_score_pred%'] = train.item_pred_property_score / train.pred_property_split_count

In [36]:
train.shape
train.head()

(172982, 63)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,item_category_split,item_property_split,predict_category_split,item_category_split_count,item_property_split_count,predict_category_split_count,user_shop_count,user_item_count,user_context_count,user_shop_trade_count,user_item_trade_count,user_context_trade_count,user_brand_count,user_city_count,user_brand_trade_count,user_city_trade_count,item_occupation_count,item_age_count,item_gender_count,item_occupation_trade_count,item_age_trade_count,item_gender_trade_count,shop_score,item_score,item_score2,item_score3,predict_category_property_split,predict_property_split,pred_category_split_count,pred_property_split_count,item_pred_category_score,item_pred_property_score,item_pred_category_score_item%,item_pred_property_score_item%,item_pred_category_score_pred%,item_pred_property_score_pred%
0,108641074714126964,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,4505772604969228686,1,1003,2005,3003,282924576738839389,1537236544,5,5799347067982556520:-1;509660095530134768:-1;5...,6765930309048922341,4,1.0,3,1.0,1.0,1.0,0,"[7908382889764677758, 5799347067982556520]","[2072967855524022579, 5131280576272319091, 263...","[5799347067982556520, 509660095530134768, 5755...",2,22,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,6.0,3.0,2.0,0.0,0.0,0.0,7.0,59,19.666667,3.277778,"[[5799347067982556520, -1], [50966009553013476...",[9148482949976129397],5,1,2,0,1.0,0.000000,0.400000,0.000000
1,5754713551599725161,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2692638157208937547,0,1002,2005,3006,4007979028023783431,1537243232,0,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,3,1.0,1.0,1.0,0,"[7908382889764677758, 5799347067982556520]","[2072967855524022579, 5131280576272319091, 263...","[5799347067982556520, 7908382889764677758]",2,22,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,5.0,0.0,0.0,0.0,7.0,59,19.666667,19.666667,"[[5799347067982556520, 9172976955054793469], [...","[9172976955054793469, 1787573075717641245,9172...",2,2,2,1,1.0,0.045455,1.000000,0.500000
2,842679481291040981,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,5247924392014515924,0,1003,2005,3004,4884875192608989870,1537211052,0,5799347067982556520:5131280576272319091;725801...,6765930309048922341,4,1.0,3,1.0,1.0,1.0,0,"[7908382889764677758, 5799347067982556520]","[2072967855524022579, 5131280576272319091, 263...","[5799347067982556520, 7258015885215914736, 790...",2,22,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,3.0,5.0,0.0,0.0,0.0,7.0,59,19.666667,19.666667,"[[5799347067982556520, 5131280576272319091], [...","[5131280576272319091, 5131280576272319091, 513...",3,3,2,1,1.0,0.045455,0.666667,0.333333
3,937088850059189027,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2681414445369714628,1,1004,2005,3006,840119421106178602,1537222670,15,509660095530134768:-1;5799347067982556520:-1;7...,6765930309048922341,4,1.0,3,1.0,1.0,1.0,0,"[7908382889764677758, 5799347067982556520]","[2072967855524022579, 5131280576272319091, 263...","[509660095530134768, 5799347067982556520, 7908...",2,22,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,2.0,2.0,0.0,0.0,0.0,7.0,59,19.666667,1.229167,"[[509660095530134768, -1], [579934706798255652...","[1787573075717641245,9148482949976129397, 9148...",5,3,2,0,1.0,0.000000,0.400000,0.000000
4,7975697065017708072,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2729475788342039013,0,1002,2005,3001,1736769971710354684,1537271320,0,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,3,1.0,1.0,1.0,0,"[7908382889764677758, 5799347067982556520]","[2072967855524022579, 5131280576272319091, 263...","[5799347067982556520, 7908382889764677758]",2,22,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,5.0,0.0,0.0,0.0,7.0,59,19.666667,19.666667,"[[5799347067982556520, 9172976955054793469], [...","[9172976955054793469, 9172976955054793469]",2,2,2,1,1.0,0.045455,1.000000,0.500000

In [37]:
train.to_csv('train_preprocessing42.csv', index=False)
his.to_csv('his_preprocessing42.csv', index=False)