In [74]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import time
from tqdm import tqdm

%matplotlib inline

#每次可以输出多个变量
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from pylab import rcParams
rcParams['figure.figsize'] = 14, 6

import warnings
warnings.filterwarnings("ignore")

#中文字体
import matplotlib
matplotlib.use('qt4agg')
#指定默认字体
matplotlib.rcParams['font.sans-serif'] = ['SimHei']
matplotlib.rcParams['font.family'] = 'sans-serif'
#解决负号'-'显示为方块的问题
matplotlib.rcParams['axes.unicode_minus'] = False

In [75]:
df = pd.read_csv('df.txt', sep=' ')
test = pd.read_csv('test.txt', sep=' ')

df.shape
df.head()
test.shape
test.head()

(478138, 27)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade
0,108641074714126964,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,4505772604969228686,1,1003,2005,3003,282924576738839389,1537236544,4006,5799347067982556520:-1;509660095530134768:-1;5...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
1,5754713551599725161,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2692638157208937547,0,1002,2005,3006,4007979028023783431,1537243232,4001,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
2,842679481291040981,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,5247924392014515924,0,1003,2005,3004,4884875192608989870,1537211052,4001,5799347067982556520:5131280576272319091;725801...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
3,937088850059189027,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2681414445369714628,1,1004,2005,3006,840119421106178602,1537222670,4016,509660095530134768:-1;5799347067982556520:-1;7...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
4,7975697065017708072,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2729475788342039013,0,1002,2005,3001,1736769971710354684,1537271320,4001,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0

(18371, 26)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description
0,2475218615076601065,2275895163219263378,7908382889764677758;8277336076276184272,2636395404473730413;7515802706813700848;302719...,7838285046767229711,7534238860363577544,7,6,8,14,4379490381248358680,0,1002,2005,3001,2858926263178884522,1537885700,4005,8277336076276184272:-1;5799347067982556520:-1;...,5275548996133547595,13,0.985244,5011,0.964023,0.966550,0.955378
1,398316874173557226,7096238490711246967,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;734498...,8126195666233054089,3948283326616421003,6,9,8,16,2629129219935839101,1,1004,2002,3006,4014843148303402290,1537862843,4001,"5755694407684602296:216555019471416386,2636395...",329470548383752413,14,0.989068,5012,0.963794,0.964225,0.959134
2,6586402638209028583,7096238490711246967,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;734498...,8126195666233054089,3948283326616421003,6,9,8,16,1092007111346257147,0,1004,2002,3004,8141706531104182980,1537858222,4011,5755694407684602296:2636395404473730413;871073...,329470548383752413,14,0.989068,5012,0.963794,0.964225,0.959134
3,1040996105851528465,7096238490711246967,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;734498...,8126195666233054089,3948283326616421003,6,9,8,16,5353289677517820939,1,1003,2002,3007,5878932623083097102,1537860915,4001,8710739180200009128:-1;5755694407684602296:263...,329470548383752413,14,0.989068,5012,0.963794,0.964225,0.959134
4,6316278569655873454,7096238490711246967,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;734498...,8126195666233054089,3948283326616421003,6,9,8,16,1098833840660870025,0,1002,2003,3002,7218739953079190510,1537859074,4001,5755694407684602296:5131280576272319091;871073...,329470548383752413,14,0.989068,5012,0.963794,0.964225,0.959134

In [76]:
test['is_trade'] = -1

df = pd.concat([df, test])

In [77]:
df['item_category_split'] = df.item_category_list.apply(lambda x: x.split(';'))
df['item_property_split'] = df.item_property_list.apply(lambda x: x.split(';'))
df['predict_category_property_split'] = df.predict_category_property.apply(
    lambda x: x.split(';'))

df['item_category_split_count'] = df.item_category_split.apply(
    lambda x: len(x))
df['item_property_split_count'] = df.item_property_split.apply(
    lambda x: len(x))

In [78]:
#time
def timestamp_datetime(value):
    format = '%Y-%m-%d %H:%M:%S'
    value = time.localtime(value)
    dt = time.strftime(format, value)
    return dt


def convert_data(data):
    data['time'] = data.context_timestamp.apply(timestamp_datetime)
    data['day'] = data.time.apply(lambda x: int(x[8:10]))
    data['hour'] = data.time.apply(lambda x: int(x[11:13]))
    user_query_day = data.groupby(
        ['user_id',
         'day']).size().reset_index().rename(columns={
             0: 'user_query_day'
         })
    data = pd.merge(data, user_query_day, 'left', on=['user_id', 'day'])
    user_query_day_hour = data.groupby(
        ['user_id', 'day',
         'hour']).size().reset_index().rename(columns={
             0: 'user_query_day_hour'
         })
    data = pd.merge(
        data, user_query_day_hour, 'left', on=['user_id', 'day', 'hour'])
    return data


df = convert_data(df)

In [79]:
#18、19、20、21、22天做历史数据，23、24天做训练和验证数据
his = df[(df.day != 23) & (df.day != 24) & (df.is_trade != -1)]
train = df[(df.day == 23) | (df.day == 24) | (df.is_trade == -1)]

# del df

his.shape
train.shape
his_trade = his[his.is_trade == 1]

#(357103, 37)
#(121035, 37) 无test

(357103, 37)

(139406, 37)

In [80]:
#user_shop_count user_item_count user_context_count
user_shop_count = his.groupby(
    ['user_id', 'shop_id'], as_index=False)['user_id'].agg({
        'user_shop_count':
        'count'
    })
train = train.merge(user_shop_count, on=['user_id', 'shop_id'], how='left')

user_item_count = his.groupby(
    ['user_id', 'item_id'], as_index=False)['user_id'].agg({
        'user_item_count':
        'count'
    })
train = train.merge(user_item_count, on=['user_id', 'item_id'], how='left')

user_context_count = his.groupby(
    ['user_id', 'context_id'], as_index=False)['user_id'].agg({
        'user_context_count':
        'count'
    })
train = train.merge(
    user_context_count, on=['user_id', 'context_id'], how='left')

#trade
user_shop_trade_count = his_trade.groupby(
    ['user_id', 'shop_id'], as_index=False)['user_id'].agg({
        'user_shop_trade_count':
        'count'
    })
train = train.merge(
    user_shop_trade_count, on=['user_id', 'shop_id'], how='left')

user_item_trade_count = his_trade.groupby(
    ['user_id', 'item_id'], as_index=False)['user_id'].agg({
        'user_item_trade_count':
        'count'
    })
train = train.merge(
    user_item_trade_count, on=['user_id', 'item_id'], how='left')

user_context_trade_count = his_trade.groupby(
    ['user_id', 'context_id'], as_index=False)['user_id'].agg({
        'user_context_trade_count':
        'count'
    })
train = train.merge(
    user_context_trade_count, on=['user_id', 'context_id'], how='left')

train[[
    'user_shop_count', 'user_item_count', 'user_context_count',
    'user_shop_trade_count', 'user_item_trade_count',
    'user_context_trade_count'
]] = train[[
    'user_shop_count', 'user_item_count', 'user_context_count',
    'user_shop_trade_count', 'user_item_trade_count',
    'user_context_trade_count'
]].fillna(0)

In [81]:
#user_brand_count user_city_count
user_brand_count = his.groupby(
    ['user_id', 'item_brand_id'], as_index=False)['user_id'].agg({
        'user_brand_count':
        'count'
    })
train = train.merge(
    user_brand_count, on=['user_id', 'item_brand_id'], how='left')

user_city_count = his.groupby(
    ['user_id', 'item_city_id'], as_index=False)['user_id'].agg({
        'user_city_count':
        'count'
    })
train = train.merge(
    user_city_count, on=['user_id', 'item_city_id'], how='left')

#trade
user_brand_trade_count = his_trade.groupby(
    ['user_id', 'item_brand_id'], as_index=False)['user_id'].agg({
        'user_brand_trade_count':
        'count'
    })
train = train.merge(
    user_brand_trade_count, on=['user_id', 'item_brand_id'], how='left')

user_city_trade_count = his_trade.groupby(
    ['user_id', 'item_city_id'], as_index=False)['user_id'].agg({
        'user_city_trade_count':
        'count'
    })
train = train.merge(
    user_city_trade_count, on=['user_id', 'item_city_id'], how='left')

train[[
    'user_brand_count', 'user_city_count', 'user_brand_trade_count',
    'user_city_trade_count'
]] = train[[
    'user_brand_count', 'user_city_count', 'user_brand_trade_count',
    'user_city_trade_count'
]].fillna(0)

In [82]:
#item_occupation_count item_age_count item_gender_count
item_occupation_count = his.groupby(
    ['item_id', 'user_occupation_id'], as_index=False)['item_id'].agg({
        'item_occupation_count':
        'count'
    })
train = train.merge(
    item_occupation_count, on=['item_id', 'user_occupation_id'], how='left')

item_age_count = his.groupby(
    ['item_id', 'user_age_level'], as_index=False)['item_id'].agg({
        'item_age_count':
        'count'
    })
train = train.merge(
    item_age_count, on=['item_id', 'user_age_level'], how='left')

item_gender_count = his.groupby(
    ['item_id', 'user_gender_id'], as_index=False)['item_id'].agg({
        'item_gender_count':
        'count'
    })
train = train.merge(
    item_gender_count, on=['item_id', 'user_gender_id'], how='left')

#trade
item_occupation_trade_count = his_trade.groupby(
    ['item_id', 'user_occupation_id'], as_index=False)['item_id'].agg({
        'item_occupation_trade_count':
        'count'
    })
train = train.merge(
    item_occupation_trade_count,
    on=['item_id', 'user_occupation_id'],
    how='left')

item_age_trade_count = his_trade.groupby(
    ['item_id', 'user_age_level'], as_index=False)['item_id'].agg({
        'item_age_trade_count':
        'count'
    })
train = train.merge(
    item_age_trade_count, on=['item_id', 'user_age_level'], how='left')

item_gender_trade_count = his_trade.groupby(
    ['item_id', 'user_gender_id'], as_index=False)['item_id'].agg({
        'item_gender_trade_count':
        'count'
    })
train = train.merge(
    item_gender_trade_count, on=['item_id', 'user_gender_id'], how='left')

train[[
    'item_occupation_count', 'item_age_count', 'item_gender_count',
    'item_occupation_trade_count', 'item_age_trade_count',
    'item_gender_trade_count'
]] = train[[
    'item_occupation_count', 'item_age_count', 'item_gender_count',
    'item_occupation_trade_count', 'item_age_trade_count',
    'item_gender_trade_count'
]].fillna(0)

In [83]:
#shop_score = (star + review_num * review_positive) * service * delivery * description
train.shop_star_level = train.shop_star_level - min(train.shop_star_level)

train['shop_score'] = (
    train.shop_star_level +
    train.shop_review_num_level * train.shop_review_positive_rate
) * train.shop_score_service * train.shop_score_delivery * train.shop_score_description

In [84]:
train.context_page_id = train.context_page_id - min(train.context_page_id)

In [85]:
#item_score = (sales + collected + pv)
#item_score2 = (sales + collected + pv) / price
#item_score3 = ((sales + collected + pv) / price) / (page + 1)

train['item_score'] = (
    train.item_sales_level + train.item_collected_level * train.item_pv_level)
train['item_score2'] = (
    train.item_sales_level + train.item_collected_level * train.item_pv_level
) / train.item_price_level
train['item_score3'] = (
    (train.item_sales_level + train.item_collected_level * train.item_pv_level
     ) / train.item_price_level) / (train.context_page_id + 1)

In [86]:
def pred_split(x):
    pred = []
    tmp = x.split(';')
    for i in range(0, len(tmp)):
        pred.append(tmp[i].split(':'))
    return pred


def predict_category_split(x):
    pred = []
    for i in range(0, len(x)):
        pred.append(x[i][0])
    return pred


def predict_property_split(x):
    pred = []
    for i in range(0, len(x)):
        for j in range(1, len(x[i])):
            if (x[i][j] != '-1'):
                pred.append(x[i][j])
    return pred

In [87]:
train[
    'predict_category_property_split'] = train.predict_category_property.apply(
        lambda x: pred_split(x))

train['predict_category_split'] = train.predict_category_property_split.apply(
    lambda x: predict_category_split(x))

train['predict_property_split'] = train.predict_category_property_split.apply(
    lambda x: predict_property_split(x))

In [88]:
def item_pred_category_score(x):
    return len(
        list(
            set(x.item_category_split).intersection(
                set(x.predict_category_split))))


def item_pred_property_score(x):
    return len(
        list(
            set(x.item_property_split).intersection(
                set(x.predict_property_split))))

In [89]:
train['pred_category_split_count'] = train.predict_category_split.apply(
    lambda x: len(x))
train['pred_property_split_count'] = train.predict_property_split.apply(
    lambda x: len(x))

train['item_pred_category_score'] = train.apply(
    item_pred_category_score, axis=1)
train['item_pred_property_score'] = train.apply(
    item_pred_property_score, axis=1)

train['item_pred_category_score_item%'] = train.item_pred_category_score / (
    train.item_category_split_count + 1) * 10
train['item_pred_property_score_item%'] = train.item_pred_property_score / (
    train.item_property_split_count + 1) * 10

train['item_pred_category_score_pred%'] = train.item_pred_category_score / (
    train.pred_category_split_count + 1) * 10
train['item_pred_property_score_pred%'] = train.item_pred_property_score / (
    train.pred_property_split_count + 1) * 10

In [90]:
#item_hot user_hot shop_hot city_hot occupation_hot brand_hot
item_hot = his.groupby(
    ['item_id'], as_index=False)['item_id'].agg({
        'item_hot': 'count'
    })
train = train.merge(item_hot, on=['item_id'], how='left')

user_hot = his.groupby(
    ['user_id'], as_index=False)['user_id'].agg({
        'user_hot': 'count'
    })
train = train.merge(user_hot, on=['user_id'], how='left')

shop_hot = his.groupby(
    ['shop_id'], as_index=False)['shop_id'].agg({
        'shop_hot': 'count'
    })
train = train.merge(shop_hot, on=['shop_id'], how='left')

brand_hot = his.groupby(
    ['item_brand_id'], as_index=False)['item_brand_id'].agg({
        'brand_hot':
        'count'
    })
train = train.merge(brand_hot, on=['item_brand_id'], how='left')

occupation_hot = his.groupby(
    ['user_occupation_id'], as_index=False)['user_occupation_id'].agg({
        'occupation_hot':
        'count'
    })
train = train.merge(occupation_hot, on=['user_occupation_id'], how='left')

city_hot = his.groupby(
    ['item_city_id'], as_index=False)['item_city_id'].agg({
        'city_hot': 'count'
    })
train = train.merge(city_hot, on=['item_city_id'], how='left')

#trade
item_trade_hot = his.groupby(
    ['item_id'], as_index=False)['is_trade'].agg({
        'item_trade_hot': 'sum'
    })
train = train.merge(item_trade_hot, on=['item_id'], how='left')

user_trade_hot = his.groupby(
    ['user_id'], as_index=False)['is_trade'].agg({
        'user_trade_hot': 'sum'
    })
train = train.merge(user_trade_hot, on=['user_id'], how='left')

shop_trade_hot = his.groupby(
    ['shop_id'], as_index=False)['is_trade'].agg({
        'shop_trade_hot': 'sum'
    })
train = train.merge(shop_trade_hot, on=['shop_id'], how='left')

brand_trade_hot = his.groupby(
    ['item_brand_id'], as_index=False)['is_trade'].agg({
        'brand_trade_hot': 'sum'
    })
train = train.merge(brand_trade_hot, on=['item_brand_id'], how='left')

occupation_trade_hot = his.groupby(
    ['user_occupation_id'], as_index=False)['is_trade'].agg({
        'occupation_trade_hot':
        'sum'
    })
train = train.merge(
    occupation_trade_hot, on=['user_occupation_id'], how='left')

city_trade_hot = his.groupby(
    ['item_city_id'], as_index=False)['is_trade'].agg({
        'city_trade_hot': 'sum'
    })
train = train.merge(city_trade_hot, on=['item_city_id'], how='left')

train[[
    'item_hot', 'user_hot', 'shop_hot', 'brand_hot', 'occupation_hot',
    'city_hot', 'item_trade_hot', 'user_trade_hot', 'shop_trade_hot',
    'brand_trade_hot', 'occupation_trade_hot', 'city_trade_hot'
]] = train[[
    'item_hot', 'user_hot', 'shop_hot', 'brand_hot', 'occupation_hot',
    'city_hot', 'item_trade_hot', 'user_trade_hot', 'shop_trade_hot',
    'brand_trade_hot', 'occupation_trade_hot', 'city_trade_hot'
]].fillna(0)

In [91]:
#平均消费能力
user_sell_power = his.groupby(
    ['user_id'], as_index=False)['item_price_level'].agg({
        'user_sell_power':
        'sum'
    })
train = train.merge(user_sell_power, on=['user_id'], how='left')

train[['user_sell_power']] = train[['user_sell_power']].fillna(0)

train['user_sell_power_mean'] = train.user_sell_power / (train.user_hot + 1)
train['user_sell_power_mean_item_minus'] = abs(
    train.user_sell_power_mean - train.item_price_level)

#trade
user_sell_trade_power = his_trade.groupby(
    ['user_id'], as_index=False)['item_price_level'].agg({
        'user_sell_trade_power':
        'sum'
    })
train = train.merge(user_sell_trade_power, on=['user_id'], how='left')

train[['user_sell_trade_power']] = train[['user_sell_trade_power']].fillna(0)

train['user_sell_trade_power_mean'] = train.user_sell_trade_power / (
    train.user_trade_hot + 1)
train['user_sell_trade_power_mean_item_minus'] = abs(
    train.user_sell_trade_power_mean - train.item_price_level)

In [70]:
train = pd.read_csv('train_preprocessing52.csv')

In [92]:
train.shape
train.head()

(139406, 85)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,item_category_split,item_property_split,predict_category_property_split,item_category_split_count,item_property_split_count,time,day,hour,user_query_day,user_query_day_hour,user_shop_count,user_item_count,user_context_count,user_shop_trade_count,user_item_trade_count,user_context_trade_count,user_brand_count,user_city_count,user_brand_trade_count,user_city_trade_count,item_occupation_count,item_age_count,item_gender_count,item_occupation_trade_count,item_age_trade_count,item_gender_trade_count,shop_score,item_score,item_score2,item_score3,predict_category_split,predict_property_split,pred_category_split_count,pred_property_split_count,item_pred_category_score,item_pred_property_score,item_pred_category_score_item%,item_pred_property_score_item%,item_pred_category_score_pred%,item_pred_property_score_pred%,item_hot,user_hot,shop_hot,brand_hot,occupation_hot,city_hot,item_trade_hot,user_trade_hot,shop_trade_hot,brand_trade_hot,occupation_trade_hot,city_trade_hot,user_sell_power,user_sell_power_mean,user_sell_power_mean_item_minus,user_sell_trade_power,user_sell_trade_power_mean,user_sell_trade_power_mean_item_minus
0,1294180558417909525,3417228998968466891,7908382889764677758;5799347067982556520,2636395404473730413;4067341101015777832;101341...,1369755222868145421,5326000431362991708,7,1,4,8,4790424684324799775,0,1003,2002,3006,8843409125615638650,1537712904,0,"5799347067982556520:9172976955054793469,742282...",3011322251466986596,12,0.981125,10,0.974849,0.977525,0.966823,0,"[7908382889764677758, 5799347067982556520]","[2636395404473730413, 4067341101015777832, 101...","[[5799347067982556520, 9172976955054793469,742...",2,14,2018-09-23 22:28:24,23,22,2,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,20.060442,33,4.714286,4.714286,"[5799347067982556520, 7908382889764677758]","[9172976955054793469,7422828355050797095, 7422...",2,2,2,0,6.666667,0.0,6.666667,0.0,1.0,18.0,1.0,1.0,110154,1274,0.0,0.0,0.0,0.0,2306,35,111.0,5.842105,1.157895,0.0,0.0,7.0
1,4988669284857152533,932459418921071956,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;655689...,3101174666276603352,7322157373578955368,8,12,14,18,5297018676355586708,1,1004,2002,3005,5448626819385615379,1537703526,0,5755694407684602296:-1;7908382889764677758:-1;...,6244933171089048032,16,1.000000,15,0.963192,0.960966,0.983802,0,"[7908382889764677758, 5755694407684602296]","[5131280576272319091, 2636395404473730413, 655...","[[5755694407684602296, -1], [79083828897646777...",2,49,2018-09-23 19:52:06,23,19,3,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,82.0,79.0,84.0,3.0,3.0,3.0,28.228659,264,33.000000,33.000000,"[5755694407684602296, 7908382889764677758, 509...",[],4,0,2,0,6.666667,0.0,4.000000,0.0,292.0,0.0,375.0,645.0,110154,43204,7.0,0.0,8.0,17.0,2306,912,0.0,0.000000,8.000000,0.0,0.0,8.0
2,5378282568284173939,932459418921071956,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;655689...,3101174666276603352,7322157373578955368,8,12,14,18,2128349640379796295,0,1005,2005,3002,6454805461923703549,1537699469,0,2948160913626618607:4083958765544089731;264834...,6244933171089048032,16,1.000000,15,0.963192,0.960966,0.983802,0,"[7908382889764677758, 5755694407684602296]","[5131280576272319091, 2636395404473730413, 655...","[[2948160913626618607, 4083958765544089731], [...",2,49,2018-09-23 18:44:29,23,18,4,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,198.0,48.0,193.0,4.0,1.0,4.0,28.228659,264,33.000000,33.000000,"[2948160913626618607, 2648343924459474923, 694...","[4083958765544089731, 3455328527623636528,4083...",5,4,1,1,3.333333,0.2,1.666667,2.0,292.0,0.0,375.0,645.0,223895,43204,7.0,0.0,8.0,17.0,4232,912,0.0,0.000000,8.000000,0.0,0.0,8.0
3,5217602552450998299,932459418921071956,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;655689...,3101174666276603352,7322157373578955368,8,12,14,18,3940166436460995988,0,1003,2005,3006,8584587379907053424,1537697730,0,5755694407684602296:-1;509660095530134768:-1;7...,6244933171089048032,16,1.000000,15,0.963192,0.960966,0.983802,0,"[7908382889764677758, 5755694407684602296]","[5131280576272319091, 2636395404473730413, 655...","[[5755694407684602296, -1], [50966009553013476...",2,49,2018-09-23 18:15:30,23,18,33,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,198.0,95.0,193.0,4.0,2.0,4.0,28.228659,264,33.000000,33.000000,"[5755694407684602296, 509660095530134768, 7908...",[],3,0,2,0,6.666667,0.0,5.000000,0.0,292.0,0.0,375.0,645.0,223895,43204,7.0,0.0,8.0,17.0,4232,912,0.0,0.000000,8.000000,0.0,0.0,8.0
4,790758633868253958,932459418921071956,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;655689...,3101174666276603352,7322157373578955368,8,12,14,18,1148196570078966163,1,1002,2005,3002,5550225482856371838,1537712724,0,5755694407684602296:5131280576272319091;509660...,6244933171089048032,16,1.000000,15,0.963192,0.960966,0.983802,0,"[7908382889764677758, 5755694407684602296]","[5131280576272319091, 2636395404473730413, 655...","[[5755694407684602296, 5131280576272319091], [...",2,49,2018-09-23 22:25:24,23,22,3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,198.0,24.0,84.0,4.0,1.0,3.0,28.228659,264,33.000000,33.000000,"[5755694407684602296, 509660095530134768, 7908...","[5131280576272319091, 5131280576272319091, 513...",4,3,2,1,6.666667,0.2,4.000000,2.5,292.0,0.0,375.0,645.0,223895,43204,7.0,0.0,8.0,17.0,4232,912,0.0,0.000000,8.000000,0.0,0.0,8.0

In [93]:
train.to_csv('train_preprocessing52.csv', index=False)
his.to_csv('his_preprocessing52.csv', index=False)