In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import time
from tqdm import tqdm

%matplotlib inline

#每次可以输出多个变量
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from pylab import rcParams
rcParams['figure.figsize'] = 14, 6

import warnings
warnings.filterwarnings("ignore")

#中文字体
import matplotlib
matplotlib.use('qt4agg')
#指定默认字体
matplotlib.rcParams['font.sans-serif'] = ['SimHei']
matplotlib.rcParams['font.family'] = 'sans-serif'
#解决负号'-'显示为方块的问题
matplotlib.rcParams['axes.unicode_minus'] = False

In [2]:
df = pd.read_csv('df.txt', sep=' ')
test = pd.read_csv('test.txt', sep=' ')
df = df.drop_duplicates(['instance_id'])

df.shape
df.head()
test.shape
test.head()

(478087, 27)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade
0,108641074714126964,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,4505772604969228686,1,1003,2005,3003,282924576738839389,1537236544,4006,5799347067982556520:-1;509660095530134768:-1;5...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
1,5754713551599725161,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2692638157208937547,0,1002,2005,3006,4007979028023783431,1537243232,4001,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
2,842679481291040981,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,5247924392014515924,0,1003,2005,3004,4884875192608989870,1537211052,4001,5799347067982556520:5131280576272319091;725801...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
3,937088850059189027,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2681414445369714628,1,1004,2005,3006,840119421106178602,1537222670,4016,509660095530134768:-1;5799347067982556520:-1;7...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
4,7975697065017708072,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2729475788342039013,0,1002,2005,3001,1736769971710354684,1537271320,4001,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0

(18371, 26)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description
0,2475218615076601065,2275895163219263378,7908382889764677758;8277336076276184272,2636395404473730413;7515802706813700848;302719...,7838285046767229711,7534238860363577544,7,6,8,14,4379490381248358680,0,1002,2005,3001,2858926263178884522,1537885700,4005,8277336076276184272:-1;5799347067982556520:-1;...,5275548996133547595,13,0.985244,5011,0.964023,0.966550,0.955378
1,398316874173557226,7096238490711246967,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;734498...,8126195666233054089,3948283326616421003,6,9,8,16,2629129219935839101,1,1004,2002,3006,4014843148303402290,1537862843,4001,"5755694407684602296:216555019471416386,2636395...",329470548383752413,14,0.989068,5012,0.963794,0.964225,0.959134
2,6586402638209028583,7096238490711246967,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;734498...,8126195666233054089,3948283326616421003,6,9,8,16,1092007111346257147,0,1004,2002,3004,8141706531104182980,1537858222,4011,5755694407684602296:2636395404473730413;871073...,329470548383752413,14,0.989068,5012,0.963794,0.964225,0.959134
3,1040996105851528465,7096238490711246967,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;734498...,8126195666233054089,3948283326616421003,6,9,8,16,5353289677517820939,1,1003,2002,3007,5878932623083097102,1537860915,4001,8710739180200009128:-1;5755694407684602296:263...,329470548383752413,14,0.989068,5012,0.963794,0.964225,0.959134
4,6316278569655873454,7096238490711246967,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;734498...,8126195666233054089,3948283326616421003,6,9,8,16,1098833840660870025,0,1002,2003,3002,7218739953079190510,1537859074,4001,5755694407684602296:5131280576272319091;871073...,329470548383752413,14,0.989068,5012,0.963794,0.964225,0.959134

In [3]:
test['is_trade'] = -1

df = pd.concat([df, test])

In [4]:
df['item_category_split'] = df.item_category_list.apply(lambda x: x.split(';'))
df['item_property_split'] = df.item_property_list.apply(lambda x: x.split(';'))
df['predict_category_property_split'] = df.predict_category_property.apply(
    lambda x: x.split(';'))

df['item_category_split_count'] = df.item_category_split.apply(
    lambda x: len(x))
df['item_property_split_count'] = df.item_property_split.apply(
    lambda x: len(x))

In [5]:
#time
def timestamp_datetime(value):
    format = '%Y-%m-%d %H:%M:%S'
    value = time.localtime(value)
    dt = time.strftime(format, value)
    return dt


def convert_data(data):
    data['time'] = data.context_timestamp.apply(timestamp_datetime)
    data['day'] = data.time.apply(lambda x: int(x[8:10]))
    data['hour'] = data.time.apply(lambda x: int(x[11:13]))
    data['minute'] = data.time.apply(lambda x: int(x[14:15])) * 10
    user_query_day = data.groupby(
        ['user_id',
         'day']).size().reset_index().rename(columns={
             0: 'user_query_day'
         })
    data = pd.merge(data, user_query_day, 'left', on=['user_id', 'day'])
    user_query_day_hour = data.groupby(
        ['user_id', 'day',
         'hour']).size().reset_index().rename(columns={
             0: 'user_query_day_hour'
         })
    data = pd.merge(
        data, user_query_day_hour, 'left', on=['user_id', 'day', 'hour'])
    user_query_minute = data.groupby(
        ['user_id', 'day', 'hour',
         'minute']).size().reset_index().rename(columns={
             0: 'user_query_minute'
         })
    data = pd.merge(
        data,
        user_query_minute,
        'left',
        on=['user_id', 'day', 'hour', 'minute'])
    return data


df = convert_data(df)

In [6]:
#18、19、20天做历史数据，21、22、23、24天做训练和验证数据
his = df[(df.day != 21) & (df.day != 22) & (df.day != 23) & (df.day != 24) &
         (df.is_trade != -1)]
train = df[(df.day == 21) | (df.day == 22) | (df.day == 23) | (df.day == 24)
           | (df.is_trade == -1)]

del df

his.shape
train.shape
his_trade = his[his.is_trade == 1]

#(357103, 37)
#(121035, 37) 无test，5：2

(217564, 39)

(278894, 39)

In [7]:
#user_shop_count user_item_count user_context_count
user_shop_count = his.groupby(
    ['user_id', 'shop_id'], as_index=False)['user_id'].agg({
        'user_shop_count':
        'count'
    })
train = train.merge(user_shop_count, on=['user_id', 'shop_id'], how='left')

user_item_count = his.groupby(
    ['user_id', 'item_id'], as_index=False)['user_id'].agg({
        'user_item_count':
        'count'
    })
train = train.merge(user_item_count, on=['user_id', 'item_id'], how='left')

user_context_count = his.groupby(
    ['user_id', 'context_id'], as_index=False)['user_id'].agg({
        'user_context_count':
        'count'
    })
train = train.merge(
    user_context_count, on=['user_id', 'context_id'], how='left')

#trade
user_shop_trade_count = his_trade.groupby(
    ['user_id', 'shop_id'], as_index=False)['user_id'].agg({
        'user_shop_trade_count':
        'count'
    })
train = train.merge(
    user_shop_trade_count, on=['user_id', 'shop_id'], how='left')

user_item_trade_count = his_trade.groupby(
    ['user_id', 'item_id'], as_index=False)['user_id'].agg({
        'user_item_trade_count':
        'count'
    })
train = train.merge(
    user_item_trade_count, on=['user_id', 'item_id'], how='left')

user_context_trade_count = his_trade.groupby(
    ['user_id', 'context_id'], as_index=False)['user_id'].agg({
        'user_context_trade_count':
        'count'
    })
train = train.merge(
    user_context_trade_count, on=['user_id', 'context_id'], how='left')

train[[
    'user_shop_count', 'user_item_count', 'user_context_count',
    'user_shop_trade_count', 'user_item_trade_count',
    'user_context_trade_count'
]] = train[[
    'user_shop_count', 'user_item_count', 'user_context_count',
    'user_shop_trade_count', 'user_item_trade_count',
    'user_context_trade_count'
]].fillna(0)

In [8]:
#user_brand_count user_city_count
user_brand_count = his.groupby(
    ['user_id', 'item_brand_id'], as_index=False)['user_id'].agg({
        'user_brand_count':
        'count'
    })
train = train.merge(
    user_brand_count, on=['user_id', 'item_brand_id'], how='left')

user_city_count = his.groupby(
    ['user_id', 'item_city_id'], as_index=False)['user_id'].agg({
        'user_city_count':
        'count'
    })
train = train.merge(
    user_city_count, on=['user_id', 'item_city_id'], how='left')

#trade
user_brand_trade_count = his_trade.groupby(
    ['user_id', 'item_brand_id'], as_index=False)['user_id'].agg({
        'user_brand_trade_count':
        'count'
    })
train = train.merge(
    user_brand_trade_count, on=['user_id', 'item_brand_id'], how='left')

user_city_trade_count = his_trade.groupby(
    ['user_id', 'item_city_id'], as_index=False)['user_id'].agg({
        'user_city_trade_count':
        'count'
    })
train = train.merge(
    user_city_trade_count, on=['user_id', 'item_city_id'], how='left')

train[[
    'user_brand_count', 'user_city_count', 'user_brand_trade_count',
    'user_city_trade_count'
]] = train[[
    'user_brand_count', 'user_city_count', 'user_brand_trade_count',
    'user_city_trade_count'
]].fillna(0)

In [9]:
#item_occupation_count item_age_count item_gender_count
item_occupation_count = his.groupby(
    ['item_id', 'user_occupation_id'], as_index=False)['item_id'].agg({
        'item_occupation_count':
        'count'
    })
train = train.merge(
    item_occupation_count, on=['item_id', 'user_occupation_id'], how='left')

item_age_count = his.groupby(
    ['item_id', 'user_age_level'], as_index=False)['item_id'].agg({
        'item_age_count':
        'count'
    })
train = train.merge(
    item_age_count, on=['item_id', 'user_age_level'], how='left')

item_gender_count = his.groupby(
    ['item_id', 'user_gender_id'], as_index=False)['item_id'].agg({
        'item_gender_count':
        'count'
    })
train = train.merge(
    item_gender_count, on=['item_id', 'user_gender_id'], how='left')

#trade
item_occupation_trade_count = his_trade.groupby(
    ['item_id', 'user_occupation_id'], as_index=False)['item_id'].agg({
        'item_occupation_trade_count':
        'count'
    })
train = train.merge(
    item_occupation_trade_count,
    on=['item_id', 'user_occupation_id'],
    how='left')

item_age_trade_count = his_trade.groupby(
    ['item_id', 'user_age_level'], as_index=False)['item_id'].agg({
        'item_age_trade_count':
        'count'
    })
train = train.merge(
    item_age_trade_count, on=['item_id', 'user_age_level'], how='left')

item_gender_trade_count = his_trade.groupby(
    ['item_id', 'user_gender_id'], as_index=False)['item_id'].agg({
        'item_gender_trade_count':
        'count'
    })
train = train.merge(
    item_gender_trade_count, on=['item_id', 'user_gender_id'], how='left')

train[[
    'item_occupation_count', 'item_age_count', 'item_gender_count',
    'item_occupation_trade_count', 'item_age_trade_count',
    'item_gender_trade_count'
]] = train[[
    'item_occupation_count', 'item_age_count', 'item_gender_count',
    'item_occupation_trade_count', 'item_age_trade_count',
    'item_gender_trade_count'
]].fillna(0)

In [10]:
#shop_score = (star + review_num * review_positive) * service * delivery * description
train.shop_star_level = train.shop_star_level - min(train.shop_star_level)

train['shop_score'] = (
    train.shop_star_level +
    train.shop_review_num_level * train.shop_review_positive_rate
) * train.shop_score_service * train.shop_score_delivery * train.shop_score_description

In [11]:
train.context_page_id = train.context_page_id - min(train.context_page_id)

In [12]:
#item_score = (sales + collected + pv)
#item_score2 = (sales + collected + pv) / price
#item_score3 = ((sales + collected + pv) / price) / (page + 1)

train['item_score'] = (
    train.item_sales_level + train.item_collected_level * train.item_pv_level)
train['item_score2'] = (
    train.item_sales_level + train.item_collected_level * train.item_pv_level
) / train.item_price_level
train['item_score3'] = (
    (train.item_sales_level + train.item_collected_level * train.item_pv_level
     ) / train.item_price_level) / (train.context_page_id + 1)

In [13]:
def pred_split(x):
    pred = []
    tmp = x.split(';')
    for i in range(0, len(tmp)):
        pred.append(tmp[i].split(':'))
    return pred


def predict_category_split(x):
    pred = []
    for i in range(0, len(x)):
        pred.append(x[i][0])
    return pred


def predict_property_split(x):
    pred = []
    for i in range(0, len(x)):
        for j in range(1, len(x[i])):
            if (x[i][j] != '-1'):
                pred.append(x[i][j])
    return pred

In [14]:
train[
    'predict_category_property_split'] = train.predict_category_property.apply(
        lambda x: pred_split(x))

train['predict_category_split'] = train.predict_category_property_split.apply(
    lambda x: predict_category_split(x))

train['predict_property_split'] = train.predict_category_property_split.apply(
    lambda x: predict_property_split(x))

In [15]:
def item_pred_category_score(x):
    return len(
        list(
            set(x.item_category_split).intersection(
                set(x.predict_category_split))))


def item_pred_property_score(x):
    return len(
        list(
            set(x.item_property_split).intersection(
                set(x.predict_property_split))))

In [16]:
train['pred_category_split_count'] = train.predict_category_split.apply(
    lambda x: len(x))
train['pred_property_split_count'] = train.predict_property_split.apply(
    lambda x: len(x))

train['item_pred_category_score'] = train.apply(
    item_pred_category_score, axis=1)
train['item_pred_property_score'] = train.apply(
    item_pred_property_score, axis=1)

train['item_pred_category_score_item%'] = train.item_pred_category_score / (
    train.item_category_split_count + 1) * 10
train['item_pred_property_score_item%'] = train.item_pred_property_score / (
    train.item_property_split_count + 1) * 10

train['item_pred_category_score_pred%'] = train.item_pred_category_score / (
    train.pred_category_split_count + 1) * 10
train['item_pred_property_score_pred%'] = train.item_pred_property_score / (
    train.pred_property_split_count + 1) * 10

In [17]:
#item_hot user_hot shop_hot city_hot occupation_hot brand_hot
item_hot = his.groupby(
    ['item_id'], as_index=False)['item_id'].agg({
        'item_hot': 'count'
    })
train = train.merge(item_hot, on=['item_id'], how='left')

user_hot = his.groupby(
    ['user_id'], as_index=False)['user_id'].agg({
        'user_hot': 'count'
    })
train = train.merge(user_hot, on=['user_id'], how='left')

shop_hot = his.groupby(
    ['shop_id'], as_index=False)['shop_id'].agg({
        'shop_hot': 'count'
    })
train = train.merge(shop_hot, on=['shop_id'], how='left')

brand_hot = his.groupby(
    ['item_brand_id'], as_index=False)['item_brand_id'].agg({
        'brand_hot':
        'count'
    })
train = train.merge(brand_hot, on=['item_brand_id'], how='left')

occupation_hot = his.groupby(
    ['user_occupation_id'], as_index=False)['user_occupation_id'].agg({
        'occupation_hot':
        'count'
    })
train = train.merge(occupation_hot, on=['user_occupation_id'], how='left')

city_hot = his.groupby(
    ['item_city_id'], as_index=False)['item_city_id'].agg({
        'city_hot': 'count'
    })
train = train.merge(city_hot, on=['item_city_id'], how='left')

#trade
item_trade_hot = his.groupby(
    ['item_id'], as_index=False)['is_trade'].agg({
        'item_trade_hot': 'sum'
    })
train = train.merge(item_trade_hot, on=['item_id'], how='left')

user_trade_hot = his.groupby(
    ['user_id'], as_index=False)['is_trade'].agg({
        'user_trade_hot': 'sum'
    })
train = train.merge(user_trade_hot, on=['user_id'], how='left')

shop_trade_hot = his.groupby(
    ['shop_id'], as_index=False)['is_trade'].agg({
        'shop_trade_hot': 'sum'
    })
train = train.merge(shop_trade_hot, on=['shop_id'], how='left')

brand_trade_hot = his.groupby(
    ['item_brand_id'], as_index=False)['is_trade'].agg({
        'brand_trade_hot': 'sum'
    })
train = train.merge(brand_trade_hot, on=['item_brand_id'], how='left')

occupation_trade_hot = his.groupby(
    ['user_occupation_id'], as_index=False)['is_trade'].agg({
        'occupation_trade_hot':
        'sum'
    })
train = train.merge(
    occupation_trade_hot, on=['user_occupation_id'], how='left')

city_trade_hot = his.groupby(
    ['item_city_id'], as_index=False)['is_trade'].agg({
        'city_trade_hot': 'sum'
    })
train = train.merge(city_trade_hot, on=['item_city_id'], how='left')

train[[
    'item_hot', 'user_hot', 'shop_hot', 'brand_hot', 'occupation_hot',
    'city_hot', 'item_trade_hot', 'user_trade_hot', 'shop_trade_hot',
    'brand_trade_hot', 'occupation_trade_hot', 'city_trade_hot'
]] = train[[
    'item_hot', 'user_hot', 'shop_hot', 'brand_hot', 'occupation_hot',
    'city_hot', 'item_trade_hot', 'user_trade_hot', 'shop_trade_hot',
    'brand_trade_hot', 'occupation_trade_hot', 'city_trade_hot'
]].fillna(0)

In [18]:
#平均消费能力
user_sell_power = his.groupby(
    ['user_id'], as_index=False)['item_price_level'].agg({
        'user_sell_power':
        'sum'
    })
train = train.merge(user_sell_power, on=['user_id'], how='left')

train[['user_sell_power']] = train[['user_sell_power']].fillna(0)

train['user_sell_power_mean'] = train.user_sell_power / (train.user_hot + 1)
train['user_sell_power_mean_item_minus'] = abs(
    train.user_sell_power_mean - train.item_price_level)

#trade
user_sell_trade_power = his_trade.groupby(
    ['user_id'], as_index=False)['item_price_level'].agg({
        'user_sell_trade_power':
        'sum'
    })
train = train.merge(user_sell_trade_power, on=['user_id'], how='left')

train[['user_sell_trade_power']] = train[['user_sell_trade_power']].fillna(0)

train['user_sell_trade_power_mean'] = train.user_sell_trade_power / (
    train.user_trade_hot + 1)
train['user_sell_trade_power_mean_item_minus'] = abs(
    train.user_sell_trade_power_mean - train.item_price_level)

In [19]:
#用户一个时间段内搜索
train['yesterday'] = train.day - 1
train['yesterhour'] = train.hour.apply(lambda x: x - 1 if x != 0 else 23)

user_day_query = train.groupby(
    ['day', 'user_id'], as_index=False)['user_id'].agg({
        'user_day_query':
        'count'
    })
train = train.merge(user_day_query, on=['day', 'user_id'], how='left')
user_day_query.columns = ['day2', 'user_id', 'user_yesterday_query']
train = train.merge(
    user_day_query,
    left_on=['yesterday', 'user_id'],
    right_on=['day2', 'user_id'],
    how='left')

user_hour_query = train.groupby(
    ['day', 'hour', 'user_id'], as_index=False)['user_id'].agg({
        'user_hour_query':
        'count'
    })
train = train.merge(user_hour_query, on=['day', 'hour', 'user_id'], how='left')
user_hour_query.columns = ['day3', 'hour3', 'user_id', 'user_yesterhour_query']
train = train.merge(
    user_hour_query,
    left_on=['day', 'yesterhour', 'user_id'],
    right_on=['day3', 'hour3', 'user_id'],
    how='left')

user_minute_query = train.groupby(
    ['day', 'hour', 'minute', 'user_id'], as_index=False)['user_id'].agg({
        'user_minute_query':
        'count'
    })
train = train.merge(
    user_minute_query, on=['day', 'hour', 'minute', 'user_id'], how='left')

train = train.drop(['day2', 'day3', 'hour3'], axis=1)
train[[
    'user_day_query', 'user_hour_query', 'user_yesterday_query',
    'user_yesterhour_query', 'user_minute_query'
]] = train[[
    'user_day_query', 'user_hour_query', 'user_yesterday_query',
    'user_yesterhour_query', 'user_minute_query'
]].fillna(0)

In [20]:
#item一个时间段内被搜索、user_item组合一个时间段内被搜索
item_day_query = train.groupby(
    ['day', 'item_id'], as_index=False)['item_id'].agg({
        'item_day_query':
        'count'
    })
train = train.merge(item_day_query, on=['day', 'item_id'], how='left')

item_hour_query = train.groupby(
    ['day', 'hour', 'item_id'], as_index=False)['item_id'].agg({
        'item_hour_query':
        'count'
    })
train = train.merge(item_hour_query, on=['day', 'hour', 'item_id'], how='left')

item_minute_query = train.groupby(
    ['day', 'hour', 'minute', 'item_id'], as_index=False)['item_id'].agg({
        'item_minute_query':
        'count'
    })
train = train.merge(
    item_minute_query, on=['day', 'hour', 'minute', 'item_id'], how='left')

user_item_day_query = train.groupby(
    ['day', 'item_id', 'user_id'], as_index=False)['user_id'].agg({
        'user_item_day_query':
        'count'
    })
train = train.merge(
    user_item_day_query, on=['day', 'item_id', 'user_id'], how='left')

user_item_hour_query = train.groupby(
    ['day', 'hour', 'item_id', 'user_id'], as_index=False)['user_id'].agg({
        'user_item_hour_query':
        'count'
    })
train = train.merge(
    user_item_hour_query, on=['day', 'hour', 'item_id', 'user_id'], how='left')

user_item_minute_query = train.groupby(
    ['day', 'hour', 'minute', 'item_id', 'user_id'],
    as_index=False)['user_id'].agg({
        'user_item_minute_query': 'count'
    })
train = train.merge(
    user_item_minute_query,
    on=['day', 'hour', 'minute', 'item_id', 'user_id'],
    how='left')

train[[
    'item_day_query', 'item_hour_query', 'item_minute_query',
    'user_item_day_query', 'user_item_hour_query', 'user_item_minute_query'
]] = train[[
    'item_day_query', 'item_hour_query', 'item_minute_query',
    'user_item_day_query', 'user_item_hour_query', 'user_item_minute_query'
]].fillna(0)

In [21]:
#小时变为半小时划分时间段
train.minute = train.minute + 5
train['min_time'] = train.hour * 2 + round(train.minute / 60)

In [22]:
#历史中有没有出现
his_train_user = set(list(his.user_id)) & set(list(train.user_id))
his_train_item = set(list(his.item_id)) & set(list(train.item_id))
his_train_brand = set(list(his.item_brand_id)) & set(list(train.item_brand_id))
his_train_user_trade = set(list(his_trade.user_id)) & set(list(train.user_id))
his_train_item_trade = set(list(his_trade.item_id)) & set(list(train.item_id))
his_train_brand_trade = set(list(his_trade.item_brand_id)) & set(
    list(train.item_brand_id))

train['user_is_his'] = train.user_id.apply(
    lambda x: 0 if x in his_train_user else 1)
train['item_is_his'] = train.item_id.apply(
    lambda x: 0 if x in his_train_item else 1)
train['brand_is_his'] = train.item_brand_id.apply(
    lambda x: 0 if x in his_train_user_trade else 1)
train['user_is_trade_his'] = train.user_id.apply(
    lambda x: 0 if x in his_train_user_trade else 1)
train['item_is_trade_his'] = train.item_id.apply(
    lambda x: 0 if x in his_train_item_trade else 1)
train['brand_is_trade_his'] = train.item_brand_id.apply(
    lambda x: 0 if x in his_train_brand_trade else 1)

In [23]:
#user某时间段第几次点击
from collections import defaultdict, Counter
import ast

temp = defaultdict(lambda: -1)


def user_count(x):
    temp[x] += 1
    return temp[x]


temp2 = defaultdict(lambda: defaultdict(lambda: -1))


def user_day_count(x):
    temp2[x.day][x.user_id] += 1
    return temp2[x.day][x.user_id]


temp3 = defaultdict(lambda: defaultdict(lambda: defaultdict(lambda: -1)))


def user_hour_count(x):
    temp3[x.day][x.hour][x.user_id] += 1
    return temp3[x.day][x.hour][x.user_id]


temp4 = defaultdict(
    lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(lambda: -1))))


def user_minute_count(x):
    temp4[x.day][x.hour][x.minute][x.user_id] += 1
    return temp4[x.day][x.hour][x.minute][x.user_id]


train['user_count'] = train.user_id.apply(user_count)
train['user_day_count'] = train.apply(user_day_count, axis=1)
train['user_hour_count'] = train.apply(user_hour_count, axis=1)
train['user_minute_count'] = train.apply(user_minute_count, axis=1)

In [24]:
#user购买率(occupation/item/brand/city)
item_hot['item_trade_percent'] = (
    item_trade_hot.item_trade_hot / item_hot.item_hot) * 100
item_hot.columns = ['item_id2', 'item_hot', 'item_trade_percent']
train = train.merge(
    item_hot[['item_id2', 'item_trade_percent']],
    left_on=['item_id'],
    right_on=['item_id2'],
    how='left')
train = train.drop(['item_id2'], axis=1)

# brand_hot = brand_hot[brand_hot.item_brand_id != -1]
brand_hot['brand_trade_percent'] = (
    brand_trade_hot.brand_trade_hot / brand_hot.brand_hot) * 100
brand_hot.columns = ['item_brand_id2', 'brand_hot', 'brand_trade_percent']
train = train.merge(
    brand_hot[['item_brand_id2', 'brand_trade_percent']],
    left_on=['item_brand_id'],
    right_on=['item_brand_id2'],
    how='left')
train = train.drop(['item_brand_id2'], axis=1)

user_hot['user_trade_percent'] = (
    user_trade_hot.user_trade_hot / user_hot.user_hot) * 100
user_hot.columns = ['user_id2', 'user_hot', 'user_trade_percent']
train = train.merge(
    user_hot[['user_id2', 'user_trade_percent']],
    left_on=['user_id'],
    right_on=['user_id2'],
    how='left')
train = train.drop(['user_id2'], axis=1)

# occupation_hot = occupation_hot[occupation_hot.user_occupation_id != -1]
occupation_hot['occupation_trade_percent'] = (
    occupation_trade_hot.occupation_trade_hot / occupation_hot.occupation_hot
) * 100
occupation_hot.columns = [
    'user_occupation_id2', 'occupation_hot', 'occupation_trade_percent'
]
train = train.merge(
    occupation_hot[['user_occupation_id2', 'occupation_trade_percent']],
    left_on=['user_occupation_id'],
    right_on=['user_occupation_id2'],
    how='left')
train = train.drop(['user_occupation_id2'], axis=1)

train[[
    'item_trade_percent', 'brand_trade_percent', 'user_trade_percent',
    'occupation_trade_percent'
]] = train[[
    'item_trade_percent', 'brand_trade_percent', 'user_trade_percent',
    'occupation_trade_percent'
]].fillna(0)

In [25]:
#is_home
train['is_home'] = train.user_gender_id.apply(lambda x: 1 if x == 2 else 0)

In [26]:
#统计特征shop_item_count、brand_item_count、city_shop_count、city_brand_count、city_item_count
shop_item_count = train.groupby(
    ['shop_id'], as_index=False)['item_id'].agg({
        'shop_item_count': 'unique'
    })
shop_item_count['shop_item_count'] = shop_item_count.shop_item_count.apply(len)
train = train.merge(shop_item_count, on=['shop_id'], how='left')

brand_item_count = train.groupby(
    ['item_brand_id'], as_index=False)['item_id'].agg({
        'brand_item_count':
        'unique'
    })
brand_item_count['brand_item_count'] = brand_item_count.brand_item_count.apply(
    len)
train = train.merge(brand_item_count, on=['item_brand_id'], how='left')

city_brand_count = train.groupby(
    ['item_city_id'], as_index=False)['item_brand_id'].agg({
        'city_brand_count':
        'unique'
    })
city_brand_count['city_brand_count'] = city_brand_count.city_brand_count.apply(
    len)
train = train.merge(city_brand_count, on=['item_city_id'], how='left')

city_item_count = train.groupby(
    ['item_city_id'], as_index=False)['item_id'].agg({
        'city_item_count':
        'unique'
    })
city_item_count['city_item_count'] = city_item_count.city_item_count.apply(len)
train = train.merge(city_item_count, on=['item_city_id'], how='left')

#his
shop_item_count = his.groupby(
    ['shop_id'], as_index=False)['item_id'].agg({
        'shop_item_count_his': 'unique'
    })
shop_item_count[
    'shop_item_count_his'] = shop_item_count.shop_item_count_his.apply(len)
train = train.merge(shop_item_count, on=['shop_id'], how='left')

brand_item_count = his.groupby(
    ['item_brand_id'], as_index=False)['item_id'].agg({
        'brand_item_count_his':
        'unique'
    })
brand_item_count[
    'brand_item_count_his'] = brand_item_count.brand_item_count_his.apply(len)
train = train.merge(brand_item_count, on=['item_brand_id'], how='left')

city_brand_count = his.groupby(
    ['item_city_id'], as_index=False)['item_brand_id'].agg({
        'city_brand_count_his':
        'unique'
    })
city_brand_count[
    'city_brand_count_his'] = city_brand_count.city_brand_count_his.apply(len)
train = train.merge(city_brand_count, on=['item_city_id'], how='left')

city_item_count = his.groupby(
    ['item_city_id'], as_index=False)['item_id'].agg({
        'city_item_count_his':
        'unique'
    })
city_item_count[
    'city_item_count_his'] = city_item_count.city_item_count_his.apply(len)
train = train.merge(city_item_count, on=['item_city_id'], how='left')

train[[
    'shop_item_count', 'brand_item_count', 'city_brand_count',
    'city_item_count', 'shop_item_count_his', 'brand_item_count_his',
    'city_brand_count_his', 'city_item_count_his'
]] = train[[
    'shop_item_count', 'brand_item_count', 'city_brand_count',
    'city_item_count', 'shop_item_count_his', 'brand_item_count_his',
    'city_brand_count_his', 'city_item_count_his'
]].fillna(0)

In [27]:
#id转vector:item_id、user_id、shop_id、item_brand_id、item_city_id
temp_list = list(set(list(train.item_id)))
train['item_id_idx'] = train.item_id.apply(lambda x: temp_list.index(x))
temp_list = list(set(list(train.user_id)))
train['user_id_idx'] = train.user_id.apply(lambda x: temp_list.index(x))
temp_list = list(set(list(train.shop_id)))
train['shop_id_idx'] = train.shop_id.apply(lambda x: temp_list.index(x))
temp_list = list(set(list(train.item_brand_id)))
train['item_brand_id_idx'] = train.item_brand_id.apply(
    lambda x: temp_list.index(x))
temp_list = list(set(list(train.item_city_id)))
train['item_city_id_idx'] = train.item_city_id.apply(
    lambda x: temp_list.index(x))

In [28]:
#user上下次浏览时间、时间差
from datetime import datetime, timedelta

train['user_next_count'] = train.user_count + 1
train['user_last_count'] = train.user_count - 1
temp_time = train[['user_id', 'user_count', 'time']]

temp_time.columns = ['user_id', 'user_next_count', 'user_next_time']
train = train.merge(temp_time, on=['user_id', 'user_next_count'], how='left')
temp_time.columns = ['user_id', 'user_last_count', 'user_last_time']
train = train.merge(temp_time, on=['user_id', 'user_last_count'], how='left')


def next_time_sub(x):
    if type(x.user_next_time) == float:
        return 999999
    else:
        return (datetime.strptime(x.user_next_time, '%Y-%m-%d  %H:%M:%S') -
                datetime.strptime(x.time, '%Y-%m-%d  %H:%M:%S')).seconds


def last_time_sub(x):
    if type(x.user_last_time) == float:
        return 999999
    else:
        return (
            datetime.strptime(x.time, '%Y-%m-%d  %H:%M:%S') -
            datetime.strptime(x.user_last_time, '%Y-%m-%d  %H:%M:%S')).seconds


train['next_time_sub'] = train.apply(next_time_sub, axis=1)
train['last_time_sub'] = train.apply(last_time_sub, axis=1)

In [4]:
from collections import defaultdict, Counter
import ast

df_time = pd.concat([
    train[['user_id', 'item_id', 'shop_id', 'time']],
    his[['user_id', 'item_id', 'shop_id', 'time']]
])

temp = defaultdict(lambda: -1)


def user_count(x):
    temp[x] += 1
    return temp[x]


temp2 = defaultdict(lambda: defaultdict(lambda: -1))


def user_item_count(x):
    temp2[x.user_id][x.item_id] += 1
    return temp2[x.user_id][x.item_id]


temp3 = defaultdict(lambda: defaultdict(lambda: -1))


def user_shop_count(x):
    temp3[x.user_id][x.shop_id] += 1
    return temp3[x.user_id][x.shop_id]


df_time['user_count'] = df_time.user_id.apply(user_count)
df_time['user_item_num'] = df_time.apply(user_item_count, axis=1)
df_time['user_shop_num'] = df_time.apply(user_shop_count, axis=1)

df_time.shape
df_time.head()

(496458, 7)

,user_id,item_id,shop_id,time,user_count,user_item_num,user_shop_num
0,8711326521450559534,3412720377098676069,6765930309048922341,2018-09-21 01:52:19,0,0,0
1,8064892827740019258,285660928590172217,4885989684392199728,2018-09-21 21:37:56,0,0,0
2,1633738185485564030,5202355029344881809,4885989684392199728,2018-09-21 22:14:29,0,0,0
3,7983400645978077748,285660928590172217,4885989684392199728,2018-09-21 13:53:54,0,0,0
4,4831066601005367480,5202355029344881809,4885989684392199728,2018-09-21 09:51:55,0,0,0

In [13]:
#user_item、user_shop上下次浏览时间、时间差
from collections import defaultdict, Counter
import ast

temp = defaultdict(lambda: defaultdict(lambda: -1))


def user_item_count(x):
    temp2[x.user_id][x.item_id] += 1
    return temp2[x.user_id][x.item_id]


temp2 = defaultdict(lambda: defaultdict(lambda: -1))


def user_shop_count(x):
    temp2[x.user_id][x.shop_id] += 1
    return temp2[x.user_id][x.shop_id]


temp3 = defaultdict(lambda: defaultdict(lambda: defaultdict(lambda: -1)))


def user_item_day_count(x):
    temp3[x.day][x.user_id][x.item_id] += 1
    return temp3[x.day][x.user_id][x.item_id]


temp4 = defaultdict(lambda: defaultdict(lambda: defaultdict(lambda: -1)))


def user_shop_day_count(x):
    temp4[x.day][x.user_id][x.shop_id] += 1
    return temp4[x.day][x.user_id][x.shop_id]


train['user_item_num'] = train.apply(user_item_count, axis=1)
train['user_shop_num'] = train.apply(user_shop_count, axis=1)
train['user_item_day_num'] = train.apply(user_item_day_count, axis=1)
train['user_shop_day_num'] = train.apply(user_shop_day_count, axis=1)

In [14]:
#user上下次浏览时间、时间差
from datetime import datetime, timedelta

train['user_next_count'] = train.user_count + 1
train['user_last_count'] = train.user_count - 1
temp_time = df_time[['user_id', 'user_count', 'time']].copy()

temp_time.columns = ['user_id', 'user_next_count', 'user_next_time']
train = train.merge(temp_time, on=['user_id', 'user_next_count'], how='left')
temp_time.columns = ['user_id', 'user_last_count', 'user_last_time']
train = train.merge(temp_time, on=['user_id', 'user_last_count'], how='left')


def next_time_sub(x):
    if type(x.user_next_time) == float:
        return 999999
    else:
        return (datetime.strptime(x.user_next_time, '%Y-%m-%d  %H:%M:%S') -
                datetime.strptime(x.time, '%Y-%m-%d  %H:%M:%S')).seconds


def last_time_sub(x):
    if type(x.user_last_time) == float:
        return 999999
    else:
        return (
            datetime.strptime(x.time, '%Y-%m-%d  %H:%M:%S') -
            datetime.strptime(x.user_last_time, '%Y-%m-%d  %H:%M:%S')).seconds


train['next_time_sub'] = train.apply(next_time_sub, axis=1)
train['last_time_sub'] = train.apply(last_time_sub, axis=1)

In [15]:
#user_item、user_shop时间差
train['user_item_num_next'] = train.user_item_num + 1
train['user_item_num_last'] = train.user_item_num - 1
train['user_shop_num_next'] = train.user_shop_num + 1
train['user_shop_num_last'] = train.user_shop_num - 1

temp_time = df_time[['user_id', 'item_id', 'user_item_num', 'time']].copy()
temp_time.columns = [
    'user_id', 'item_id', 'user_item_num_next', 'user_item_next_time'
]
train = train.merge(
    temp_time, on=['user_id', 'item_id', 'user_item_num_next'], how='left')
temp_time.columns = [
    'user_id', 'item_id', 'user_item_num_last', 'user_item_last_time'
]
train = train.merge(
    temp_time, on=['user_id', 'item_id', 'user_item_num_last'], how='left')

temp_time = df_time[['user_id', 'shop_id', 'user_shop_num', 'time']].copy()
temp_time.columns = [
    'user_id', 'shop_id', 'user_shop_num_next', 'user_shop_next_time'
]
train = train.merge(
    temp_time, on=['user_id', 'shop_id', 'user_shop_num_next'], how='left')
temp_time.columns = [
    'user_id', 'shop_id', 'user_shop_num_last', 'user_shop_last_time'
]
train = train.merge(
    temp_time, on=['user_id', 'shop_id', 'user_shop_num_last'], how='left')


def next_time_sub(x):
    if type(x.user_item_next_time) == float:
        return 999999
    else:
        return (datetime.strptime(x.user_item_next_time, '%Y-%m-%d  %H:%M:%S')
                - datetime.strptime(x.time, '%Y-%m-%d  %H:%M:%S')).seconds


def last_time_sub(x):
    if type(x.user_item_last_time) == float:
        return 999999
    else:
        return (datetime.strptime(x.time, '%Y-%m-%d  %H:%M:%S') -
                datetime.strptime(x.user_item_last_time,
                                  '%Y-%m-%d  %H:%M:%S')).seconds


train['user_item_next_time_sub'] = train.apply(next_time_sub, axis=1)
train['user_item_last_time_sub'] = train.apply(last_time_sub, axis=1)


def next_time_sub(x):
    if type(x.user_shop_next_time) == float:
        return 999999
    else:
        return (datetime.strptime(x.user_shop_next_time, '%Y-%m-%d  %H:%M:%S')
                - datetime.strptime(x.time, '%Y-%m-%d  %H:%M:%S')).seconds


def last_time_sub(x):
    if type(x.user_shop_last_time) == float:
        return 999999
    else:
        return (datetime.strptime(x.time, '%Y-%m-%d  %H:%M:%S') -
                datetime.strptime(x.user_shop_last_time,
                                  '%Y-%m-%d  %H:%M:%S')).seconds


train['user_shop_next_time_sub'] = train.apply(next_time_sub, axis=1)
train['user_shop_last_time_sub'] = train.apply(last_time_sub, axis=1)

In [16]:
#user第一次出现时间差
train['user_fisrt_num'] = 0  #user_count
train['user_item_fisrt_num'] = 0  #user_item_num
train['user_shop_fisrt_num'] = 0  #user_shop_num
temp_time = df_time[[
    'user_id', 'item_id', 'shop_id', 'user_count', 'user_item_num',
    'user_shop_num', 'time'
]].copy()

temp_time.columns = [
    'user_id', 'item_id', 'shop_id', 'user_fisrt_num', 'user_item_fisrt_num',
    'user_shop_fisrt_num', 'user_count_first_time'
]
train = train.merge(
    temp_time[['user_id', 'user_fisrt_num', 'user_count_first_time']],
    on=['user_id', 'user_fisrt_num'],
    how='left')
temp_time.columns = [
    'user_id', 'item_id', 'shop_id', 'user_fisrt_num', 'user_item_fisrt_num',
    'user_shop_fisrt_num', 'user_item_count_first_time'
]
train = train.merge(
    temp_time[[
        'user_id', 'item_id', 'user_item_fisrt_num',
        'user_item_count_first_time'
    ]],
    on=['user_id', 'item_id', 'user_item_fisrt_num'],
    how='left')
temp_time.columns = [
    'user_id', 'item_id', 'shop_id', 'user_fisrt_num', 'user_item_fisrt_num',
    'user_shop_fisrt_num', 'user_shop_count_first_time'
]
train = train.merge(
    temp_time[[
        'user_id', 'shop_id', 'user_shop_fisrt_num',
        'user_shop_count_first_time'
    ]],
    on=['user_id', 'shop_id', 'user_shop_fisrt_num'],
    how='left')


def first_time_sub(x):
    return (
        datetime.strptime(x.time, '%Y-%m-%d  %H:%M:%S') - datetime.strptime(
            x.user_count_first_time, '%Y-%m-%d  %H:%M:%S')).seconds


train['user_count_first_time_sub'] = train.apply(first_time_sub, axis=1)


def first_time_sub(x):
    return (
        datetime.strptime(x.time, '%Y-%m-%d  %H:%M:%S') - datetime.strptime(
            x.user_item_count_first_time, '%Y-%m-%d  %H:%M:%S')).seconds


train['user_item_count_first_time_sub'] = train.apply(first_time_sub, axis=1)


def first_time_sub(x):
    return (
        datetime.strptime(x.time, '%Y-%m-%d  %H:%M:%S') - datetime.strptime(
            x.user_shop_count_first_time, '%Y-%m-%d  %H:%M:%S')).seconds


train['user_shop_count_first_time_sub'] = train.apply(first_time_sub, axis=1)

In [17]:
#最后一次点击
from datetime import datetime, timedelta

user_last = train.groupby(
    ['user_id'], as_index=False)['user_count'].agg({
        'max_click': 'max'
    })
user_item_last = train.groupby(
    ['user_id', 'item_id'], as_index=False)['user_item_num'].agg({
        'max_user_item_click':
        'max'
    })

train = train.merge(user_last, on=['user_id'], how='left')
train['is_last_click'] = train.apply(
    lambda x: 1 if x.max_click == x.user_count else 0, axis=1)
train = train.merge(user_item_last, on=['user_id', 'item_id'], how='left')
train['is_last_user_item_click'] = train.apply(
    lambda x: 1 if x.max_user_item_click == x.user_item_num else 0, axis=1)

user_last_time = train[['user_id', 'user_count', 'time']]
user_last_time.columns = ['user_id', 'max_click', 'max_click_time']
train = train.merge(user_last_time, on=['user_id', 'max_click'], how='left')
user_item_last_time = train[['user_id', 'item_id', 'user_item_num', 'time']]
user_item_last_time.columns = ['user_id', 'item_id', 'max_user_item_click', 'max_user_item_click_time']
train = train.merge(user_item_last_time, on=['user_id', 'item_id', 'max_user_item_click'], how='left')

def last_time_sub(x):
    return (
        datetime.strptime(x.max_click_time, '%Y-%m-%d  %H:%M:%S') - datetime.strptime(
            x.time, '%Y-%m-%d  %H:%M:%S')).seconds

train['max_click_time_sub'] = train.apply(last_time_sub, axis=1)

def last_time_sub(x):
    return (
        datetime.strptime(x.max_user_item_click_time, '%Y-%m-%d  %H:%M:%S') - datetime.strptime(
            x.time, '%Y-%m-%d  %H:%M:%S')).seconds

train['max_user_item_click_time_sub'] = train.apply(last_time_sub, axis=1)

In [2]:
train = pd.read_csv('train_preprocessing34.csv')
his = pd.read_csv('his_preprocessing34.csv')
his_trade = his[his.is_trade == 1]

In [3]:
# train = train.iloc[:, :129]
train.shape
train.head()
#(278894, 85)(3:4)
#(347271, 87)(2:5)

(278894, 168)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,item_category_split,item_property_split,predict_category_property_split,item_category_split_count,item_property_split_count,time,day,hour,minute,user_query_day,user_query_day_hour,user_query_minute,user_shop_count,user_item_count,user_context_count,user_shop_trade_count,user_item_trade_count,user_context_trade_count,user_brand_count,user_city_count,user_brand_trade_count,user_city_trade_count,item_occupation_count,item_age_count,item_gender_count,item_occupation_trade_count,item_age_trade_count,item_gender_trade_count,shop_score,item_score,item_score2,item_score3,predict_category_split,predict_property_split,pred_category_split_count,pred_property_split_count,item_pred_category_score,item_pred_property_score,item_pred_category_score_item%,item_pred_property_score_item%,item_pred_category_score_pred%,item_pred_property_score_pred%,item_hot,user_hot,shop_hot,brand_hot,occupation_hot,city_hot,item_trade_hot,user_trade_hot,shop_trade_hot,brand_trade_hot,occupation_trade_hot,city_trade_hot,user_sell_power,user_sell_power_mean,user_sell_power_mean_item_minus,user_sell_trade_power,user_sell_trade_power_mean,user_sell_trade_power_mean_item_minus,yesterday,yesterhour,user_day_query,user_yesterday_query,user_hour_query,user_yesterhour_query,user_minute_query,item_day_query,item_hour_query,item_minute_query,user_item_day_query,user_item_hour_query,user_item_minute_query,min_time,user_is_his,item_is_his,brand_is_his,user_is_trade_his,item_is_trade_his,brand_is_trade_his,user_count,user_day_count,user_hour_count,user_minute_count,item_trade_percent,brand_trade_percent,user_trade_percent,occupation_trade_percent,is_home,shop_item_count,brand_item_count,city_brand_count,city_item_count,shop_item_count_his,brand_item_count_his,city_brand_count_his,city_item_count_his,item_id_idx,user_id_idx,shop_id_idx,item_brand_id_idx,item_city_id_idx,user_item_num,user_shop_num,user_item_day_num,user_shop_day_num,user_next_count,user_last_count,user_next_time,user_last_time,next_time_sub,last_time_sub,user_item_num_next,user_item_num_last,user_shop_num_next,user_shop_num_last,user_item_next_time,user_item_last_time,user_shop_next_time,user_shop_last_time,user_item_next_time_sub,user_item_last_time_sub,user_shop_next_time_sub,user_shop_last_time_sub,user_fisrt_num,user_item_fisrt_num,user_shop_fisrt_num,user_count_first_time,user_item_count_first_time,user_shop_count_first_time,user_count_first_time_sub,user_item_count_first_time_sub,user_shop_count_first_time_sub,max_click,is_last_click,max_user_item_click,is_last_user_item_click,max_click_time,max_user_item_click_time,max_click_time_sub,max_user_item_click_time_sub
0,4293715837363757697,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,4,4,14,8711326521450559534,0,1000,2005,3003,5035994110420503338,1537465939,1,5799347067982556520:9172976955054793469;725801...,6765930309048922341,4,1.000000,3,1.000000,1.000000,1.000000,0,"['7908382889764677758', '5799347067982556520']","['2072967855524022579', '5131280576272319091',...","[['5799347067982556520', '9172976955054793469'...",2,21,2018-09-21 01:52:19,21,1,55,9,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,6.0,0.0,0.0,0.0,7.000000,60,20.000,10.000000,"['5799347067982556520', '7258015885215914736',...","['9172976955054793469', '9172976955054793469']",5,2,2,1,6.666667,0.454545,3.333333,3.333333,12.0,0.0,12.0,50.0,137467,25252.0,0.0,0.0,0.0,0.0,2611,429.0,0.0,0.0,3.0,0.0,0.0,3.0,20,0,9,0.0,1,0.0,1,1,1,1,1,1,1,3.0,1,0,1,1,1,1,0,0,0,0,0.000000,0.000000,0.0,1.899365,0,1,7,224,1014,1.0,13.0,204.0,968.0,2654,123470,1907,390,28,0,0,0,0,1,-1,2018-09-21 04:30:26,NaN,9487,999999,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-21 01:52:19,2018-09-21 01:52:19,2018-09-21 01:52:19,0,0,0,8,0,0,1,2018-09-21 04:37:13,2018-09-21 01:52:19,9894,0
1,70764105903083828,285660928590172217,7908382889764677758;8277336076276184272,2072967855524022579;5131280576272319091;263639...,9057103201734987852,548352491538518780,8,9,8,14,8064892827740019258,0,1003,2005,3003,7972645707776427108,1537537076,14,8277336076276184272:820214312075361939;5799347...,4885989684392199728,15,0.985647,13,0.974774,0.976604,0.969257,0,"['7908382889764677758', '8277336076276184272']","['2072967855524022579', '5131280576272319091',...","[['8277336076276184272', '820214312075361939']...",2,50,2018-09-21 21:37:56,21,21,35,9,8,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0,13.0,22.0,1.0,1.0,1.0,25.636987,121,15.125,1.008333,"['8277336076276184272', '5799347067982556520',...",['820214312075361939'],4,1,2,1,6.666667,0.196078,4.000000,5.000000,29.0,0.0,55.0,70.0,137467,739.0,1.0,0.0,2.0,1.0,2611,11.0,0.0,0.0,8.0,0.0,0.0,8.0,20,20,9,0.0,8,0.0,5,15,3,1,1,1,1,43.0,1,0,1,1,0,0,0,0,0,0,3.448276,1.428571,0.0,1.899365,0,2,3,24,84,2.0,4.0,21.0,79.0,5371,65467,668,893,56,0,0,0,0,1,-1,2018-09-21 21:30:25,NaN,85949,999999,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-21 21:37:56,2018-09-21 21:37:56,2018-09-21 21:37:56,0,0,0,8,0,0,1,2018-09-21 21:57:45,2018-09-21 21:37:56,1189,0
2,3954908518456917085,5202355029344881809,7908382889764677758;5755694407684602296,2072967855524022579;5131280576272319091;263639...,5520678735822176314,548352491538518780,8,9,10,16,1633738185485564030,0,1003,2005,3003,6797298244965748241,1537539269,1,5755694407684602296:6538068079754090196;836752...,4885989684392199728,15,0.985647,13,0.974774,0.976604,0.969257,0,"['7908382889764677758', '5755694407684602296']","['2072967855524022579', '5131280576272319091',...","[['5755694407684602296', '6538068079754090196'...",2,46,2018-09-21 22:14:29,21,22,15,2,2,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,10.0,20.0,0.0,1.0,1.0,25.636987,169,21.125,10.562500,"['5755694407684602296', '836752724084922533', ...","['6538068079754090196', '6538068079754090196,3...",3,3,2,0,6.666667,0.000000,5.000000,0.000000,26.0,0.0,55.0,60.0,137467,739.0,1.0,0.0,2.0,1.0,2611,11.0,0.0,0.0,8.0,0.0,0.0,8.0,20,21,2,0.0,2,0.0,2,14,2,2,1,1,1,44.0,1,0,1,1,0,0,0,0,0,0,3.846154,1.666667,0.0,1.899365,0,2,3,24,84,2.0,3.0,21.0,79.0,818,115727,668,14,56,0,0,0,0,1,-1,2018-09-21 22:14:11,NaN,86382,999999,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-21 22:14:29,2018-09-21 22:14:29,2018-09-21 22:14:29,0,0,0,1,0,0,1,2018-09-21 22:14:11,2018-09-21 22:14:29,86382,0
3,4521314384240415059,285660928590172217,7908382889764677758;8277336076276184272,2072967855524022579;5131280576272319091;263639...,9057103201734987852,548352491538518780,8,9,8,14,7983400645978077748,0,1003,2005,3005,7455406367907195,1537509234,0,8277336076276184272:820214312075361939;5799347...,4885989684392199728,15,0.985647,13,0.974774,0.976604,0.969257,0,"['7908382889764677758', '8277336076276184272']","['2072967855524022579', '5131280576272319091',...","[['8277336076276184272', '820214312075361939']...",2,50,2018-09-21 13:53:54,21,13,55,9,3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0,13.0,22.0,1.0,1.0,1.0,25.636987,121,15.125,15.125000,"['8277336076276184272', '5799347067982556520',...","['820214312075361939', '2636395404473730413,91...",4,2,2,1,6.666667,0.196078,4.000000,3.333333,29.0,0.0,55.0,70.0,137467,739.0,1.0,0.0,2.0,1.0,2611,11.0,0.0,0.0,8.0,0.0,0.0,8.0,20,12,9,0.0,3,0.0,3,15,2,2,2,1,1,27.0,1,0,1,1,0,0,0,0,0,0,3.448276,1.428571,0.0,1.899365,0,2,3,24,84,2.0,4.0,21.0,79.0,5371,53815,668,893,56,0,0,0,0,1,-1,2018-09-21 21:58:53,NaN,29099,999999,1,-1,1,-1,2018-09-21 21:58:53,NaN,2018-09-21 21:58:53,NaN,29099,999999,29099,999999,0,0,0,2018-09-21 13:53:54,2018-09-21 13:53:54,2018-09-21 13:53:54,0,0,0,9,0,1,0,2018-09-25 22:16:27,2018-09-21 21:58:53,30153,29099
4,6005676298575614673,5202355029344881809,7908382889764677758;5755694407684602296,2072967855524022579;5131280576272319091;263639...,5520678735822176314,548352491538518780,8,9,10,16,4831066601005367480,0,1007,2005,3002,1422823996606455864,1537494715,0,5755694407684602296:-1;7447522129235776380:-1;...,4885989684392199728,15,0.985647,13,0.974774,0.976604,0.969257,0,"['7908382889764677758', '5755694407684602296']","['2072967855524022579', '5131280576272319091',...","[['5755694407684602296', '-1'], ['744752212923...",2,46,2018-09-21 09:51:55,21,9,55,1,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,20.0,0.0,0.0,1.0,25.636987,169,21.125,21.125000,"['5755694407684602296', '7447522129235776380',...",['2253152183208719552'],5,1,2,1,6.666667,0.212766,3.333333,5.000000,26.0,0.0,55.0,60.0,137467,739.0,1.0,0.0,2.0,1.0,2611,11.0,0.0,0.0,8.0,0.0,0.0,8.0,20,8,1,0.0,1,0.0,1,14,1,1,1,1,1,19.0,1,0,1,1,0,0,0,0,0,0,3.846154,1.666667,0.0,1.899365,0,2,3,24,84,2.0,3.0,21.0,79.0,818,54570,668,14,56,0,0,0,0,1,-1,NaN,NaN,999999,999999,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-21 09:51:55,2018-09-21 09:51:55,2018-09-21 09:51:55,0,0,0,0,1,0,1,2018-09-21 09:51:55,2018-09-21 09:51:55,0,0

In [8]:
#重新处理item_score

train['item_score'] = (
    train.item_sales_level + train.item_collected_level * train.item_pv_level)
train['item_score2'] = (
    train.item_sales_level + train.item_collected_level * train.item_pv_level
) / (train.item_price_level + 2)
train['item_score3'] = (
    (train.item_sales_level + train.item_collected_level * train.item_pv_level
     ) / (train.item_price_level + 2)) / (train.context_page_id + 2)

In [12]:
#good_features
origin = [
    'item_price_level', 'item_sales_level', 'item_collected_level',
    'item_pv_level', 'user_gender_id', 'user_age_level', 'user_occupation_id',
    'user_star_level', 'context_page_id', 'shop_review_num_level',
    'shop_review_positive_rate', 'shop_star_level', 'shop_score_service',
    'shop_score_delivery', 'shop_score_description'
]

predictors = [
    'item_category_split_count', 'item_property_split_count', 'day', 'hour',
    'minute', 'user_shop_count', 'user_item_count', 'user_context_count',
    'user_shop_trade_count', 'user_item_trade_count',
    'user_context_trade_count', 'user_brand_count', 'user_city_count',
    'user_brand_trade_count', 'user_city_trade_count', 'item_occupation_count',
    'item_age_count', 'item_gender_count', 'item_occupation_trade_count',
    'item_age_trade_count', 'item_gender_trade_count', 'shop_score',
    'item_score', 'item_score2', 'item_score3', 'pred_category_split_count',
    'pred_property_split_count', 'item_pred_category_score',
    'item_pred_property_score', 'item_pred_category_score_item%',
    'item_pred_property_score_item%', 'item_pred_category_score_pred%',
    'item_pred_property_score_pred%', 'item_hot', 'user_hot', 'shop_hot',
    'brand_hot', 'occupation_hot', 'city_hot', 'item_trade_hot',
    'user_trade_hot', 'shop_trade_hot', 'brand_trade_hot',
    'occupation_trade_hot', 'city_trade_hot', 'user_sell_power',
    'user_sell_power_mean', 'user_sell_power_mean_item_minus',
    'user_sell_trade_power', 'user_sell_trade_power_mean',
    'user_sell_trade_power_mean_item_minus', 'yesterday', 'yesterhour',
    'user_day_query', 'user_yesterday_query', 'user_hour_query',
    'user_yesterhour_query', 'user_minute_query', 'item_day_query',
    'item_hour_query', 'user_item_day_query', 'user_item_hour_query',
    'item_minute_query', 'user_item_minute_query', 'user_count',
    'user_day_count', 'user_hour_count', 'user_minute_count', 'min_time',
    'user_is_his', 'item_is_his', 'brand_is_his', 'user_is_trade_his',
    'item_is_trade_his', 'brand_is_trade_his', 'item_trade_percent',
    'brand_trade_percent', 'user_trade_percent', 'occupation_trade_percent',
    'is_home', 'shop_item_count', 'brand_item_count', 'city_brand_count',
    'city_item_count', 'shop_item_count_his', 'brand_item_count_his',
    'city_brand_count_his', 'city_item_count_his', 'item_id_idx',
    'user_id_idx', 'shop_id_idx', 'item_brand_id_idx', 'item_city_id_idx',
    'next_time_sub', 'last_time_sub', 'user_item_num', 'user_shop_num',
    'user_item_day_num', 'user_shop_day_num', 'user_item_next_time_sub',
    'user_item_last_time_sub', 'user_shop_next_time_sub',
    'user_shop_last_time_sub', 'user_count_first_time_sub',
    'user_item_count_first_time_sub', 'user_shop_count_first_time_sub',
    'is_last_click', 'is_last_user_item_click', 'max_click_time_sub',
    'max_user_item_click_time_sub'
]

rubbish_features = [
    'user_id_idx', 'item_id_idx', 'item_hour_query',
    'item_pred_category_score_pred%', 'item_brand_id_idx', 'brand_trade_hot',
    'brand_trade_hot', 'shop_id_idx', 'min_time', 'item_age_count',
    'brand_trade_percent'
]

target = ['is_trade']

In [ ]:
#user偏好哪类商品

In [ ]:
#冷启动特征

In [ ]:
#GBDT叶子特征

In [ ]:
#平均数编码

In [13]:
predictors = list(set(origin + predictors))
predictors = list(set(predictors) - set(rubbish_features))
train[predictors].to_csv('train_preprocessing34_good_features.csv', index=False)

In [14]:
train.to_csv('train_preprocessing34.csv', index=False)
his.to_csv('his_preprocessing34.csv', index=False)

# Distribution

In [34]:
des = pd.DataFrame()

des['data_count'] = df[df.is_trade != -1].groupby(['day']).instance_id.count()
des['trade_count'] = df[df.is_trade == 1].groupby(['day']).instance_id.count()
des['trade_percent'] = df[df.is_trade == 1].groupby(['day']).instance_id.count(
) / df[df.is_trade != -1].groupby(['day']).instance_id.count() * 100

des

     data_count  trade_count  trade_percent
day
18        78268         1567       2.002095
19        70931         1396       1.968110
20        68387         1324       1.936040
21        71199         1375       1.931207
22        68318         1289       1.886765
23        63614         1099       1.727607
24        57421          971       1.691019

In [12]:
df[df.is_trade == -1].groupby(['day']).instance_id.count()

day
25    18371
Name: instance_id, dtype: int64