In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import time
from tqdm import tqdm

pd.set_option('display.max_columns',None)

%matplotlib inline

#每次可以输出多个变量
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from pylab import rcParams
rcParams['figure.figsize'] = 14, 6

#中文字体
import matplotlib  
matplotlib.use('qt4agg')  
#指定默认字体  
matplotlib.rcParams['font.sans-serif'] = ['SimHei']   
matplotlib.rcParams['font.family']='sans-serif'  
#解决负号'-'显示为方块的问题  
matplotlib.rcParams['axes.unicode_minus'] = False

/usr/local/miniconda2/envs/py35/lib/python3.5/site-packages/matplotlib/__init__.py:1405: UserWarning:
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)

# One-Hot

In [5]:
from sklearn import preprocessing
import xgboost as xgb
import ast

In [6]:
wifi_infos = pd.read_csv('./output/wifi_info.csv')
wifi_infos = wifi_infos.drop(['Unnamed: 0'], axis=1)

wifi_infos = wifi_infos.bssid.value_counts()
many_wifi = []
for index in wifi_infos.index:
    if wifi_infos[index] >= 85:
        many_wifi.append(index)
        
len(many_wifi)

30156

In [5]:
wifi_connected = pd.read_csv('./output/wifi_connected.csv')
wifi_connected = wifi_connected[['full_order', 'bssid']]
wifi_connected = wifi_connected.drop_duplicates(['full_order'])

wifi_connected_infos = wifi_connected.bssid.value_counts()
many_wifi_connected = []
for index in wifi_connected_infos.index:
    if (wifi_connected_infos[index] >= 100) & (wifi_connected_infos[index] < 200):
        many_wifi_connected.append(index)
        
wifi_connected = wifi_connected.as_matrix()
temp = []
for i in range(wifi_connected.shape[0]):
    if wifi_connected[i, 1] in many_wifi_connected:
        temp.append(wifi_connected[i])
        
wifi_connected = pd.DataFrame(temp, columns=['full_order', 'bssid'])
del temp
wifi_connected.shape
wifi_connected.head()

(30053, 2)

   full_order       bssid
0          83  b_56323049
1          84  b_56323049
2         123   b_6937466
3         124   b_6937466
4         125   b_6937466

In [4]:
shop = pd.read_csv('../input/训练数据-ccf_first_round_shop_info.csv')
shop = shop[['shop_id', 'category_id', 'price']]

train = pd.read_csv('../input/训练数据-ccf_first_round_user_shop_behavior.csv')
train.user_id = train.user_id.apply(lambda x : int(x[2:]))
train['full_order'] = train.index
train = train.merge(shop, on=['shop_id'], how='left')

test = pd.read_csv('../input/AB榜测试集-evaluation_public.csv')
test.user_id = test.user_id.apply(lambda x : int(x[2:]))
test['full_order'] = test.index + 1138015

In [6]:
full_data_wifi_infos = pd.concat([train[['full_order', 'wifi_infos']], test[['full_order', 'wifi_infos']]])

In [ ]:
def wifi_shop_connect(temp):
    fuck=temp[['shop_id','wifi_infos']].values
    res1=[]
    res2=[]
    res3=[]
    res4=[]
    for i in fuck:
        wifis=i[1].split(';')
        for j in wifis:
            wifi=j.split('|')
            res1.append(i[0])
            res2.append(wifi[0])
            res4.append(wifi[1])
            if wifi[2]=='true':
                res3.append(1)
            else:
                res3.append(0)
    t_data=pd.DataFrame()
    t_data['shop_id']=res1
    t_data['wifi_id']=res2
    t_data['connect']=res3
    res4=[int(x) for x in res4]
    t_data['strength']=res4
#     t_data=t_data[t_data.connect==1]
    return t_data 

shop_wifi = wifi_shop_connect(train)

temp = shop_wifi.groupby(['shop_id', 'wifi_id'], as_index=False).agg({'connect':'count', 'strength':'mean'})
temp.columns = ['shop_id', 'wifi_id', 'strength', 'count']
# temp = temp.sort_values(['count', 'strength'], ascending=False)
# temp = temp.drop_duplicates(['shop_id'])

shop_wifi_only_connect = temp
del temp
del shop_wifi

In [9]:
def wifi_shop_stre(temp):
    fuck=temp[['shop_id','wifi_infos']].values
    res1=[]
    res2=[]
    res3=[]
    res4=[]
    for i in fuck:
        wifis=i[1].split(';')
        for j in wifis:
            wifi=j.split('|')
            res1.append(i[0])
            res2.append(wifi[0])
            res4.append(wifi[1])
            if wifi[2]=='true':
                res3.append(1)
            else:
                res3.append(0)
    t_data=pd.DataFrame()
    t_data['shop_id']=res1
    t_data['wifi_id']=res2
    t_data['connect']=res3
    res4=[int(x) for x in res4]
    t_data['strength']=res4
    return t_data 

shop_wifi = wifi_shop_stre(train)

temp = shop_wifi.groupby(['shop_id'], as_index=False).agg({'strength':['mean']})
temp.columns = ['shop_id', 'strength', 'wifi_id']
temp = temp.sort_values(['strength'], ascending=False)
# temp = temp.drop_duplicates(['shop_id'])

shop_wifi_stre_connect = temp[['shop_id', 'wifi_id', 'strength']]
del temp
del shop_wifi

In [10]:
shop_wifi_only.shape # 所有WiFi
shop_wifi_only_connect.shape # 连接WiFi
shop_wifi_stre.shape # 所有WiFi
shop_wifi_stre_connect.shape # 连接WiFi

(8477, 3)

(7927, 3)

(8477, 3)

(7927, 3)

In [ ]:

        if mall_id not in finish_shop:
            shops_new = pd.DataFrame()
            shops = m_full[m_full.flag != -1][['shop_id']].copy()
            shops = shops.merge(shop_wifi_only, on=['shop_id'], how='left')
            shops = shops.rename(columns={'wifi_id':'wifi_id_count', 'strength':'strength_count'})
            shops = shops.merge(shop_wifi_stre, on=['shop_id'], how='left')
            shops = shops.rename(columns={'wifi_id':'wifi_id_stre', 'strength':'strength_stre'})
            shops = shops.merge(shop_wifi_only_connect, on=['shop_id'], how='left')
            shops = shops.rename(columns={'wifi_id':'wifi_id_count_connect', 'strength':'strength_count_connect_connect'})
            shops = shops.merge(shop_wifi_stre_connect, on=['shop_id'], how='left')
            shops = shops.rename(columns={'wifi_id':'wifi_id_stre_connect', 'strength':'strength_stre_connect'})
            shops = shops.fillna(0)
            for line in shops.values:
                temp = {}
                if line[1] in m1.columns:
                    if m1.loc[0, line[1]] == -113:
                        temp['has1'] = 0
                    else:
                        temp['has1'] = 1
                    temp['stre_diff1'] = abs(int(line[2]) - int(m1.loc[0, line[1]]))
                else:
                    temp['has1'] = 0
                    temp['stre_diff1'] = 113
                if line[3] in m1.columns:
                    if m1.loc[0, line[3]] == -113:
                        temp['has2'] = 0
                    else:
                        temp['has2'] = 1
                    temp['stre_diff2'] = abs(int(line[4]) - int(m1.loc[0, line[3]]))
                else:
                    temp['has2'] = 0
                    temp['stre_diff2'] = 113
                if line[5] in m1.columns:
                    if m1.loc[0, line[3]] == -113:
                        temp['connect1'] = 0
                    else:
                        temp['connect1'] = 1
                    temp['stre_diff3'] = abs(int(line[4]) - int(m1.loc[0, line[3]]))
                else:
                    temp['connect1'] = 0
                    temp['stre_diff3'] = 113
                if line[7] in m1.columns:
                    if m1.loc[0, line[3]] == -113:
                        temp['connect2'] = 0
                    else:
                        temp['connect2'] = 1
                    temp['stre_diff4'] = abs(int(line[4]) - int(m1.loc[0, line[3]]))
                else:
                    temp['connect2'] = 0
                    temp['stre_diff4'] = 113
                shops_new = shops_new.append(temp, ignore_index=True)
                
            shops = m_full[m_full.flag == -1][['shop_id']].copy()
            shops = shops.merge(shop_wifi_only, on=['shop_id'], how='left')
            shops = shops.rename(columns={'wifi_id':'wifi_id_count', 'strength':'strength_count'})
            shops = shops.merge(shop_wifi_stre, on=['shop_id'], how='left')
            shops = shops.rename(columns={'wifi_id':'wifi_id_stre', 'strength':'strength_stre'})
            shops = shops.merge(shop_wifi_only_connect, on=['shop_id'], how='left')
            shops = shops.rename(columns={'wifi_id':'wifi_id_count_connect', 'strength':'strength_count_connect_connect'})
            shops = shops.merge(shop_wifi_stre_connect, on=['shop_id'], how='left')
            shops = shops.rename(columns={'wifi_id':'wifi_id_stre_connect', 'strength':'strength_stre_connect'})
            shops = shops.fillna(0)
            for line in shops.values:
                temp = {}
                if line[1] in m1.columns:
                    if m1.loc[0, line[1]] == -113:
                        temp['has1'] = 0
                    else:
                        temp['has1'] = 1
                    temp['stre_diff1'] = abs(int(line[2]) - int(m1.loc[0, line[1]]))
                else:
                    temp['has1'] = 0
                    temp['stre_diff1'] = 113
                if line[3] in m1.columns:
                    if m1.loc[0, line[3]] == -113:
                        temp['has2'] = 0
                    else:
                        temp['has2'] = 1
                    temp['stre_diff2'] = abs(int(line[4]) - int(m1.loc[0, line[3]]))
                else:
                    temp['has2'] = 0
                    temp['stre_diff2'] = 113
                if line[5] in m1.columns:
                    if m1.loc[0, line[3]] == -113:
                        temp['connect1'] = 0
                    else:
                        temp['connect1'] = 1
                    temp['stre_diff3'] = abs(int(line[4]) - int(m1.loc[0, line[3]]))
                else:
                    temp['connect1'] = 0
                    temp['stre_diff3'] = 113
                if line[7] in m1.columns:
                    if m1.loc[0, line[3]] == -113:
                        temp['connect2'] = 0
                    else:
                        temp['connect2'] = 1
                    temp['stre_diff4'] = abs(int(line[4]) - int(m1.loc[0, line[3]]))
                else:
                    temp['connect2'] = 0
                    temp['stre_diff4'] = 113
                shops_new = shops_new.append(temp, ignore_index=True)
            
            shops_new.reset_index(drop=True, inplace=True)
            pickle.dump(shops_new, open('./output/new_feature_shop/' + str(mall_id) + '.p', 'wb'), protocol=4)
        else:
            shops_new = pickle.load(open('./output/new_feature_shop/' + str(mall_id) + '.p', 'rb'))
        m_full = pd.concat([m_full, shops_new], axis=1)

In [8]:
def get_time_hour(data):
    data['hourofday']=pd.DatetimeIndex(data.time_stamp).hour
    data['dayofweek']=pd.DatetimeIndex(data.time_stamp).day
    return data

# 相差的分钟数
def diff_of_minutes(time1, time2):
    d = {'5': 0, '6': 31, }
    try:
        days = (d[time1[6]] + int(time1[8:10])) - (d[time2[6]] + int(time2[8:10]))
        try:
            minutes1 = int(time1[11:13]) * 60 + int(time1[14:16])
        except:
            minutes1 = 0
        try:
            minutes2 = int(time2[11:13]) * 60 + int(time2[14:16])
        except:
            minutes2 = 0
        return (days * 1440 - minutes2 + minutes1)
    except:
        return np.nan

# 计算两点之间距离
def call_distance(lat1,lon1,lat2,lon2):
    dx = np.abs(lon1 - lon2)  # 经度差
    dy = np.abs(lat1 - lat2)  # 维度差
    b = (lat1 + lat2) / 2.0
    Lx = 6371004.0 * (dx / 57.2958) * np.cos(b / 57.2958)
    Ly = 6371004.0 * (dy / 57.2958)
    L = (Lx**2 + Ly**2) ** 0.5
    return L

def call_orientation(lat1,lon1,lat2,lon2):
    radLat1 = math.radians(lat1)  
    radLon1 = math.radians(lon1)  
    radLat2 = math.radians(lat2)  
    radLon2 = math.radians(lon2)  
    dLon = radLon2 - radLon1  
    y = math.sin(dLon) * math.cos(radLat2)  
    x = math.cos(radLat1) * math.sin(radLat2) - math.sin(radLat1) * math.cos(radLat2) * math.cos(dLon)  
    brng = math.degrees(math.atan2(y, x))  
    brng = (brng + 360) % 360  
    return brng

def get_label(data):
    true = dict(zip(train['row_id'].values, train['shop_id']))
    print('label map finish')
    data['label'] = data['row_id'].map(true)
    data['label'] = (data['label'] == data['shop_id']).astype('int')
    return data

def make_wifi_shop_relation(train):
    fuck=train.values
    res1=[]
    res2=[]
    res3=[]
    for i in fuck:
        wifis=i[1].split(';')
        for j in wifis:
            wifi=j.split('|')
            res1.append(i[0])
            res2.append(wifi[0])
            res3.append(int(wifi[1]))
    t_data=pd.DataFrame()
    t_data['shop_id']=res1
    t_data['wifi_id']=res2
    t_data['power']=res3
    return t_data      

def make_wifi_rowid_relation(test):
    fuck=test.values
    res1=[]
    res2=[]
    res3=[]
    for i in fuck:
        wifis=i[1].split(';')
        for j in wifis:
            wifi=j.split('|')
            res1.append(i[0])
            res2.append(wifi[0])
            res3.append(int(wifi[1]))
    t_data=pd.DataFrame()
    t_data['row_id']=res1
    t_data['wifi_id']=res2
    t_data['power']=res3
    return t_data         

def wifi_shop_connect(train):
    fuck=train[['shop_id','wifi_infos']].values
    res1=[]
    res2=[]
    res3=[]
    for i in fuck:
        wifis=i[1].split(';')
        for j in wifis:
            wifi=j.split('|')
            res1.append(i[0])
            res2.append(wifi[0])
            if wifi[2]=='true':
                res3.append(1)
            else:
                res3.append(0)
    t_data=pd.DataFrame()
    t_data['shop_id']=res1
    t_data['wifi_id']=res2
    t_data['connect']=res3
    t_data=t_data[t_data.connect==1]
    return t_data  

def wifi_rowid_conenct(test):
    fuck=test[['row_id','wifi_infos']].values
    res1=[]
    res2=[]
    res3=[]
    for i in fuck:
        wifis=i[1].split(';')
        for j in wifis:
            wifi=j.split('|')
            res1.append(i[0])
            res2.append(wifi[0])
            if wifi[2]=='true':
                res3.append(1)
            else:
                res3.append(0)
    t_data=pd.DataFrame()
    t_data['row_id']=res1
    t_data['wifi_id']=res2
    t_data['connect']=res3
    t_data=t_data[t_data.connect==1]
    return t_data        

#构造wifishop对应信息
def get_wifi_shop_info(train):
    wifi_train = train[['shop_id','wifi_infos']].drop_duplicates()
    wifi_shop_info=make_wifi_shop_relation(wifi_train)
    wifi_shop_info=wifi_shop_info.groupby(['shop_id','wifi_id'],as_index=False)['power'].agg({'ave_power':'mean'})
    return wifi_shop_info

def get_wifi_shop_count(train):
    wifi_train = train[['shop_id','wifi_infos']].drop_duplicates()
    wifi_shop_count=make_wifi_shop_relation(wifi_train)
    wifi_shop_count=wifi_shop_count.groupby(['shop_id','wifi_id'],as_index=False)['power'].agg({'wifi inshopcount':'count'})
    wifi_shop_count.sort_values(['shop_id','wifi inshopcount'],inplace=True)
    wifi_shop_count= wifi_shop_count.groupby('shop_id').tail(50)
    return wifi_shop_count
    
# 通过wifi来构建负样本
def get_wifi_shop(train,test):
    result_path = cache_path + 'wifi_shop_%d.hdf' %(train.shape[0]*test.shape[0])
    if os.path.exists(result_path) & flag:
        result = pd.read_hdf(result_path, 'w')
    else:
        #唯一对应shop 和wifi  还可以通过能量去删选 这部分还没做
        #have connected
        wifi_rowid_connect=wifi_rowid_conenct(test)
        global wifi_shop_connect_only
        result1=pd.merge(wifi_rowid_connect[['row_id','wifi_id']],wifi_shop_connect_only[['wifi_id','shop_id']],on=['wifi_id'])
        result1=result1[['row_id','shop_id']].drop_duplicates()
        result1['canconnect']=1
               
        wifi_shop=wifi_shop_info[['shop_id','wifi_id','ave_power']].drop_duplicates()
       # wifi_shop=wifi_shop[wifi_shop['ave_power']>=-80]
       # b=wifi_shop.sort_values('ave_power')
        #wifi_shop= b.groupby('wifi_id').tail(9)
        wifi_test=test[['row_id','wifi_infos']].drop_duplicates()
        wifi_rowid=make_wifi_rowid_relation(wifi_test)
        #for those not connected use the power
        wifi_rowid=wifi_rowid[~wifi_rowid['row_id'].isin(result1['row_id'])]
        #选取能量最大的三个看看有几个
        result3= pd.merge(wifi_rowid[['row_id','wifi_id']],wifi_shop_connect_only[['wifi_id','shop_id']],on='wifi_id',how='left')
        result3=result3[['row_id','shop_id']].drop_duplicates()
        result3['canconnect']=1
        #wifi_rowid=wifi_rowid[wifi_rowid['power']>=-80]
        a=wifi_rowid.sort_values('power')
        wifi_rowid= a.groupby('row_id').tail(2)
        result2= pd.merge(wifi_rowid[['row_id','wifi_id']],wifi_shop,on='wifi_id',how='left')
        result2=result2[['row_id','shop_id']].drop_duplicates()
        result2['canconnect']=0
        result=pd.concat([result1,result2,result3]).drop_duplicates()
        result = result[(~result['shop_id'].isnull())]
        result.to_hdf(result_path, 'w', complib='blosc', complevel=5)
    return result

def get_user_end_shop(train,test):
    result_path = cache_path + 'user_end_shop_%d.hdf' %(train.shape[0]*test.shape[0])
    if os.path.exists(result_path) & flag:
        result = pd.read_hdf(result_path, 'w')
    else:
        train_new=pd.merge(train,shop1,on='shop_id',how='left')
        user_shop=train_new[['shop_id','user_id','mall_id']].drop_duplicates()
        result=pd.merge(test[['user_id','mall_id','row_id']],user_shop,on=['user_id','mall_id'])
        result=result[['row_id','shop_id']].drop_duplicates()
        result['canconnect']=0
        result.to_hdf(result_path, 'w', complib='blosc', complevel=5)
    return result

def f1(x):
    wifipower={}
    wifi=[]
    power=[]
    wifis=x.split(';')
    for i in wifis:
        s=i.split('|')
        wifi.append(s[0])
        power.append(int(s[1]))
    wifipower = dict(zip(wifi, power))
    wifipower=sorted(wifipower.items(),key=lambda x:x[1],reverse=True)
    return wifipower[0]

def f2(x):
    wifipower={}
    wifi=[]
    power=[]
    wifis=x.split(';')
    for i in wifis:
        s=i.split('|')
        wifi.append(s[0])
        power.append(int(s[1]))
    wifipower = dict(zip(wifi, power))
    wifipower=sorted(wifipower.items(),key=lambda x:x[1],reverse=True)
    if(len(wifipower)>1): 
        return wifipower[1]
    else: 
        return 0
    
def get_wifi(result):
    result['wifi1']=result['wifi_infos'].map(f1)
    result['wifi2']=result['wifi_infos'].map(f2)
    result['wifi1_id']=result['wifi1'].map(lambda x:x[0])
    result['wifi1_power']=result['wifi1'].map(lambda x:x[1])
    result['wifi2_id']=result['wifi2'].map(lambda x:0 if x==0 else x[0])
    result['wifi2_power']=result['wifi2'].map(lambda x:0 if x==0 else x[1])
    wifi_shop_info.rename(columns={'wifi_id':'wifi1_id'},inplace=True)
    result=pd.merge(result,wifi_shop_info,on=['shop_id','wifi1_id'],how='left')
    result.rename(columns={'ave_power':'ave_power1'},inplace=True)
    result['ave_power1']=result['ave_power1'].fillna(result['ave_power1'].min())
    result['power_dif1']=abs((result['ave_power1']-result['wifi1_power']).astype(np.float))
    wifi_shop_info.rename(columns={'wifi1_id':'wifi2_id'},inplace=True)
    result=pd.merge(result,wifi_shop_info,on=['shop_id','wifi2_id'],how='left')
    wifi_shop_info.rename(columns={'wifi2_id':'wifi_id'},inplace=True)
    result.rename(columns={'ave_power':'ave_power2'},inplace=True)
    result['ave_power2']=result['ave_power2'].fillna(result['ave_power2'].min())
    result['power_dif2']=abs((result['ave_power2']-result['wifi2_power']).astype(np.float))
    return result

def wifi_name(x):
    wifi=[]
    wifis=x.split(';')
    for i in wifis:
        s=i.split('|')
        wifi.append(s[0])
    return wifi 

def fuck(x):
    x=list(x.split(':'))
    return x

def get_same_relation(result):
    result['w1']=result['wifi_infos'].map(wifi_name)
    t2 = wifi_shop_count.groupby('shop_id')['wifi_id'].agg(lambda x:':'.join(x)).reset_index()
    t2['w2']=t2['wifi_id'].map(fuck)
    del t2['wifi_id']
    result=pd.merge(result,t2,on=['shop_id'],how='left')
    a=list(result['w1'])
    b=list(result['w2'])
    c=[]
    for i in range(len(a)):
        try:
            d=len(set(a[i])&set(b[i]))
            c.append(d)
        except:
            c.append(0)
    result['w3']=c
    del result['w1']
    del result['w2']
    return result

def get_wifi_power(x):
    wifipower={}
    wifi=[]
    power=[]
    wifis=x.split(';')
    for i in wifis:
        s=i.split('|')
        wifi.append(s[0])
        power.append(int(s[1]))
    wifipower = dict(zip(wifi, power))
    return wifipower

def get_shop_wifi_dic(x):
    wifipower={}
    wifi=[]
    power=[]
    wifis=x.split('|')
    for i in wifis:
        s=i.split(':')
        wifi.append(s[0])
        power.append(float(s[1]))
    wifipower = dict(zip(wifi, power))
    return wifipower

def get_knn(x,y):
    sum=0
    for each in x:
        try:
            if each in y:
                sum+=(x[each]-y[each])**2    #历史信息里存在这个信号的话，计算
            else:
                sum += (x[each]-(-90)) ** 2
        except:
            sum=999        
    return sum**0.5*1.0/len(x)

def ger_power_var(result):
    result['w4']=result['wifi_infos'].map(get_wifi_power)
    wifi_shop_info['w']=wifi_shop_info['wifi_id']+':'+wifi_shop_info['ave_power'].astype('str')
    t1=wifi_shop_info[['shop_id','w']]
    t2 = t1.groupby('shop_id')['w'].agg(lambda x:'|'.join(x)).reset_index()
    t2['w']=t2['w'].map(get_shop_wifi_dic)    
    result = pd.merge(result,t2,on = ['shop_id'],how = 'left')
    result['knn_values'] = map(lambda x, y: get_knn(x, y) , result['w4'], result['w'])
    del result['w4']
    del result['w']
    return result
    
#shop_id和当前信号最强的wifi以及第二强的wifi有没有互联记录
def if_wifi_shop_connected(result):
    global wifi_shop_connect_only
    wifi_shop_connect_only.rename(columns={'wifi_id':'wifi1_id','connect':'connect1'},inplace=True)
    result=pd.merge(result,wifi_shop_connect_only,on=['wifi1_id','shop_id'],how='left')
    wifi_shop_connect_only.rename(columns={'wifi1_id':'wifi2_id','connect1':'connect2'},inplace=True)
    result=pd.merge(result,wifi_shop_connect_only,on=['wifi2_id','shop_id'],how='left')
    wifi_shop_connect_only.rename(columns={'wifi2_id':'wifi_id','connect2':'connect'},inplace=True)
    result['connect1']=result['connect1'].fillna(0)
    result['connect2']=result['connect2'].fillna(0)
    result['connect_sum']=result['connect1']+result['connect2']
    return result

In [10]:
wifi_shop_info = get_wifi_shop_info(train)
wifi_shop_info.shape
wifi_shop_info.head()

(948314, 3)

     shop_id     wifi_id  ave_power
0  s_1000261  b_10224605 -63.000000
1  s_1000261  b_13587831 -67.833333
2  s_1000261  b_13587832 -71.000000
3  s_1000261  b_13587833 -79.000000
4  s_1000261  b_13587835 -65.800000

In [9]:
def get_train_fullorder(x):
    return int(x/5)

def get_test_fullorder(x):
    return int(x/9 + 1138015)

def get_full_fullorder(x):
    if x.flag != -1:
        return int(x.full_order/5)
    else:
        return int((x.full_order - 5690075)/9 + 1138015)

def get_count_percent(x):
    if x == 0:
        return 0
    else:
        return 100 / x
    
def get_wifi_strength_diff1(x):
    if x.strength1 == -113:
        return 113
    else:
        return abs(x.wifi1_power - x.strength1)
    
def get_wifi_strength_diff2(x):
    if x.strength2 == -113:
        return 113
    else:
        return abs(x.wifi2_power - x.strength2)

In [11]:
wifi_shop_connect1=wifi_shop_connect(train)
wifi_shop_connect_only=wifi_shop_connect1.drop_duplicates()

In [7]:
full_data = pd.read_csv('./output/full_data_neg_shop5_newfeature.csv')
mall_ids = set(full_data.mall_id)

In [34]:
temp = full_data[(full_data.flag == 1)][['shop_id', 'longitude_y', 'latitude_y']].groupby(['shop_id'], as_index=False).agg({'longitude_y':'mean', 'latitude_y':'mean'})
temp.columns = ['shop_id', 'real_latitude_y', 'real_longitude_y']

full_data = full_data.merge(temp, on=['shop_id'], how='left')
full_data['real_lat_diff'] = abs(full_data.latitude_x - full_data.real_latitude_y)
full_data['real_lon_diff'] = abs(full_data.longitude_x - full_data.real_longitude_y)
del temp

In [36]:
def is_weekend(x):
    if (x == 6) | (x == 0):
        return 1
    else:
        return 0

full_data['is_weekend'] = full_data.time_week.apply(is_weekend)
full_data['real_dis'] = 1000000 * (full_data.real_lat_diff**2 + full_data.real_lon_diff**2)

In [39]:
%%time
def scaleDis(x):
    if(x.flag != -1):
        maxT = max(full_data.real_dis[x.name - x.name%5 : x.name - x.name%5 + 5])
        minT = min(full_data.real_dis[x.name - x.name%5 : x.name - x.name%5 + 5])
        return (x.real_dis - minT)/(maxT - minT)
    else:
        maxT = max(full_data.real_dis[x.name - x.name%9 : x.name - x.name%9 + 9])
        minT = min(full_data.real_dis[x.name - x.name%9 : x.name - x.name%9 + 9])
        return (x.real_dis - minT)/(maxT - minT)
    
full_data.real_dis = full_data.apply(scaleDis, axis=1)

CPU times: user 1h 18min 58s, sys: 1min 6s, total: 1h 20min 5s
Wall time: 1h 25min 58s

In [16]:
%%time
full_data.full_order = full_data.index
full_data.full_order = full_data.apply(get_full_fullorder, axis=1)
full_data = full_data.merge(full_data_wifi_infos, on=['full_order'], how='left')

CPU times: user 11min 46s, sys: 13.6 s, total: 12min
Wall time: 21min 48s

In [17]:
full_data = full_data.merge(wifi_connected, left_on='full_order', right_on='full_order', how='left')
full_data = full_data.merge(shop, on=['shop_id'], how='left')

full_data = get_wifi(full_data)

In [19]:
wifi_shop_connect_only.rename(columns={'wifi_id':'wifi1_id','connect':'connect1'},inplace=True)
full_data=full_data.merge(wifi_shop_connect_only,on=['wifi1_id','shop_id'],how='left')

wifi_shop_connect_only.rename(columns={'wifi1_id':'wifi2_id','connect1':'connect2'},inplace=True)
full_data=full_data.merge(wifi_shop_connect_only,on=['wifi2_id','shop_id'],how='left')

wifi_shop_connect_only.rename(columns={'wifi2_id':'wifi_id','connect2':'connect'},inplace=True)

full_data['connect1']=full_data['connect1'].fillna(0)
full_data['connect2']=full_data['connect2'].fillna(0)
full_data['connect_sum']=full_data['connect1']+full_data['connect2']

/usr/local/miniconda2/envs/py35/lib/python3.5/site-packages/pandas/core/frame.py:2844: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)

In [13]:
%%time
# shop_wifi_only_connect.rename(columns={'wifi_id':'wifi1_id','connect':'connect1'},inplace=True)
# full_data = full_data.merge(shop_wifi_only_connect, on=['shop_id', 'wifi1_id'],how='left')
# full_data.rename(columns={'strength':'count1', 'count':'strength1'}, inplace=True)
# full_data['strength1'] = full_data['strength1'].fillna(-113)
# full_data['count1'] = full_data['count1'].fillna(0)
# full_data['count1'] = full_data['count1'].apply(get_count_percent)

# shop_wifi_only_connect.rename(columns={'wifi1_id':'wifi2_id','connect1':'connect2'},inplace=True)
# full_data = full_data.merge(shop_wifi_only_connect,on=['wifi2_id','shop_id'],how='left')
# full_data.rename(columns={'strength':'count2', 'count':'strength2'}, inplace=True)
# full_data['strength2'] = full_data['strength2'].fillna(-113)
# full_data['count2'] = full_data['count2'].fillna(0)
# full_data['count2'] = full_data['count2'].apply(get_count_percent)

# shop_wifi_only_connect.rename(columns={'wifi2_id':'wifi_id','connect2':'connect'},inplace=True)

full_data['strength1_diff'] = full_data.apply(get_wifi_strength_diff1, axis=1)
full_data['strength2_diff'] = full_data.apply(get_wifi_strength_diff2, axis=1)

CPU times: user 8min 7s, sys: 9.18 s, total: 8min 17s
Wall time: 8min 17s

In [8]:
shop = pd.read_csv('../input/训练数据-ccf_first_round_shop_info.csv')
shop = shop[['shop_id', 'category_id', 'price']]

train = pd.read_csv('../input/训练数据-ccf_first_round_user_shop_behavior.csv')
train.user_id = train.user_id.apply(lambda x : int(x[2:]))
train['full_order'] = train.index
train = train.merge(shop, on=['shop_id'], how='left')

In [9]:
user_shop_count = train.groupby(['user_id','shop_id'], as_index=False)['shop_id'].agg({'user_shop_count' : 'count'})
user_category_count = train.groupby(['user_id', 'category_id'], as_index=False)['category_id'].agg({'user_category_count' : 'count'})

full_data = full_data.merge(user_shop_count, on=['user_id', 'shop_id'], how='left')
full_data = full_data.merge(user_category_count, on=['user_id', 'category_id'], how='left')

full_data.user_shop_count = full_data.user_shop_count.fillna(0.0)
full_data.user_category_count = full_data.user_category_count.fillna(0.0)

In [41]:
full_data.to_csv('./output/full_data_neg_shop5_newfeature.csv', index=False)

In [8]:
full_data.shape
full_data.head()

(10045454, 41)

,user_id,mall_id,longitude_x,latitude_x,shop_id,flag,time_hour,time_week,full_order,longitude_y,latitude_y,distance,wifi_infos,bssid,category_id,price,wifi1,wifi2,wifi1_id,wifi1_power,wifi2_id,wifi2_power,ave_power1,power_dif1,ave_power2,power_dif2,connect1,connect2,connect_sum,count1,strength1,count2,strength2,strength1_diff,strength2_diff,real_latitude_y,real_longitude_y,real_lat_diff,real_lon_diff,is_weekend,real_dis
0,11838,m_8379,122.177725,38.427641,s_3236609,1,15,3,0,122.177906,38.428193,0.421046,b_6396480|-67|false;b_41124514|-86|false;b_287...,NaN,c_38,55,"('b_5857369', -55)","('b_6396479', -55)",b_5857369,-55,b_6396479,-55,-111.0,56.0,-111.0,56.0,0.0,0.0,0.0,0.0,-113.0,0.0,-113.0,113.0,113.0,38.428193,122.177906,0.000552,0.000181,0,0.190202
1,11838,m_8379,122.177725,38.427641,s_3853881,0,15,3,0,122.177631,38.427646,0.000000,b_6396480|-67|false;b_41124514|-86|false;b_287...,NaN,c_39,57,"('b_5857369', -55)","('b_6396479', -55)",b_5857369,-55,b_6396479,-55,-111.0,56.0,-111.0,56.0,0.0,0.0,0.0,0.0,-113.0,0.0,-113.0,113.0,113.0,38.427646,122.177631,0.000005,0.000094,0,0.000000
2,11838,m_8379,122.177725,38.427641,s_485436,0,15,3,0,122.177572,38.427088,0.417583,b_6396480|-67|false;b_41124514|-86|false;b_287...,NaN,c_49,44,"('b_5857369', -55)","('b_6396479', -55)",b_5857369,-55,b_6396479,-55,-111.0,56.0,-111.0,56.0,0.0,0.0,0.0,0.0,-113.0,0.0,-113.0,113.0,113.0,38.427088,122.177572,0.000553,0.000153,0,0.185428
3,11838,m_8379,122.177725,38.427641,s_3947040,0,15,3,0,122.178316,38.428533,0.790291,b_6396480|-67|false;b_41124514|-86|false;b_287...,NaN,c_38,41,"('b_5857369', -55)","('b_6396479', -55)",b_5857369,-55,b_6396479,-55,-111.0,56.0,-111.0,56.0,0.0,0.0,0.0,0.0,-113.0,0.0,-113.0,113.0,113.0,38.428533,122.178316,0.000892,0.000591,0,0.657585
4,11838,m_8379,122.177725,38.427641,s_882862,0,15,3,0,122.178386,38.428781,1.000000,b_6396480|-67|false;b_41124514|-86|false;b_287...,NaN,c_49,57,"('b_5857369', -55)","('b_6396479', -55)",b_5857369,-55,b_6396479,-55,-111.0,56.0,-111.0,56.0,0.0,0.0,0.0,0.0,-113.0,0.0,-113.0,113.0,113.0,38.428781,122.178386,0.001140,0.000661,0,1.000000

In [9]:
# full_data = full_data.drop(['distance'], axis=1)

train = full_data[full_data.flag != -1]
test = full_data[full_data.flag == -1]

# train.full_order = train.full_order.apply(get_train_fullorder)
# test.full_order = test.full_order.apply(get_test_fullorder)

del full_data

train.shape
train.head()
test.shape
test.head()

(5690075, 41)

,user_id,mall_id,longitude_x,latitude_x,shop_id,flag,time_hour,time_week,full_order,longitude_y,latitude_y,distance,wifi_infos,bssid,category_id,price,wifi1,wifi2,wifi1_id,wifi1_power,wifi2_id,wifi2_power,ave_power1,power_dif1,ave_power2,power_dif2,connect1,connect2,connect_sum,count1,strength1,count2,strength2,strength1_diff,strength2_diff,real_latitude_y,real_longitude_y,real_lat_diff,real_lon_diff,is_weekend,real_dis
0,11838,m_8379,122.177725,38.427641,s_3236609,1,15,3,0,122.177906,38.428193,0.421046,b_6396480|-67|false;b_41124514|-86|false;b_287...,NaN,c_38,55,"('b_5857369', -55)","('b_6396479', -55)",b_5857369,-55,b_6396479,-55,-111.0,56.0,-111.0,56.0,0.0,0.0,0.0,0.0,-113.0,0.0,-113.0,113.0,113.0,38.428193,122.177906,0.000552,0.000181,0,0.190202
1,11838,m_8379,122.177725,38.427641,s_3853881,0,15,3,0,122.177631,38.427646,0.000000,b_6396480|-67|false;b_41124514|-86|false;b_287...,NaN,c_39,57,"('b_5857369', -55)","('b_6396479', -55)",b_5857369,-55,b_6396479,-55,-111.0,56.0,-111.0,56.0,0.0,0.0,0.0,0.0,-113.0,0.0,-113.0,113.0,113.0,38.427646,122.177631,0.000005,0.000094,0,0.000000
2,11838,m_8379,122.177725,38.427641,s_485436,0,15,3,0,122.177572,38.427088,0.417583,b_6396480|-67|false;b_41124514|-86|false;b_287...,NaN,c_49,44,"('b_5857369', -55)","('b_6396479', -55)",b_5857369,-55,b_6396479,-55,-111.0,56.0,-111.0,56.0,0.0,0.0,0.0,0.0,-113.0,0.0,-113.0,113.0,113.0,38.427088,122.177572,0.000553,0.000153,0,0.185428
3,11838,m_8379,122.177725,38.427641,s_3947040,0,15,3,0,122.178316,38.428533,0.790291,b_6396480|-67|false;b_41124514|-86|false;b_287...,NaN,c_38,41,"('b_5857369', -55)","('b_6396479', -55)",b_5857369,-55,b_6396479,-55,-111.0,56.0,-111.0,56.0,0.0,0.0,0.0,0.0,-113.0,0.0,-113.0,113.0,113.0,38.428533,122.178316,0.000892,0.000591,0,0.657585
4,11838,m_8379,122.177725,38.427641,s_882862,0,15,3,0,122.178386,38.428781,1.000000,b_6396480|-67|false;b_41124514|-86|false;b_287...,NaN,c_49,57,"('b_5857369', -55)","('b_6396479', -55)",b_5857369,-55,b_6396479,-55,-111.0,56.0,-111.0,56.0,0.0,0.0,0.0,0.0,-113.0,0.0,-113.0,113.0,113.0,38.428781,122.178386,0.001140,0.000661,0,1.000000

(4355379, 41)

,user_id,mall_id,longitude_x,latitude_x,shop_id,flag,time_hour,time_week,full_order,longitude_y,latitude_y,distance,wifi_infos,bssid,category_id,price,wifi1,wifi2,wifi1_id,wifi1_power,wifi2_id,wifi2_power,ave_power1,power_dif1,ave_power2,power_dif2,connect1,connect2,connect_sum,count1,strength1,count2,strength2,strength1_diff,strength2_diff,real_latitude_y,real_longitude_y,real_lat_diff,real_lon_diff,is_weekend,real_dis
5690075,30097142,m_3916,122.141011,39.818847,s_3683488,-1,13,1,1138015,122.140708,39.819073,0.040208,b_34366982|-82|false;b_37756289|-53|false;b_41...,NaN,c_25,45,"('b_37756289', -53)","('b_32418144', -55)",b_37756289,-53,b_32418144,-55,-54.596154,1.596154,-46.118644,8.881356,0.0,0.0,0.0,1.923077,-54.596154,1.694915,-46.118644,1.596154,8.881356,39.819073,122.140708,0.000226,0.000303,0,0.009152
5690076,30097142,m_3916,122.141011,39.818847,s_147921,-1,13,1,1138015,122.141208,39.818696,0.000000,b_34366982|-82|false;b_37756289|-53|false;b_41...,NaN,c_30,48,"('b_37756289', -53)","('b_32418144', -55)",b_37756289,-53,b_32418144,-55,-55.725424,2.725424,-53.325513,1.674487,1.0,0.0,1.0,0.338983,-55.725424,0.293255,-53.325513,2.725424,1.674487,39.818696,122.141208,0.000151,0.000197,0,0.000044
5690077,30097142,m_3916,122.141011,39.818847,s_312218,-1,13,1,1138015,122.140651,39.819060,0.049160,b_34366982|-82|false;b_37756289|-53|false;b_41...,NaN,c_28,34,"('b_37756289', -53)","('b_32418144', -55)",b_37756289,-53,b_32418144,-55,-56.875000,3.875000,-63.836478,8.836478,1.0,0.0,1.0,0.694444,-56.875000,0.628931,-63.836478,3.875000,8.836478,39.819060,122.140651,0.000213,0.000360,0,0.012747
5690078,30097142,m_3916,122.141011,39.818847,s_10425,-1,13,1,1138015,122.140955,39.819088,0.011282,b_34366982|-82|false;b_37756289|-53|false;b_41...,NaN,c_29,50,"('b_37756289', -53)","('b_32418144', -55)",b_37756289,-53,b_32418144,-55,-76.824176,23.824176,-76.101322,21.101322,1.0,0.0,1.0,0.549451,-76.824176,0.440529,-76.101322,23.824176,21.101322,39.819088,122.140955,0.000241,0.000056,0,0.000000
5690079,30097142,m_3916,122.141011,39.818847,s_3997599,-1,13,1,1138015,122.140818,39.819379,0.395798,b_34366982|-82|false;b_37756289|-53|false;b_41...,NaN,c_28,43,"('b_37756289', -53)","('b_32418144', -55)",b_37756289,-53,b_32418144,-55,-84.857143,31.857143,-78.927273,23.927273,0.0,0.0,0.0,14.285714,-84.857143,1.818182,-78.927273,31.857143,23.927273,39.819379,122.140818,0.000532,0.000193,0,0.203941

In [11]:
def mall_wifi_dateframe(mall_id, path):
    cols = pickle.load(open('../cjy/input/'+path+'/'+mall_id+'_cols.p','rb'))
    coo = pickle.load(open('../cjy/input/'+path+'/'+mall_id+'.p','rb'))
    coo = coo.tocoo(copy=False)
    coo_group = pd.DataFrame({'row': coo.row, 'col': coo.col, 'data': coo.data}
                 )[['row', 'col', 'data']].sort_values(['row', 'col']
                 ).reset_index(drop=True).groupby('col')
    df = pd.DataFrame(-113 * np.ones((max(coo.row)+1, len(cols))), columns=cols, dtype=np.int64)
    tmp = coo_group.apply(lambda x:x.row.values)
    for col,rows,values in zip(tmp.index.tolist(),tmp.values,
                                coo_group.apply(lambda x:x.data.tolist())):
        df.iloc[rows,col]=values
    return df

In [12]:
import os  
  
finish_mall = []
finish_mall = os.listdir('./model_negShop/')
finish_mall.remove('.ipynb_checkpoints')
finish_mall.remove('result')
# finish_mall.remove('temp')
for i in range(len(finish_mall)):
    finish_mall[i] = finish_mall[i][:-2]
finish_mall

# finish_shop = []
# finish_shop = os.listdir('./output/new_feature_shop/')
# # finish_shop.remove('.ipynb_checkpoints')
# # finish_shop.remove('result')
# # finish_mall.remove('temp')
# for i in range(len(finish_shop)):
#     finish_shop[i] = finish_shop[i][:-2]
# finish_shop

['m_1293',
 'm_1263',
 'm_4495',
 'm_622',
 'm_3313',
 'm_2907',
 'm_909',
 'm_6803',
 'm_2270',
 'm_8379',
 'm_5076',
 'm_1375',
 'm_3425',
 'm_2878',
 'm_822',
 'm_1089',
 'm_625',
 'm_3916',
 'm_1621',
 'm_979',
 'm_4543',
 'm_4341',
 'm_690',
 'm_7168',
 'm_5154',
 'm_1021',
 'm_2058',
 'm_3019',
 'm_1920',
 'm_9054',
 'm_5085',
 'm_6167',
 'm_4094',
 'm_9068',
 'm_4079',
 'm_4828',
 'm_1831',
 'm_3005',
 'm_4121',
 'm_3501',
 'm_2578',
 'm_3871',
 'm_2267',
 'm_5352',
 'm_4011',
 'm_3739',
 'm_2715',
 'm_7800',
 'm_2182',
 'm_8344',
 'm_2333',
 'm_4759',
 'm_6337',
 'm_2467',
 'm_623',
 'm_5529',
 'm_615',
 'm_626',
 'm_4168',
 'm_4572',
 'm_4033',
 'm_6587',
 'm_5810',
 'm_4459',
 'm_968',
 'm_3839',
 'm_3517',
 'm_4406',
 'm_5892',
 'm_2224',
 'm_7601',
 'm_4923',
 'm_5767',
 'm_1950',
 'm_1085',
 'm_3832',
 'm_7973',
 'm_2123',
 'm_5825',
 'm_3445',
 'm_4515',
 'm_2415',
 'm_8093',
 'm_4187',
 'm_1175',
 'm_1409',
 'm_7523',
 'm_4548',
 'm_3112',
 'm_7374',
 'm_4422',
 'm_1790',
 'm_1377',
 'm_7994',
 'm_3054',
 'm_2009',
 'm_3528']

In [14]:
len(finish_mall)

0

In [13]:
finish_mall = ['m_6167', 'm_4011', 'm_623', 'm_4572', 'm_4548', 'm_4187', 'm_1831', 'm_2878', 'm_7800']

In [21]:
def crt_wifi_weight(x):
    shop_id = train[train.full_order == 26].shop_id[train[train.full_order == 26].shop_id.index[0]]
    print(shop_id)
    if(len(crt_mall_true_wifi[crt_mall_true_wifi.shop_id == shop_id].true_wifi_and_cnt[0]) > 9):
        temp_dict = ast.literal_eval(crt_mall_true_wifi[crt_mall_true_wifi.shop_id == shop_id].true_wifi_and_cnt[0][8 : -1])
        count = 0
        for key, value in temp_dict:
            if key in many_wifi:
                if m1.loc[x.name, key] != -113:
                    count = count + temp_dict['key']
            print(count)
    else:
        return 0

In [117]:
crt_mall_true_wifi = pd.read_csv('../cjy/input/mall_true_wifi/m_622.csv')

crt_mall_true_wifi.shape
crt_mall_true_wifi.head()

(83, 4)

,shop_id,true_wifi_size,true_wifi_and_cnt,true_wifi_uni_size
0,s_1074181,10,"Counter({'b_28212937': 2, 'b_21638502': 2, 'b_...",7
1,s_1145103,12,Counter({'b_40947031': 12}),1
2,s_1298092,4,"Counter({'b_37867647': 2, 'b_56528587': 1, 'b_...",3
3,s_147427,9,"Counter({'b_28065378': 6, 'b_43444473': 1, 'b_...",4
4,s_173803,71,"Counter({'b_50072170': 66, 'b_619945': 2, 'b_3...",4

In [124]:
ast.literal_eval(crt_mall_true_wifi[crt_mall_true_wifi.shop_id == 's_1074181'].true_wifi_and_cnt[0][8 : -1])
len('Counter()')

{'b_21638502': 2,
 'b_2435182': 1,
 'b_28065378': 2,
 'b_28212937': 2,
 'b_3108477': 1,
 'b_55701925': 1,
 'b_56327963': 1}

9

In [30]:
gbm = xgb.XGBClassifier(
    learning_rate =0.1,
    n_estimators=1500,
    max_depth=7,
    min_child_weight=1.1,
    gamma=0.1,
    reg_alpha=0.05,
    reg_lambda=15,
    subsample=0.8,
    colsample_bytree=0.886,
    objective= 'binary:logistic',
    nthread=-1,
    scale_pos_weight=4,
    silent=1,
    seed=0)

In [29]:
predict = ['mall_id', 'longitude_x', 'latitude_x', 'shop_id', 'flag',
        'time_hour', 'time_week',
        'distance', 'bssid','ave_power1', 'power_dif1', 
        'ave_power2', 'power_dif2', 'connect1','connect2', 
        'count1', 'strength1', 'count2', 'strength2', 'strength1_diff', 
        'strength2_diff', 'real_longitude_y', 'real_latitude_y','real_dis']

In [15]:
finish_mall.remove('m_7800')

In [ ]:
acc = pd.DataFrame()
for mall_id in tqdm(mall_ids):
    if mall_id not in finish_mall:
        acc_temp = {}
        train_new = []
        m_train = train[train.mall_id == mall_id].copy()
        m_test = test[test.mall_id == mall_id].copy()
        m_full = pd.concat([m_train, m_test])
        m_full.reset_index(drop=True, inplace=True)
        m_full = m_full[predict]
        del m_train
        del m_test

        # wifi onehot
        m1 = mall_wifi_dateframe(mall_id, 'train_matrix')
        m2 = mall_wifi_dateframe(mall_id, 'test_matrix')
        m1 = m1.drop(['full_order'], axis=1)
        m2 = m2.drop(['full_order'], axis=1)
        
#         shop_id onehot
        shop = pd.get_dummies(m_full.shop_id)
        m_full = m_full.drop(['shop_id'], axis=1)
        m_full = pd.concat([m_full, shop], axis=1)
        del shop
#         category = pd.get_dummies(m_full.category_id)
#         m_full = m_full.drop(['category_id'], axis=1)
#         m_full = pd.concat([m_full, category], axis=1)
#         del category
        bssid = pd.get_dummies(m_full.bssid)
        m_full = m_full.drop(['bssid'], axis=1)
        m_full = pd.concat([m_full, bssid], axis=1)
        del bssid
        
        m_train = m_full[m_full.flag != -1]
        m_test = m_full[m_full.flag == -1]
        m_train = m_train.drop(['mall_id'], axis=1)
        m_test = m_test.drop(['mall_id'], axis=1)
        y_temp = m_train.flag
        m_train = m_train.drop(['flag'], axis=1)
        m_test = m_test.drop(['flag'], axis=1)
        m_train = m_train.as_matrix()
        m_test = m_test.as_matrix()
        del m_full

        wifi_spc = list(set(many_wifi).intersection(set(m1.columns)))
        m1 = m1[wifi_spc]
        m2 = m2[wifi_spc]
        m1 = m1.as_matrix()
        m2 = m2.as_matrix()
        m_train_new = []
        m_test_new = []
        
        for i in range(len(m1)):
            m_train_new.append(m1[i].tolist())
            m_train_new.append(m1[i].tolist())
            m_train_new.append(m1[i].tolist())
            m_train_new.append(m1[i].tolist())
            m_train_new.append(m1[i].tolist())
#         for i in range(len(m2)):
#             m_test_new.append(m2[i].tolist())
#             m_test_new.append(m2[i].tolist())
#             m_test_new.append(m2[i].tolist())
#             m_test_new.append(m2[i].tolist())
#             m_test_new.append(m2[i].tolist())
#             m_test_new.append(m2[i].tolist())
#             m_test_new.append(m2[i].tolist())
#             m_test_new.append(m2[i].tolist())
#             m_test_new.append(m2[i].tolist())
        del m1
        del m2
        m_trian_nn = np.hstack((m_train.tolist(), m_train_new))
#         m_test_nn = np.hstack((m_test.tolist(), m_test_new))
        del m_train
        del m_test
        del m_train_new
        del m_test_new
        x_train = m_trian_nn
        y_train = y_temp.tolist()
#         x_test = m_test_nn
        del m_trian_nn
#         del m_test_nn
        
        acc_temp['num'] = len(y_train)
        x_train_1 = x_train[:-5000]
        y_train_1 = y_train[:-5000]
        x_train_2 = x_train[-5000:]
        y_train_2 = y_train[-5000:]
        del x_train
        del y_train

        gbm.fit(x_train_1, y_train_1)
        del x_train_1
        del y_train_1
        
        y_pred_proba = gbm.predict_proba(x_train_2)
        y_pred_proba = pd.DataFrame(y_pred_proba)
        y_max = []
        for i in range(y_pred_proba.shape[0]):
            if i % 5 == 0:
                temp = y_pred_proba.loc[i : i + 4, 1].sort_values(ascending=False)
                y_max.append(temp.index[0])
            else:
                y_max.append(0)
        y_max = pd.Series(y_max)
        acc_temp['mall_id'] = mall_id
        acc_temp['acc'] = 1 - len(y_max[y_max % 5 != 0])/(1000)
        acc = acc.append(pd.DataFrame(acc_temp, index=[0]))
        
#         y_pred_proba = []
#         y_pred_proba = gbm.predict_proba(x_test)
#         y_pred_proba = pd.DataFrame(y_pred_proba)

        print(str(mall_id) + ':' + str(acc_temp['acc']) + '/' + str(acc_temp['num']))
#         finish_mall.append(mall_id)
#         pickle.dump(pd.DataFrame(y_pred_proba), open('./model_negShop/' + str(mall_id) + '.p', 'wb'), protocol=4)

  0%|          | 0/97 [00:00<?, ?it/s]

In [ ]:
acc 0.78

predict = ['mall_id', 'longitude_x', 'latitude_x', 'shop_id', 'flag',
        'time_hour', 'is_weekend',
        'distance', 'bssid','ave_power1', 'power_dif1', 
        'ave_power2', 'power_dif2', 'connect1','connect2', 
        'count1', 'strength1', 'count2', 'strength2', 'strength1_diff', 
        'strength2_diff', 'real_dis']

In [ ]:
acc 0.779

predict = ['mall_id', 'longitude_x', 'latitude_x', 'shop_id', 'flag',
        'time_hour', 'is_weekend', 'longitude_y', 'latitude_y',
        'distance', 'bssid','ave_power1', 'power_dif1', 
        'ave_power2', 'power_dif2', 'connect1','connect2', 
        'count1', 'strength1', 'count2', 'strength2', 'strength1_diff', 
        'strength2_diff', 'real_longitude_y', 'real_latitude_y', 'real_dis']

In [ ]:
acc 0.783

predict = ['mall_id', 'longitude_x', 'latitude_x', 'shop_id', 'flag',
        'time_hour',
        'distance', 'bssid','ave_power1', 'power_dif1', 
        'ave_power2', 'power_dif2', 'connect1','connect2', 
        'count1', 'strength1', 'count2', 'strength2', 'strength1_diff', 
        'strength2_diff', 'real_longitude_y', 'real_latitude_y', 'real_dis']

In [225]:
acc.to_csv('./output/acc/acc_xgb1500_newfeature.csv', index=False)

In [56]:
acc = pd.read_csv('./output/acc/acc_xgb1000_latlng2_dis.csv')

acc[acc.mall_id == mall_id]

acc.reset_index(drop=True, inplace=True)
acc.shape
acc.head()

      acc mall_id    num
53  0.967  m_4011  32460

(97, 3)

     acc mall_id    num
0  0.931  m_6587  62385
1  0.958  m_8093  46280
2  0.976  m_5154  37940
3  0.949  m_5352  51890
4  0.960  m_4759  31445

In [19]:
acc.acc.mean()
# acc_xgb1000_latlng1 0.9221855670103094
# acc_xgb1000_latlng2_dis 0.9230721649484543

0.8932222222222221

In [26]:
gbm.get_xgb_params

<bound method XGBModel.get_xgb_params of XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.886,
       gamma=0.1, learning_rate=0.1, max_delta_step=0, max_depth=7,
       min_child_weight=1.1, missing=None, n_estimators=1200, nthread=-1,
       objective='binary:logistic', reg_alpha=0.05, reg_lambda=7,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)>

In [33]:
acc

     acc mall_id    num
0  0.782  m_7800  98660

In [48]:
acc
0	0.884	m_2878	51625
0	0.959	m_1831	49520
0	0.941	m_4548	26405
0	0.798	m_7800	98660
0	0.844	m_4187	47600
0	0.928	m_4572	46855
0	0.816	m_6167	26790
0	0.965	m_4011	32460
0	0.967	m_623	31160

XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.886,
       gamma=0.1, learning_rate=0.1, max_delta_step=0, max_depth=7,
       min_child_weight=1.1, missing=None, n_estimators=1200, nthread=-1,
       objective='binary:logistic', reg_alpha=0.05, reg_lambda=10,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)

In [43]:
acc
0	0.888	m_2878	51625
0	0.965	m_1831	49520
0	0.938	m_4548	26405
0	0.797	m_7800	98660
0	0.849	m_4187	47600
0	0.926	m_4572	46855
0	0.813	m_6167	26790
0	0.963	m_4011	32460
0	0.966	m_623	31160

XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.886,
       gamma=0.1, learning_rate=0.1, max_delta_step=0, max_depth=7,
       min_child_weight=1.1, missing=None, n_estimators=1200, nthread=-1,
       objective='binary:logistic', reg_alpha=0.05, reg_lambda=7,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)

In [66]:
acc
0	0.827	m_6167	26790
0	0.846	m_4187	47600
0	0.961	m_623	31160
0	0.924	m_4572	46855
0	0.947	m_4548	26405
0	0.773	m_7800	98660
0	0.963	m_1831	49520
0	0.963	m_4011	32460
0	0.883	m_2878	51625

XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.886,
       gamma=0.1, learning_rate=0.1, max_delta_step=0, max_depth=7,
       min_child_weight=1.1, missing=None, n_estimators=1000, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=3,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)

In [54]:
acc
0	0.824	m_6167	26790
0	0.840	m_4187	47600
0	0.967	m_623	31160
0	0.925	m_4572	46855
0	0.946	m_4548	26405
0	0.774	m_7800	98660
0	0.962	m_1831	49520
0	0.964	m_4011	32460
0	0.886	m_2878	51625

XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.886,
       gamma=0.1, learning_rate=0.1, max_delta_step=0, max_depth=7,
       min_child_weight=1.1, missing=None, n_estimators=1000, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)

In [34]:
acc
0	0.818	m_6167	26790
0	0.833	m_4187	47600
0	0.962	m_623	31160
0	0.917	m_4572	46855
0	0.947	m_4548	26405
0	0.758	m_7800	98660
0	0.962	m_1831	49520
0	0.962	m_4011	32460
0	0.868	m_2878	51625

XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.75,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=1000, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)

In [44]:
acc
0	0.812	m_6167	26790
0	0.830	m_4187	47600
0	0.966	m_623	31160
0	0.921	m_4572	46855
0	0.944	m_4548	26405
0	0.764	m_7800	98660
0	0.963	m_1831	49520
0	0.964	m_4011	32460
0	0.872	m_2878	51625

In [27]:
acc
0	0.826	m_4187	47600
0	0.880	m_2878	51625
0	0.944	m_4548	26405
0	0.969	m_623	31160
0	0.959	m_1831	49520
0	0.819	m_6167	26790
0	0.966	m_4011	32460
0	0.915	m_4572	46855
0	0.764	m_7800	98660

# wifi>85, 200>bssid>100,shop_id, category_id, 2*经纬度, 1:4, scale_pos_weight=4

In [112]:
acc
0	0.948	m_4548	26405
0	0.967	m_623	31160
0	0.964	m_4011	32460
0	0.820	m_6167	26790
0	0.914	m_4572	46855
0	0.877	m_2878	51625
0	0.959	m_1831	49520
0	0.837	m_4187	47600
0	0.763	m_7800	98660

# wifi>85, bssid>100,shop_id, category_id, 2*经纬度, 1:4, scale_pos_weight=4

In [19]:
acc
0	0.962	m_1831	49520
0	0.826	m_4187	47600
0	0.829	m_6167	26790
0	0.762	m_7800	98660
0	0.923	m_4572	46855
0	0.965	m_623	31160
0	0.972	m_4011	32460
0	0.947	m_4548	26405
0	0.882	m_2878	51625

# shop_id, bssid, 2*经纬度, 1:4, scale_pos_weight=8

In [ ]:
XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.75,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=1000, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)
m_7800:0.76
m_2878:0.885
m_623:0.963
m_4548:0.943
m_6167:0.808
m_4011:0.968
m_4187:0.8220000000000001
m_4572:0.918
m_1831:0.961
    
wifi>85 2个经纬度+distance

In [69]:
acc
mall_id	num
0	0.964	m_4011	58428
0	0.796	m_6167	48222
0	0.914	m_4572	84339
0	0.959	m_623	56088
0	0.950	m_1831	89136
0	0.940	m_4548	47529
0	0.861	m_2878	92925
0	0.784	m_4187	85680
0	0.722	m_7800	177588

# shop_id,bssid,time_week,1:8

In [75]:
acc
acc	mall_id	num
0	0.965	m_4011	58428
0	0.772	m_6167	48222
0	0.900	m_4572	84339
0	0.962	m_623	56088
0	0.954	m_1831	89136
0	0.940	m_4548	47529
0	0.856	m_2878	92925
0	0.786	m_4187	85680
0	0.725	m_7800	177588

# shop_id,time_week,1:8

In [68]:
acc
mall_id	num
0	0.964	m_4011	58428
0	0.789	m_6167	48222
0	0.911	m_4572	84339
0	0.957	m_623	56088
0	0.956	m_1831	89136
0	0.940	m_4548	47529
0	0.862	m_2878	92925
0	0.795	m_4187	85680
0	0.715	m_7800	177588

# shop_id,category_id,bssid,time_week,1:8

In [72]:
acc
acc	mall_id	num
0	0.963	m_4011	58428
0	0.791	m_6167	48222
0	0.919	m_4572	84339
0	0.960	m_623	56088
0	0.954	m_1831	89136
0	0.938	m_4548	47529
0	0.861	m_2878	92925
0	0.795	m_4187	85680
0	0.707	m_7800	177588

# shop_id,bssid,1:8

In [ ]:
XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.75,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=1000, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)
m_6167:0.796
m_4011:0.965
m_623:0.962
m_4572:0.914
m_4548:0.945
m_4187:0.831
m_1831:0.964
m_2878:0.883
m_7800:0.762
    
-113 使用user相同，shop不同负样本
x_train = np.hstack((m_trian_nn[:, 2:4], m_trian_nn[:, 5:7],  m_trian_nn[:, 8:]))
y_train = m_trian_nn[:, 4]

In [ ]:
XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.75,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=1000, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)
m_7800:0.753
m_2878:0.877
m_623:0.966
m_4548:0.949
m_6167:0.8240000000000001
m_4011:0.97
m_4187:0.835
m_4572:0.916
m_1831:0.968
    
wifi>85

In [128]:
XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.75,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=1000, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)
m_6167:0.8029999999999999
m_4011:0.963
m_623:0.961
m_4572:0.904
m_4548:0.9410000000000001
m_4187:0.83
m_7800:0.761
m_1831:0.957

-113 两个经纬度加(0,1)distasnce

In [ ]:
XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.75,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=1000, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)
m_7800:0.748
m_2878:0.878
m_623:0.968
m_4548:0.947
m_6167:0.823
m_4011:0.97
m_4187:0.834
m_4572:0.92
m_1831:0.964
    
wifi>90

In [ ]:
XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.75,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=1000, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)
m_7800:0.755
m_2878:0.88
m_623:0.967
m_4548:0.945
m_6167:0.8240000000000001
m_4011:0.968
m_4187:0.838
m_4572:0.922
m_1831:0.963
    
wifi>80

In [ ]:
XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.75,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=1000, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)
m_7800:0.767
m_2878:0.878
m_623:0.948
m_4548:0.94
m_6167:0.782
m_4011:0.952
m_4187:0.825
m_4572:0.878
m_1831:0.946
    
wifi>150

In [ ]:
XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.75,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=1000, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)
m_7800:0.755
m_2878:0.868
m_623:0.931
m_4548:0.922
m_6167:0.777
m_4011:0.952
m_4187:0.817
m_4572:0.851
m_1831:0.94
    
wifi>200

In [ ]:
XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.75,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=1000, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)
m_6167:0.813
m_4011:0.965
m_623:0.965
m_4572:0.905
m_4548:0.946
m_4187:0.837
m_7800:0.756
m_1831:0.962
m_2878:0.875
    
-113 两个经纬度

In [ ]:
XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.75,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=1000, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)
m_6167:0.776
m_4011:0.956
m_623:0.946
m_4572:0.89
m_4548:0.922
m_4187:0.8029999999999999
m_7800:0.718
m_1831:0.9390000000000001
m_2878:0.858
    
-113 经纬度改为(0,1)的distance

In [ ]:
XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.75,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=1000, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)
m_6167:0.771
m_4011:0.949
m_623:0.949
m_4572:0.87
m_4548:0.885
m_4187:0.808
m_7800:0.728
m_1831:0.925
m_2878:0.856
      
-113 无经纬度

In [ ]:
XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.75,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=1000, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)
m_4011:0.87
m_6167:0.8220000000000001
m_4548:0.848
m_1831:0.897
m_4187:0.677
m_623:0.883
m_4572:0.731

调成-113

In [ ]:
XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.75,
       gamma=0.9, learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=1000, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=4, seed=0, silent=1, subsample=0.8)
m_6167:0.8160000000000001
m_623:0.865
m_2878:0.8109999999999999
m_4011:0.857
m_1831:0.896
m_4548:0.835
m_4187:0.681