In [2]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import time
from tqdm import tqdm

%matplotlib inline

#每次可以输出多个变量
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from pylab import rcParams
rcParams['figure.figsize'] = 14, 6

import warnings
warnings.filterwarnings("ignore")

#中文字体
import matplotlib
matplotlib.use('qt4agg')
#指定默认字体
matplotlib.rcParams['font.sans-serif'] = ['SimHei']
matplotlib.rcParams['font.family'] = 'sans-serif'
#解决负号'-'显示为方块的问题
matplotlib.rcParams['axes.unicode_minus'] = False

In [32]:
df = pd.read_csv('df.txt', sep=' ')
df = df.drop_duplicates()

df.shape
df.head()

(478111, 27)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade
0,108641074714126964,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,4505772604969228686,1,1003,2005,3003,282924576738839389,1537236544,4006,5799347067982556520:-1;509660095530134768:-1;5...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
1,5754713551599725161,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2692638157208937547,0,1002,2005,3006,4007979028023783431,1537243232,4001,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
2,842679481291040981,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,5247924392014515924,0,1003,2005,3004,4884875192608989870,1537211052,4001,5799347067982556520:5131280576272319091;725801...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
3,937088850059189027,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2681414445369714628,1,1004,2005,3006,840119421106178602,1537222670,4016,509660095530134768:-1;5799347067982556520:-1;7...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
4,7975697065017708072,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2729475788342039013,0,1002,2005,3001,1736769971710354684,1537271320,4001,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0

(18371, 26)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description
0,2475218615076601065,2275895163219263378,7908382889764677758;8277336076276184272,2636395404473730413;7515802706813700848;302719...,7838285046767229711,7534238860363577544,7,6,8,14,4379490381248358680,0,1002,2005,3001,2858926263178884522,1537885700,4005,8277336076276184272:-1;5799347067982556520:-1;...,5275548996133547595,13,0.985244,5011,0.964023,0.966550,0.955378
1,398316874173557226,7096238490711246967,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;734498...,8126195666233054089,3948283326616421003,6,9,8,16,2629129219935839101,1,1004,2002,3006,4014843148303402290,1537862843,4001,"5755694407684602296:216555019471416386,2636395...",329470548383752413,14,0.989068,5012,0.963794,0.964225,0.959134
2,6586402638209028583,7096238490711246967,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;734498...,8126195666233054089,3948283326616421003,6,9,8,16,1092007111346257147,0,1004,2002,3004,8141706531104182980,1537858222,4011,5755694407684602296:2636395404473730413;871073...,329470548383752413,14,0.989068,5012,0.963794,0.964225,0.959134
3,1040996105851528465,7096238490711246967,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;734498...,8126195666233054089,3948283326616421003,6,9,8,16,5353289677517820939,1,1003,2002,3007,5878932623083097102,1537860915,4001,8710739180200009128:-1;5755694407684602296:263...,329470548383752413,14,0.989068,5012,0.963794,0.964225,0.959134
4,6316278569655873454,7096238490711246967,7908382889764677758;5755694407684602296,5131280576272319091;2636395404473730413;734498...,8126195666233054089,3948283326616421003,6,9,8,16,1098833840660870025,0,1002,2003,3002,7218739953079190510,1537859074,4001,5755694407684602296:5131280576272319091;871073...,329470548383752413,14,0.989068,5012,0.963794,0.964225,0.959134

In [33]:
test = pd.read_csv('test.txt', sep=' ')

test.shape
test.head()

test['is_trade'] = -1
df = pd.concat([df, test])

In [34]:
#time
def timestamp_datetime(value):
    format = '%Y-%m-%d %H:%M:%S'
    value = time.localtime(value)
    dt = time.strftime(format, value)
    return dt


def convert_data(data):
    data['time'] = data.context_timestamp.apply(timestamp_datetime)
    data['day'] = data.time.apply(lambda x: int(x[8:10]))
    data['hour'] = data.time.apply(lambda x: int(x[11:13]))
    user_query_day = data.groupby(
        ['user_id',
         'day']).size().reset_index().rename(columns={
             0: 'user_query_day'
         })
    data = pd.merge(data, user_query_day, 'left', on=['user_id', 'day'])
    user_query_day_hour = data.groupby(
        ['user_id', 'day',
         'hour']).size().reset_index().rename(columns={
             0: 'user_query_day_hour'
         })
    data = pd.merge(
        data, user_query_day_hour, 'left', on=['user_id', 'day', 'hour'])
    return data


df = convert_data(df)

In [35]:
#shop_score = (star + review_num * review_positive) * service * delivery * description
df.shop_star_level = df.shop_star_level - min(df.shop_star_level)

df['shop_score'] = (
    df.shop_star_level +
    df.shop_review_num_level * df.shop_review_positive_rate
) * df.shop_score_service * df.shop_score_delivery * df.shop_score_description

In [36]:
#item_score = (sales + collected + pv)
#item_score2 = (sales + collected + pv) / price
#item_score3 = ((sales + collected + pv) / price) / (page + 1)

df.context_page_id = df.context_page_id - min(df.context_page_id)

df['item_score'] = (
    df.item_sales_level + df.item_collected_level * df.item_pv_level)
df['item_score2'] = (
    df.item_sales_level + df.item_collected_level * df.item_pv_level
) / df.item_price_level
df['item_score3'] = (
    (df.item_sales_level + df.item_collected_level * df.item_pv_level
     ) / df.item_price_level) / (df.context_page_id + 1)

In [ ]:
# item与predict相似度
def pred_split(x):
    pred = []
    tmp = x.split(';')
    for i in range(0, len(tmp)):
        pred.append(tmp[i].split(':'))
    return pred


def predict_category_split(x):
    pred = []
    for i in range(0, len(x)):
        pred.append(x[i][0])
    return pred


def predict_property_split(x):
    pred = []
    for i in range(0, len(x)):
        for j in range(1, len(x[i])):
            if (x[i][j] != '-1'):
                pred.append(x[i][j])
    return pred


df['predict_category_property_split'] = df.predict_category_property.apply(
    lambda x: pred_split(x))

df['predict_category_split'] = df.predict_category_property_split.apply(
    lambda x: predict_category_split(x))

df['predict_property_split'] = df.predict_category_property_split.apply(
    lambda x: predict_property_split(x))

def item_pred_category_score(x):
    return len(
        list(
            set(x.item_category_split).intersection(
                set(x.predict_category_split))))


def item_pred_property_score(x):
    return len(
        list(
            set(x.item_property_split).intersection(
                set(x.predict_property_split))))


df['item_category_split'] = df.item_category_list.apply(lambda x: x.split(';'))
df['item_property_split'] = df.item_property_list.apply(lambda x: x.split(';'))
df['predict_category_property_split'] = df.predict_category_property.apply(
    lambda x: x.split(';'))
df['item_category_split_count'] = df.item_category_split.apply(
    lambda x: len(x))
df['item_property_split_count'] = df.item_property_split.apply(
    lambda x: len(x))
df['predict_category_property_split_count'] = df.predict_category_split.apply(
    lambda x: len(x))

df['pred_category_split_count'] = df.predict_category_split.apply(
    lambda x: len(x))
df['pred_property_split_count'] = df.predict_property_split.apply(
    lambda x: len(x))

df['item_pred_category_score'] = df.apply(item_pred_category_score, axis=1)
df['item_pred_property_score'] = df.apply(item_pred_property_score, axis=1)

df['item_pred_category_score_item%'] = df.item_pred_category_score / df.item_category_split_count
df['item_pred_property_score_item%'] = df.item_pred_property_score / df.item_property_split_count

df['item_pred_category_score_pred%'] = df.item_pred_category_score / df.pred_category_split_count
df['item_pred_property_score_pred%'] = df.item_pred_property_score / df.pred_property_split_count

In [30]:
df.shape
df.head()

(478111, 52)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,time,day,hour,user_query_day,user_query_day_hour,shop_score,item_score,item_score2,item_score3,predict_category_property_split,predict_category_split,predict_property_split,item_category_split,item_property_split,item_category_split_count,item_property_split_count,predict_category_property_split_count,pred_category_split_count,pred_property_split_count,item_pred_category_score,item_pred_property_score,item_pred_category_score_item%,item_pred_property_score_item%,item_pred_category_score_pred%,item_pred_property_score_pred%
0,108641074714126964,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,4505772604969228686,1,1003,2005,3003,282924576738839389,1537236544,5,5799347067982556520:-1;509660095530134768:-1;5...,6765930309048922341,4,1.0,3,1.0,1.0,1.0,0,2018-09-18 10:09:04,18,10,3,3,7.0,59,19.666667,3.277778,"[5799347067982556520:-1, 509660095530134768:-1...","[5799347067982556520, 509660095530134768, 5755...",[9148482949976129397],"[7908382889764677758, 5799347067982556520]","[2072967855524022579, 5131280576272319091, 263...",2,22,5,5,1,2,0,1.0,0.000000,0.400000,0.000000
1,5754713551599725161,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2692638157208937547,0,1002,2005,3006,4007979028023783431,1537243232,0,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,3,1.0,1.0,1.0,0,2018-09-18 12:00:32,18,12,8,5,7.0,59,19.666667,19.666667,"[5799347067982556520:9172976955054793469, 7908...","[5799347067982556520, 7908382889764677758]","[9172976955054793469, 1787573075717641245,9172...","[7908382889764677758, 5799347067982556520]","[2072967855524022579, 5131280576272319091, 263...",2,22,2,2,2,2,1,1.0,0.045455,1.000000,0.500000
2,842679481291040981,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,5247924392014515924,0,1003,2005,3004,4884875192608989870,1537211052,0,5799347067982556520:5131280576272319091;725801...,6765930309048922341,4,1.0,3,1.0,1.0,1.0,0,2018-09-18 03:04:12,18,3,2,2,7.0,59,19.666667,19.666667,"[5799347067982556520:5131280576272319091, 7258...","[5799347067982556520, 7258015885215914736, 790...","[5131280576272319091, 5131280576272319091, 513...","[7908382889764677758, 5799347067982556520]","[2072967855524022579, 5131280576272319091, 263...",2,22,3,3,3,2,1,1.0,0.045455,0.666667,0.333333
3,937088850059189027,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2681414445369714628,1,1004,2005,3006,840119421106178602,1537222670,15,509660095530134768:-1;5799347067982556520:-1;7...,6765930309048922341,4,1.0,3,1.0,1.0,1.0,0,2018-09-18 06:17:50,18,6,1,1,7.0,59,19.666667,1.229167,"[509660095530134768:-1, 5799347067982556520:-1...","[509660095530134768, 5799347067982556520, 7908...","[1787573075717641245,9148482949976129397, 9148...","[7908382889764677758, 5799347067982556520]","[2072967855524022579, 5131280576272319091, 263...",2,22,5,5,3,2,0,1.0,0.000000,0.400000,0.000000
4,7975697065017708072,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,2729475788342039013,0,1002,2005,3001,1736769971710354684,1537271320,0,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,3,1.0,1.0,1.0,0,2018-09-18 19:48:40,18,19,2,2,7.0,59,19.666667,19.666667,"[5799347067982556520:9172976955054793469, 7908...","[5799347067982556520, 7908382889764677758]","[9172976955054793469, 9172976955054793469]","[7908382889764677758, 5799347067982556520]","[2072967855524022579, 5131280576272319091, 263...",2,22,2,2,2,2,1,1.0,0.045455,1.000000,0.500000

In [31]:
df.to_csv('df_without_his.csv', index=False)

In [ ]:
#item_hot user_hot shop_hot city_hot occupation_hot

In [ ]:
#平均消费能力