In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt
# import seaborn as sns
import pickle
import time
# from tqdm import tqdm

%matplotlib inline

#每次可以输出多个变量
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from pylab import rcParams
rcParams['figure.figsize'] = 14, 6

import warnings
warnings.filterwarnings("ignore")

#中文字体
import matplotlib
matplotlib.use('qt4agg')
#指定默认字体
matplotlib.rcParams['font.sans-serif'] = ['SimHei']
matplotlib.rcParams['font.family'] = 'sans-serif'
#解决负号'-'显示为方块的问题
matplotlib.rcParams['axes.unicode_minus'] = False

In [23]:
train1 = pd.read_csv('train_preprocessing_pre5.csv')
train2 = pd.read_csv('train_preprocessing_6.csv')
train3 = pd.read_csv('train_preprocessing_fulltime.csv')

train1.shape
train1.head()
train2.shape
train2.head()
train3.shape
train3.head()

(1597063, 155)

,instance_id,item_id,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,time,day,hour,minute,user_query_day,user_query_day_hour,user_query_minute,item_category_split_count,item_property_split_count,pred_category_split_count,pred_property_split_count,item_pred_category_score,item_pred_property_score,item_pred_category_score_item%,item_pred_property_score_item%,item_pred_category_score_pred%,item_pred_property_score_pred%,user_shop_count,user_item_count,user_context_count,user_shop_trade_count,user_item_trade_count,user_context_trade_count,user_brand_count,user_city_count,user_brand_trade_count,user_city_trade_count,item_occupation_count,item_age_count,item_gender_count,item_occupation_trade_count,item_age_trade_count,item_gender_trade_count,shop_score,item_score,item_score2,item_score3,item_hot,user_hot,shop_hot,brand_hot,occupation_hot,city_hot,item_trade_hot,user_trade_hot,shop_trade_hot,brand_trade_hot,occupation_trade_hot,city_trade_hot,user_sell_power,user_sell_power_mean,user_sell_power_mean_item_minus,user_sell_trade_power,user_sell_trade_power_mean,user_sell_trade_power_mean_item_minus,yesterday,yesterhour,user_day_query,user_yesterday_query,user_hour_query,user_yesterhour_query,user_minute_query,item_day_query,item_hour_query,item_minute_query,user_item_day_query,user_item_hour_query,user_item_minute_query,min_time,user_is_his,item_is_his,brand_is_his,user_is_trade_his,item_is_trade_his,brand_is_trade_his,user_count,user_day_count,user_hour_count,user_minute_count,item_trade_percent,brand_trade_percent,user_trade_percent,occupation_trade_percent,is_home,shop_item_count,brand_item_count,city_brand_count,city_item_count,shop_item_count_his,brand_item_count_his,city_brand_count_his,city_item_count_his,user_next_count,user_last_count,user_next_time,user_last_time,next_time_sub,last_time_sub,user_item_num,user_shop_num,user_item_day_num,user_shop_day_num,user_item_num_next,user_item_num_last,user_shop_num_next,user_shop_num_last,user_item_next_time,user_item_last_time,user_shop_next_time,user_shop_last_time,user_item_next_time_sub,user_item_last_time_sub,user_shop_next_time_sub,user_shop_last_time_sub,user_fisrt_num,user_item_fisrt_num,user_shop_fisrt_num,user_count_first_time,user_item_count_first_time,user_shop_count_first_time,user_count_first_time_sub,user_item_count_first_time_sub,user_shop_count_first_time_sub,max_click,is_last_click,max_user_item_click,is_last_user_item_click,max_click_time,max_user_item_click_time,max_click_time_sub,max_user_item_click_time_sub
0,1002640977003914936,4943913163084262584,3801992748557162347,4374800994578205793,7,9,10,17,1493508356721691818,1,1005,2002,3007,1088197280290283759,1536249600,0,5829729320339396622,14,1.000000,13,0.981436,0.980990,0.987401,0,2018-09-07 00:00:00,7,0,5,2,2,1,2,19,3,3,1,1,3.333333,0.500000,2.500000,2.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,77.0,55.0,26.0,0.0,0.0,0.0,25.667487,179,19.888889,9.944444,145.0,0.0,426.0,7564.0,2484989,26039.0,0.0,0.0,0.0,8.0,29558,193.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,2,0.0,2,0.0,1,171,62,8,1,1,1,0.0,1,0,1,1,1,0,0,0,0,0,0.000000,0.105764,0.0,1.189462,0,3,105,70,346,3.0,113.0,108.0,564.0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0
1,7563693237648713137,1097656060630949565,8420832032159385750,196257267849351217,7,12,12,20,2535192701541505605,0,1005,2005,3002,4656934049025345586,1536249600,0,1924781308265458391,19,1.000000,18,0.981413,0.981040,0.989620,0,2018-09-07 00:00:00,7,0,5,1,1,1,3,25,1,1,1,0,2.500000,0.000000,5.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3369.0,1275.0,4040.0,2.0,1.0,2.0,35.254001,252,28.000000,14.000000,5376.0,1.0,19723.0,27115.0,4405710,1210626.0,3.0,0.0,30.0,86.0,55540,8360.0,7.0,3.500000,3.500000,0.0,0.0,7.0,6,23,1,0.0,1,0.0,1,723,79,12,1,1,1,0.0,0,0,1,1,0,0,0,0,0,0,0.055804,0.317168,0.0,1.260637,0,52,78,940,5348,85.0,132.0,1189.0,7995.0,1,-1,2018-09-03 13:29:48,NaN,48588,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
2,3325379761110661259,4747706882249246504,6232396831040542357,8519578687848277273,6,14,13,17,8204445143641875432,0,1003,2004,3007,6544635643285905366,1536249600,0,8983666490462246326,23,0.995066,21,0.974091,0.974842,0.967002,0,2018-09-07 00:00:00,7,0,5,2,2,2,2,24,2,1,2,0,6.666667,0.000000,6.666667,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,243.0,410.0,0.0,2.0,2.0,40.298827,235,29.375000,14.687500,546.0,0.0,18742.0,12654.0,412495,71554.0,4.0,0.0,88.0,68.0,4728,563.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,2,0.0,2,0.0,2,364,14,2,1,1,1,0.0,1,0,1,1,0,0,0,0,0,0,0.732601,0.537379,0.0,1.146196,0,176,58,44,509,199.0,72.0,51.0,661.0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
3,6026863564044534796,6075147184977200133,2143736106091506900,6219110439660858399,6,8,8,16,3370515857303357002,-1,-1,-1,-1,1591753168403833710,1536249600,0,146460612484534365,19,0.979555,17,0.957083,0.958109,0.951751,0,2018-09-07 00:00:00,7,0,5,4,2,2,2,20,6,1,2,0,6.666667,0.000000,2.857143,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,6.0,0.0,0.0,0.0,31.079815,136,17.000000,8.500000,147.0,0.0,6382.0,6861.0,17104,1309878.0,0.0,0.0,63.0,64.0,217,12905.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,4,0.0,2,2.0,2,133,12,1,1,1,1,0.0,1,0,1,1,1,0,0,0,0,0,0.000000,0.932809,0.0,1.268709,0,10,12,1958,6805,14.0,18.0,2497.0,9983.0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0
4,7074792290685319356,7227779099688226563,8909918568166119776,3122721854741763495,8,13,13,19,4890272292782939403,0,1002,2005,3009,3421390014084173241,1536249600,0,3685789896910492811,17,1.000000,15,0.983497,0.983812,0.986854,0,2018-09-07 00:00:00,7,0,5,3,3,3,2,34,5,2,2,1,6.666667,0.285714,3.333333,3.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,945.0,170.0,1761.0,2.0,0.0,2.0,30.555430,260,26.000000,13.000000,2197.0,2.0,4177.0,4177.0,4405710,133820.0,4.0,0.0,9.0,9.0,55540,1636.0,11.0,3.666667,4.333333,0.0,0.0,8.0,6,23,3,0.0,3,0.0,3,1014,182,15,1,1,1,0.0,0,0,1,1,0,0,0,0,0,0,0.182066,0.215466,0.0,1.260637,0,43,43,152,687,51.0,51.0,190.0,1115.0,1,-1,2018-09-07 00:00:21,NaN,21,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0

(1597063, 155)

,instance_id,item_id,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,time,day,hour,minute,user_query_day,user_query_day_hour,user_query_minute,item_category_split_count,item_property_split_count,pred_category_split_count,pred_property_split_count,item_pred_category_score,item_pred_property_score,item_pred_category_score_item%,item_pred_property_score_item%,item_pred_category_score_pred%,item_pred_property_score_pred%,user_shop_count,user_item_count,user_context_count,user_shop_trade_count,user_item_trade_count,user_context_trade_count,user_brand_count,user_city_count,user_brand_trade_count,user_city_trade_count,item_occupation_count,item_age_count,item_gender_count,item_occupation_trade_count,item_age_trade_count,item_gender_trade_count,shop_score,item_score,item_score2,item_score3,item_hot,user_hot,shop_hot,brand_hot,occupation_hot,city_hot,item_trade_hot,user_trade_hot,shop_trade_hot,brand_trade_hot,occupation_trade_hot,city_trade_hot,user_sell_power,user_sell_power_mean,user_sell_power_mean_item_minus,user_sell_trade_power,user_sell_trade_power_mean,user_sell_trade_power_mean_item_minus,yesterday,yesterhour,user_day_query,user_yesterday_query,user_hour_query,user_yesterhour_query,user_minute_query,item_day_query,item_hour_query,item_minute_query,user_item_day_query,user_item_hour_query,user_item_minute_query,min_time,user_is_his,item_is_his,brand_is_his,user_is_trade_his,item_is_trade_his,brand_is_trade_his,user_count,user_day_count,user_hour_count,user_minute_count,item_trade_percent,brand_trade_percent,user_trade_percent,occupation_trade_percent,is_home,shop_item_count,brand_item_count,city_brand_count,city_item_count,shop_item_count_his,brand_item_count_his,city_brand_count_his,city_item_count_his,user_next_count,user_last_count,user_next_time,user_last_time,next_time_sub,last_time_sub,user_item_num,user_shop_num,user_item_day_num,user_shop_day_num,user_item_num_next,user_item_num_last,user_shop_num_next,user_shop_num_last,user_item_next_time,user_item_last_time,user_shop_next_time,user_shop_last_time,user_item_next_time_sub,user_item_last_time_sub,user_shop_next_time_sub,user_shop_last_time_sub,user_fisrt_num,user_item_fisrt_num,user_shop_fisrt_num,user_count_first_time,user_item_count_first_time,user_shop_count_first_time,user_count_first_time_sub,user_item_count_first_time_sub,user_shop_count_first_time_sub,max_click,is_last_click,max_user_item_click,is_last_user_item_click,max_click_time,max_user_item_click_time,max_click_time_sub,max_user_item_click_time_sub
0,1002640977003914936,4943913163084262584,3801992748557162347,4374800994578205793,7,9,10,17,1493508356721691818,1,1005,2002,3007,1088197280290283759,1536249600,0,5829729320339396622,14,1.000000,13,0.981436,0.980990,0.987401,0,2018-09-07 00:00:00,7,0,5,2,2,1,2,19,3,3,1,1,3.333333,0.500000,2.500000,2.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,48.0,43.0,29.0,0.0,0.0,0.0,25.667487,179,19.888889,9.944444,123.0,0.0,272.0,3025.0,664288,9429.0,0.0,0.0,0.0,0.0,3098,26.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,2,0.0,2,0.0,1,171,62,8,1,1,1,0.0,1,0,1,1,1,1,0,0,0,0,0.000000,0.000000,0.0,0.466364,0,3,105,70,346,3.0,92.0,80.0,376.0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0
1,7563693237648713137,1097656060630949565,8420832032159385750,196257267849351217,7,12,12,20,2535192701541505605,0,1005,2005,3002,4656934049025345586,1536249600,0,1924781308265458391,19,1.000000,18,0.981413,0.981040,0.989620,0,2018-09-07 00:00:00,7,0,5,1,1,1,3,25,1,1,1,0,2.500000,0.000000,5.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,860.0,304.0,1064.0,0.0,0.0,0.0,35.254001,252,28.000000,14.000000,1413.0,0.0,5612.0,7070.0,1125867,330746.0,0.0,0.0,0.0,2.0,6846,877.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,1,0.0,1,0.0,1,723,79,12,1,1,1,0.0,1,0,1,1,1,0,0,0,0,0,0.000000,0.028289,0.0,0.608065,0,52,78,940,5348,53.0,81.0,952.0,5582.0,1,-1,NaN,NaN,999999,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
2,3325379761110661259,4747706882249246504,6232396831040542357,8519578687848277273,6,14,13,17,8204445143641875432,0,1003,2004,3007,6544635643285905366,1536249600,0,8983666490462246326,23,0.995066,21,0.974091,0.974842,0.967002,0,2018-09-07 00:00:00,7,0,5,2,2,2,2,24,2,1,2,0,6.666667,0.000000,6.666667,0.000000,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,33.0,328.0,480.0,0.0,0.0,1.0,40.298827,235,29.375000,14.687500,599.0,2.0,10131.0,7157.0,109743,23811.0,1.0,0.0,15.0,13.0,520,65.0,11.0,3.666667,2.333333,0.0,0.0,6.0,6,23,2,0.0,2,0.0,2,364,14,2,1,1,1,0.0,0,0,1,1,0,0,0,0,0,0,0.166945,0.181640,0.0,0.473834,0,176,58,44,509,204.0,65.0,44.0,530.0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,2018-09-06 23:56:27,NaN,2018-09-06 23:56:27,NaN,86187,999999,86187,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
3,6026863564044534796,6075147184977200133,2143736106091506900,6219110439660858399,6,8,8,16,3370515857303357002,-1,-1,-1,-1,1591753168403833710,1536249600,0,146460612484534365,19,0.979555,17,0.957083,0.958109,0.951751,0,2018-09-07 00:00:00,7,0,5,4,2,2,2,20,6,1,2,0,6.666667,0.000000,2.857143,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,31.079815,136,17.000000,8.500000,80.0,0.0,1257.0,1330.0,4490,342180.0,0.0,0.0,8.0,9.0,45,1554.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,4,0.0,2,2.0,2,133,12,1,1,1,1,0.0,1,0,1,1,1,0,0,0,0,0,0.000000,0.676692,0.0,1.002227,0,10,12,1958,6805,10.0,13.0,1948.0,6822.0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0
4,7074792290685319356,7227779099688226563,8909918568166119776,3122721854741763495,8,13,13,19,4890272292782939403,0,1002,2005,3009,3421390014084173241,1536249600,0,3685789896910492811,17,1.000000,15,0.983497,0.983812,0.986854,0,2018-09-07 00:00:00,7,0,5,3,3,3,2,34,5,2,2,1,6.666667,0.285714,3.333333,3.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,431.0,97.0,796.0,0.0,0.0,0.0,30.555430,260,26.000000,13.000000,1011.0,1.0,2589.0,2589.0,1125867,33116.0,0.0,0.0,2.0,2.0,6846,153.0,6.0,3.000000,5.000000,0.0,0.0,8.0,6,23,3,0.0,3,0.0,3,1014,182,15,1,1,1,0.0,0,0,1,1,1,0,0,0,0,0,0.000000,0.077250,0.0,0.608065,0,43,43,152,687,28.0,28.0,161.0,713.0,1,-1,2018-09-07 00:00:21,NaN,21,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0

(1597063, 77)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,time,day,hour,minute,user_query_day,user_query_day_hour,user_query_minute,user_count,user_day_count,user_hour_count,user_minute_count,user_next_count,user_last_count,user_next_time,user_last_time,next_time_sub,last_time_sub,user_item_num,user_shop_num,user_item_day_num,user_shop_day_num,user_item_num_next,user_item_num_last,user_shop_num_next,user_shop_num_last,user_item_next_time,user_item_last_time,user_shop_next_time,user_shop_last_time,user_item_next_time_sub,user_item_last_time_sub,user_shop_next_time_sub,user_shop_last_time_sub,user_fisrt_num,user_item_fisrt_num,user_shop_fisrt_num,user_count_first_time,user_item_count_first_time,user_shop_count_first_time,user_count_first_time_sub,user_item_count_first_time_sub,user_shop_count_first_time_sub,max_click,is_last_click,max_user_item_click,is_last_user_item_click,max_click_time,max_user_item_click_time,max_click_time_sub,max_user_item_click_time_sub
0,1002640977003914936,4943913163084262584,836752724084922533;768579787521575291,367082587220462692;5131280576272319091;8689439...,3801992748557162347,4374800994578205793,7,9,10,17,1493508356721691818,1,1005,2002,3007,1088197280290283759,1536249600,4001,"836752724084922533:4324484723289924768,3657871...",5829729320339396622,14,1.000000,5012,0.981436,0.980990,0.987401,0,2018-09-07 00:00:00,7,0,0,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0
1,7563693237648713137,1097656060630949565,836752724084922533;3613783563199627217;6370392...,6241534230954727302;367082587220462692;5977512...,8420832032159385750,196257267849351217,7,12,12,20,2535192701541505605,0,1005,2005,3002,4656934049025345586,1536249600,4001,"836752724084922533:1405752240728470138,2125982...",1924781308265458391,19,1.000000,5017,0.981413,0.981040,0.989620,0,2018-09-07 00:00:00,7,0,0,1,1,1,0,0,0,0,1,-1,2018-09-03 13:29:48,NaN,48588,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
2,3325379761110661259,4747706882249246504,836752724084922533;768579787521575291,3540471119339706981;5131280576272319091;302719...,6232396831040542357,8519578687848277273,6,14,13,17,8204445143641875432,0,1003,2004,3007,6544635643285905366,1536249600,4001,"768579787521575291:3540471119339706981,5131280...",8983666490462246326,23,0.995066,5020,0.974091,0.974842,0.967002,0,2018-09-07 00:00:00,7,0,0,2,2,2,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,2018-09-06 23:56:27,NaN,2018-09-06 23:56:27,NaN,86187,999999,86187,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
3,6026863564044534796,6075147184977200133,836752724084922533;1909641874861640857,5977512434884267894;2072967855524022579;263639...,2143736106091506900,6219110439660858399,6,8,8,16,3370515857303357002,-1,-1,-1,-1,1591753168403833710,1536249600,4001,1036082357054043890:-1;8658630417297894718:-1;...,146460612484534365,19,0.979555,5016,0.957083,0.958109,0.951751,0,2018-09-07 00:00:00,7,0,0,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0
4,7074792290685319356,7227779099688226563,836752724084922533;768579787521575291,6241534230954727302;3540471119339706981;462193...,8909918568166119776,3122721854741763495,8,13,13,19,4890272292782939403,0,1002,2005,3009,3421390014084173241,1536249600,4001,768579787521575291:-1;8096917686185033019:9148...,3685789896910492811,17,1.000000,5014,0.983497,0.983812,0.986854,0,2018-09-07 00:00:00,7,0,0,3,3,3,0,0,0,0,1,-1,2018-09-07 00:00:21,NaN,21,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0

In [25]:
origin = [
    'item_id', 'item_brand_id', 'item_city_id',
    'item_price_level', 'item_sales_level', 'item_collected_level',
    'item_pv_level', 'user_id', 'user_gender_id', 'user_age_level',
    'user_occupation_id', 'user_star_level', 'context_id', 'context_timestamp',
    'context_page_id', 'shop_id', 'shop_review_num_level',
    'shop_review_positive_rate', 'shop_star_level', 'shop_score_service',
    'shop_score_delivery', 'shop_score_description'
]

features = [
    'time', 'day', 'hour', 'minute', 'user_query_day', 'user_query_day_hour',
    'user_query_minute', 'item_category_split_count',
    'item_property_split_count', 'pred_category_split_count',
    'pred_property_split_count', 'item_pred_category_score',
    'item_pred_property_score', 'item_pred_category_score_item%',
    'item_pred_property_score_item%', 'item_pred_category_score_pred%',
    'item_pred_property_score_pred%', 'user_shop_count', 'user_item_count',
    'user_context_count', 'user_shop_trade_count', 'user_item_trade_count',
    'user_context_trade_count', 'user_brand_count', 'user_city_count',
    'user_brand_trade_count', 'user_city_trade_count', 'item_occupation_count',
    'item_age_count', 'item_gender_count', 'item_occupation_trade_count',
    'item_age_trade_count', 'item_gender_trade_count', 'shop_score',
    'item_score', 'item_score2', 'item_score3', 'item_hot', 'user_hot',
    'shop_hot', 'brand_hot', 'occupation_hot', 'city_hot', 'item_trade_hot',
    'user_trade_hot', 'shop_trade_hot', 'brand_trade_hot',
    'occupation_trade_hot', 'city_trade_hot', 'user_sell_power',
    'user_sell_power_mean', 'user_sell_power_mean_item_minus',
    'user_sell_trade_power', 'user_sell_trade_power_mean',
    'user_sell_trade_power_mean_item_minus', 'yesterday', 'yesterhour',
    'user_day_query', 'user_yesterday_query', 'user_hour_query',
    'user_yesterhour_query', 'user_minute_query', 'item_day_query',
    'item_hour_query', 'item_minute_query', 'user_item_day_query',
    'user_item_hour_query', 'user_item_minute_query', 'min_time',
    'user_is_his', 'item_is_his', 'brand_is_his', 'user_is_trade_his',
    'item_is_trade_his', 'brand_is_trade_his', 'user_count', 'user_day_count',
    'user_hour_count', 'user_minute_count', 'item_trade_percent',
    'brand_trade_percent', 'user_trade_percent', 'occupation_trade_percent',
    'is_home', 'shop_item_count', 'brand_item_count', 'city_brand_count',
    'city_item_count', 'shop_item_count_his', 'brand_item_count_his',
    'city_brand_count_his', 'city_item_count_his', 'user_next_count',
    'user_last_count', 'user_next_time', 'user_last_time', 'next_time_sub',
    'last_time_sub', 'user_item_num', 'user_shop_num', 'user_item_day_num',
    'user_shop_day_num', 'user_item_num_next', 'user_item_num_last',
    'user_shop_num_next', 'user_shop_num_last', 'user_item_next_time',
    'user_item_last_time', 'user_shop_next_time', 'user_shop_last_time',
    'user_item_next_time_sub', 'user_item_last_time_sub',
    'user_shop_next_time_sub', 'user_shop_last_time_sub', 'user_fisrt_num',
    'user_item_fisrt_num', 'user_shop_fisrt_num', 'user_count_first_time',
    'user_item_count_first_time', 'user_shop_count_first_time',
    'user_count_first_time_sub', 'user_item_count_first_time_sub',
    'user_shop_count_first_time_sub', 'max_click', 'is_last_click',
    'max_user_item_click', 'is_last_user_item_click', 'max_click_time',
    'max_user_item_click_time', 'max_click_time_sub',
    'max_user_item_click_time_sub'
]

by = ['instance_id']

target = ['is_trade']

In [29]:
# train2 = train2.drop(origin + target, axis=1)
# train3 = train3.drop(origin + target, axis=1)

train2_col = []
for i in train2.columns:
    train2_col.append(i + '_6')
train2.columns = train2_col

train3_col = []
for i in train3.columns:
    train3_col.append(i + '_full_time')
train3.columns = train3_col

In [32]:
train = train1.merge(train2, left_on=['instance_id'], right_on=['instance_id_6'], how='left')
train = train.merge(train3, left_on=['instance_id'], right_on=['instance_id_full_time'], how='left')

train.shape
train.head()

(1597063, 341)

,instance_id,item_id,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,time,day,hour,minute,user_query_day,user_query_day_hour,user_query_minute,item_category_split_count,item_property_split_count,pred_category_split_count,pred_property_split_count,item_pred_category_score,item_pred_property_score,item_pred_category_score_item%,item_pred_property_score_item%,item_pred_category_score_pred%,item_pred_property_score_pred%,user_shop_count,user_item_count,user_context_count,user_shop_trade_count,user_item_trade_count,user_context_trade_count,user_brand_count,user_city_count,user_brand_trade_count,user_city_trade_count,item_occupation_count,item_age_count,item_gender_count,item_occupation_trade_count,item_age_trade_count,item_gender_trade_count,shop_score,item_score,item_score2,item_score3,item_hot,user_hot,shop_hot,brand_hot,occupation_hot,city_hot,item_trade_hot,user_trade_hot,shop_trade_hot,brand_trade_hot,occupation_trade_hot,city_trade_hot,user_sell_power,user_sell_power_mean,user_sell_power_mean_item_minus,user_sell_trade_power,user_sell_trade_power_mean,user_sell_trade_power_mean_item_minus,yesterday,yesterhour,user_day_query,user_yesterday_query,user_hour_query,user_yesterhour_query,user_minute_query,item_day_query,item_hour_query,item_minute_query,user_item_day_query,user_item_hour_query,user_item_minute_query,min_time,user_is_his,item_is_his,brand_is_his,user_is_trade_his,item_is_trade_his,brand_is_trade_his,user_count,user_day_count,user_hour_count,user_minute_count,item_trade_percent,brand_trade_percent,user_trade_percent,occupation_trade_percent,is_home,shop_item_count,brand_item_count,city_brand_count,city_item_count,shop_item_count_his,brand_item_count_his,city_brand_count_his,city_item_count_his,user_next_count,user_last_count,user_next_time,user_last_time,next_time_sub,last_time_sub,user_item_num,user_shop_num,user_item_day_num,user_shop_day_num,user_item_num_next,user_item_num_last,user_shop_num_next,user_shop_num_last,user_item_next_time,user_item_last_time,user_shop_next_time,user_shop_last_time,user_item_next_time_sub,user_item_last_time_sub,user_shop_next_time_sub,user_shop_last_time_sub,user_fisrt_num,user_item_fisrt_num,user_shop_fisrt_num,user_count_first_time,user_item_count_first_time,user_shop_count_first_time,user_count_first_time_sub,user_item_count_first_time_sub,user_shop_count_first_time_sub,max_click,is_last_click,max_user_item_click,is_last_user_item_click,max_click_time,max_user_item_click_time,max_click_time_sub,max_user_item_click_time_sub,instance_id_6,time_6,day_6,hour_6,minute_6,user_query_day_6,user_query_day_hour_6,user_query_minute_6,item_category_split_count_6,item_property_split_count_6,pred_category_split_count_6,pred_property_split_count_6,item_pred_category_score_6,item_pred_property_score_6,item_pred_category_score_item%_6,item_pred_property_score_item%_6,item_pred_category_score_pred%_6,item_pred_property_score_pred%_6,user_shop_count_6,user_item_count_6,user_context_count_6,user_shop_trade_count_6,user_item_trade_count_6,user_context_trade_count_6,user_brand_count_6,user_city_count_6,user_brand_trade_count_6,user_city_trade_count_6,item_occupation_count_6,item_age_count_6,item_gender_count_6,item_occupation_trade_count_6,item_age_trade_count_6,item_gender_trade_count_6,shop_score_6,item_score_6,item_score2_6,item_score3_6,item_hot_6,user_hot_6,shop_hot_6,brand_hot_6,occupation_hot_6,city_hot_6,item_trade_hot_6,user_trade_hot_6,shop_trade_hot_6,brand_trade_hot_6,occupation_trade_hot_6,city_trade_hot_6,user_sell_power_6,user_sell_power_mean_6,user_sell_power_mean_item_minus_6,user_sell_trade_power_6,user_sell_trade_power_mean_6,user_sell_trade_power_mean_item_minus_6,yesterday_6,yesterhour_6,user_day_query_6,user_yesterday_query_6,user_hour_query_6,user_yesterhour_query_6,user_minute_query_6,item_day_query_6,item_hour_query_6,item_minute_query_6,user_item_day_query_6,user_item_hour_query_6,user_item_minute_query_6,min_time_6,user_is_his_6,item_is_his_6,brand_is_his_6,user_is_trade_his_6,item_is_trade_his_6,brand_is_trade_his_6,user_count_6,user_day_count_6,user_hour_count_6,user_minute_count_6,item_trade_percent_6,brand_trade_percent_6,user_trade_percent_6,occupation_trade_percent_6,is_home_6,shop_item_count_6,brand_item_count_6,city_brand_count_6,city_item_count_6,shop_item_count_his_6,brand_item_count_his_6,city_brand_count_his_6,city_item_count_his_6,user_next_count_6,user_last_count_6,user_next_time_6,user_last_time_6,next_time_sub_6,last_time_sub_6,user_item_num_6,user_shop_num_6,user_item_day_num_6,user_shop_day_num_6,user_item_num_next_6,user_item_num_last_6,user_shop_num_next_6,user_shop_num_last_6,user_item_next_time_6,user_item_last_time_6,user_shop_next_time_6,user_shop_last_time_6,user_item_next_time_sub_6,user_item_last_time_sub_6,user_shop_next_time_sub_6,user_shop_last_time_sub_6,user_fisrt_num_6,user_item_fisrt_num_6,user_shop_fisrt_num_6,user_count_first_time_6,user_item_count_first_time_6,user_shop_count_first_time_6,user_count_first_time_sub_6,user_item_count_first_time_sub_6,user_shop_count_first_time_sub_6,max_click_6,is_last_click_6,max_user_item_click_6,is_last_user_item_click_6,max_click_time_6,max_user_item_click_time_6,max_click_time_sub_6,max_user_item_click_time_sub_6,instance_id_full_time,item_category_list_full_time,item_property_list_full_time,predict_category_property_full_time,time_full_time,day_full_time,hour_full_time,minute_full_time,user_query_day_full_time,user_query_day_hour_full_time,user_query_minute_full_time,user_count_full_time,user_day_count_full_time,user_hour_count_full_time,user_minute_count_full_time,user_next_count_full_time,user_last_count_full_time,user_next_time_full_time,user_last_time_full_time,next_time_sub_full_time,last_time_sub_full_time,user_item_num_full_time,user_shop_num_full_time,user_item_day_num_full_time,user_shop_day_num_full_time,user_item_num_next_full_time,user_item_num_last_full_time,user_shop_num_next_full_time,user_shop_num_last_full_time,user_item_next_time_full_time,user_item_last_time_full_time,user_shop_next_time_full_time,user_shop_last_time_full_time,user_item_next_time_sub_full_time,user_item_last_time_sub_full_time,user_shop_next_time_sub_full_time,user_shop_last_time_sub_full_time,user_fisrt_num_full_time,user_item_fisrt_num_full_time,user_shop_fisrt_num_full_time,user_count_first_time_full_time,user_item_count_first_time_full_time,user_shop_count_first_time_full_time,user_count_first_time_sub_full_time,user_item_count_first_time_sub_full_time,user_shop_count_first_time_sub_full_time,max_click_full_time,is_last_click_full_time,max_user_item_click_full_time,is_last_user_item_click_full_time,max_click_time_full_time,max_user_item_click_time_full_time,max_click_time_sub_full_time,max_user_item_click_time_sub_full_time
0,1002640977003914936,4943913163084262584,3801992748557162347,4374800994578205793,7,9,10,17,1493508356721691818,1,1005,2002,3007,1088197280290283759,1536249600,0,5829729320339396622,14,1.000000,13,0.981436,0.980990,0.987401,0,2018-09-07 00:00:00,7,0,5,2,2,1,2,19,3,3,1,1,3.333333,0.500000,2.500000,2.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,77.0,55.0,26.0,0.0,0.0,0.0,25.667487,179,19.888889,9.944444,145.0,0.0,426.0,7564.0,2484989,26039.0,0.0,0.0,0.0,8.0,29558,193.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,2,0.0,2,0.0,1,171,62,8,1,1,1,0.0,1,0,1,1,1,0,0,0,0,0,0.000000,0.105764,0.0,1.189462,0,3,105,70,346,3.0,113.0,108.0,564.0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0,1002640977003914936,2018-09-07 00:00:00,7,0,5,2,2,1,2,19,3,3,1,1,3.333333,0.500000,2.500000,2.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,48.0,43.0,29.0,0.0,0.0,0.0,25.667487,179,19.888889,9.944444,123.0,0.0,272.0,3025.0,664288,9429.0,0.0,0.0,0.0,0.0,3098,26.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,2,0.0,2,0.0,1,171,62,8,1,1,1,0.0,1,0,1,1,1,1,0,0,0,0,0.000000,0.000000,0.0,0.466364,0,3,105,70,346,3.0,92.0,80.0,376.0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0,1002640977003914936,836752724084922533;768579787521575291,367082587220462692;5131280576272319091;8689439...,"836752724084922533:4324484723289924768,3657871...",2018-09-07 00:00:00,7,0,0,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0
1,7563693237648713137,1097656060630949565,8420832032159385750,196257267849351217,7,12,12,20,2535192701541505605,0,1005,2005,3002,4656934049025345586,1536249600,0,1924781308265458391,19,1.000000,18,0.981413,0.981040,0.989620,0,2018-09-07 00:00:00,7,0,5,1,1,1,3,25,1,1,1,0,2.500000,0.000000,5.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3369.0,1275.0,4040.0,2.0,1.0,2.0,35.254001,252,28.000000,14.000000,5376.0,1.0,19723.0,27115.0,4405710,1210626.0,3.0,0.0,30.0,86.0,55540,8360.0,7.0,3.500000,3.500000,0.0,0.0,7.0,6,23,1,0.0,1,0.0,1,723,79,12,1,1,1,0.0,0,0,1,1,0,0,0,0,0,0,0.055804,0.317168,0.0,1.260637,0,52,78,940,5348,85.0,132.0,1189.0,7995.0,1,-1,2018-09-03 13:29:48,NaN,48588,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,7563693237648713137,2018-09-07 00:00:00,7,0,5,1,1,1,3,25,1,1,1,0,2.500000,0.000000,5.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,860.0,304.0,1064.0,0.0,0.0,0.0,35.254001,252,28.000000,14.000000,1413.0,0.0,5612.0,7070.0,1125867,330746.0,0.0,0.0,0.0,2.0,6846,877.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,1,0.0,1,0.0,1,723,79,12,1,1,1,0.0,1,0,1,1,1,0,0,0,0,0,0.000000,0.028289,0.0,0.608065,0,52,78,940,5348,53.0,81.0,952.0,5582.0,1,-1,NaN,NaN,999999,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,7563693237648713137,836752724084922533;3613783563199627217;6370392...,6241534230954727302;367082587220462692;5977512...,"836752724084922533:1405752240728470138,2125982...",2018-09-07 00:00:00,7,0,0,1,1,1,0,0,0,0,1,-1,2018-09-03 13:29:48,NaN,48588,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
2,3325379761110661259,4747706882249246504,6232396831040542357,8519578687848277273,6,14,13,17,8204445143641875432,0,1003,2004,3007,6544635643285905366,1536249600,0,8983666490462246326,23,0.995066,21,0.974091,0.974842,0.967002,0,2018-09-07 00:00:00,7,0,5,2,2,2,2,24,2,1,2,0,6.666667,0.000000,6.666667,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,243.0,410.0,0.0,2.0,2.0,40.298827,235,29.375000,14.687500,546.0,0.0,18742.0,12654.0,412495,71554.0,4.0,0.0,88.0,68.0,4728,563.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,2,0.0,2,0.0,2,364,14,2,1,1,1,0.0,1,0,1,1,0,0,0,0,0,0,0.732601,0.537379,0.0,1.146196,0,176,58,44,509,199.0,72.0,51.0,661.0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,3325379761110661259,2018-09-07 00:00:00,7,0,5,2,2,2,2,24,2,1,2,0,6.666667,0.000000,6.666667,0.000000,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,33.0,328.0,480.0,0.0,0.0,1.0,40.298827,235,29.375000,14.687500,599.0,2.0,10131.0,7157.0,109743,23811.0,1.0,0.0,15.0,13.0,520,65.0,11.0,3.666667,2.333333,0.0,0.0,6.0,6,23,2,0.0,2,0.0,2,364,14,2,1,1,1,0.0,0,0,1,1,0,0,0,0,0,0,0.166945,0.181640,0.0,0.473834,0,176,58,44,509,204.0,65.0,44.0,530.0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,2018-09-06 23:56:27,NaN,2018-09-06 23:56:27,NaN,86187,999999,86187,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,3325379761110661259,836752724084922533;768579787521575291,3540471119339706981;5131280576272319091;302719...,"768579787521575291:3540471119339706981,5131280...",2018-09-07 00:00:00,7,0,0,2,2,2,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,2018-09-06 23:56:27,NaN,2018-09-06 23:56:27,NaN,86187,999999,86187,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
3,6026863564044534796,6075147184977200133,2143736106091506900,6219110439660858399,6,8,8,16,3370515857303357002,-1,-1,-1,-1,1591753168403833710,1536249600,0,146460612484534365,19,0.979555,17,0.957083,0.958109,0.951751,0,2018-09-07 00:00:00,7,0,5,4,2,2,2,20,6,1,2,0,6.666667,0.000000,2.857143,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,6.0,0.0,0.0,0.0,31.079815,136,17.000000,8.500000,147.0,0.0,6382.0,6861.0,17104,1309878.0,0.0,0.0,63.0,64.0,217,12905.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,4,0.0,2,2.0,2,133,12,1,1,1,1,0.0,1,0,1,1,1,0,0,0,0,0,0.000000,0.932809,0.0,1.268709,0,10,12,1958,6805,14.0,18.0,2497.0,9983.0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0,6026863564044534796,2018-09-07 00:00:00,7,0,5,4,2,2,2,20,6,1,2,0,6.666667,0.000000,2.857143,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,31.079815,136,17.000000,8.500000,80.0,0.0,1257.0,1330.0,4490,342180.0,0.0,0.0,8.0,9.0,45,1554.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,4,0.0,2,2.0,2,133,12,1,1,1,1,0.0,1,0,1,1,1,0,0,0,0,0,0.000000,0.676692,0.0,1.002227,0,10,12,1958,6805,10.0,13.0,1948.0,6822.0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0,6026863564044534796,836752724084922533;1909641874861640857,5977512434884267894;2072967855524022579;263639...,1036082357054043890:-1;8658630417297894718:-1;...,2018-09-07 00:00:00,7,0,0,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0
4,7074792290685319356,7227779099688226563,8909918568166119776,3122721854741763495,8,13,13,19,4890272292782939403,0,1002,2005,3009,3421390014084173241,1536249600,0,3685789896910492811,17,1.000000,15,0.983497,0.983812,0.986854,0,2018-09-07 00:00:00,7,0,5,3,3,3,2,34,5,2,2,1,6.666667,0.285714,3.333333,3.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,945.0,170.0,1761.0,2.0,0.0,2.0,30.555430,260,26.000000,13.000000,2197.0,2.0,4177.0,4177.0,4405710,133820.0,4.0,0.0,9.0,9.0,55540,1636.0,11.0,3.666667,4.333333,0.0,0.0,8.0,6,23,3,0.0,3,0.0,3,1014,182,15,1,1,1,0.0,0,0,1,1,0,0,0,0,0,0,0.182066,0.215466,0.0,1.260637,0,43,43,152,687,51.0,51.0,190.0,1115.0,1,-1,2018-09-07 00:00:21,NaN,21,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0,7074792290685319356,2018-09-07 00:00:00,7,0,5,3,3,3,2,34,5,2,2,1,6.666667,0.285714,3.333333,3.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,431.0,97.0,796.0,0.0,0.0,0.0,30.555430,260,26.000000,13.000000,1011.0,1.0,2589.0,2589.0,1125867,33116.0,0.0,0.0,2.0,2.0,6846,153.0,6.0,3.000000,5.000000,0.0,0.0,8.0,6,23,3,0.0,3,0.0,3,1014,182,15,1,1,1,0.0,0,0,1,1,1,0,0,0,0,0,0.000000,0.077250,0.0,0.608065,0,43,43,152,687,28.0,28.0,161.0,713.0,1,-1,2018-09-07 00:00:21,NaN,21,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0,7074792290685319356,836752724084922533;768579787521575291,6241534230954727302;3540471119339706981;462193...,768579787521575291:-1;8096917686185033019:9148...,2018-09-07 00:00:00,7,0,0,3,3,3,0,0,0,0,1,-1,2018-09-07 00:00:21,NaN,21,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0

In [45]:
del train1
del train2
del train3
# train.to_csv('train_zero.csv', index=None)

In [2]:
import sys
sys.path.append('/Users/zero/xgboost/python-package')
import xgboost as xgb
# import lightgbm as lgb

from sklearn.model_selection import GridSearchCV
from sklearn.cross_validation import KFold
from sklearn.metrics import log_loss

/opt/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [3]:
train = pd.read_csv('train_zero.csv')

train.shape
train.head()

(1597063, 341)

,instance_id,item_id,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,time,day,hour,minute,user_query_day,user_query_day_hour,user_query_minute,item_category_split_count,item_property_split_count,pred_category_split_count,pred_property_split_count,item_pred_category_score,item_pred_property_score,item_pred_category_score_item%,item_pred_property_score_item%,item_pred_category_score_pred%,item_pred_property_score_pred%,user_shop_count,user_item_count,user_context_count,user_shop_trade_count,user_item_trade_count,user_context_trade_count,user_brand_count,user_city_count,user_brand_trade_count,user_city_trade_count,item_occupation_count,item_age_count,item_gender_count,item_occupation_trade_count,item_age_trade_count,item_gender_trade_count,shop_score,item_score,item_score2,item_score3,item_hot,user_hot,shop_hot,brand_hot,occupation_hot,city_hot,item_trade_hot,user_trade_hot,shop_trade_hot,brand_trade_hot,occupation_trade_hot,city_trade_hot,user_sell_power,user_sell_power_mean,user_sell_power_mean_item_minus,user_sell_trade_power,user_sell_trade_power_mean,user_sell_trade_power_mean_item_minus,yesterday,yesterhour,user_day_query,user_yesterday_query,user_hour_query,user_yesterhour_query,user_minute_query,item_day_query,item_hour_query,item_minute_query,user_item_day_query,user_item_hour_query,user_item_minute_query,min_time,user_is_his,item_is_his,brand_is_his,user_is_trade_his,item_is_trade_his,brand_is_trade_his,user_count,user_day_count,user_hour_count,user_minute_count,item_trade_percent,brand_trade_percent,user_trade_percent,occupation_trade_percent,is_home,shop_item_count,brand_item_count,city_brand_count,city_item_count,shop_item_count_his,brand_item_count_his,city_brand_count_his,city_item_count_his,user_next_count,user_last_count,user_next_time,user_last_time,next_time_sub,last_time_sub,user_item_num,user_shop_num,user_item_day_num,user_shop_day_num,user_item_num_next,user_item_num_last,user_shop_num_next,user_shop_num_last,user_item_next_time,user_item_last_time,user_shop_next_time,user_shop_last_time,user_item_next_time_sub,user_item_last_time_sub,user_shop_next_time_sub,user_shop_last_time_sub,user_fisrt_num,user_item_fisrt_num,user_shop_fisrt_num,user_count_first_time,user_item_count_first_time,user_shop_count_first_time,user_count_first_time_sub,user_item_count_first_time_sub,user_shop_count_first_time_sub,max_click,is_last_click,max_user_item_click,is_last_user_item_click,max_click_time,max_user_item_click_time,max_click_time_sub,max_user_item_click_time_sub,instance_id_6,time_6,day_6,hour_6,minute_6,user_query_day_6,user_query_day_hour_6,user_query_minute_6,item_category_split_count_6,item_property_split_count_6,pred_category_split_count_6,pred_property_split_count_6,item_pred_category_score_6,item_pred_property_score_6,item_pred_category_score_item%_6,item_pred_property_score_item%_6,item_pred_category_score_pred%_6,item_pred_property_score_pred%_6,user_shop_count_6,user_item_count_6,user_context_count_6,user_shop_trade_count_6,user_item_trade_count_6,user_context_trade_count_6,user_brand_count_6,user_city_count_6,user_brand_trade_count_6,user_city_trade_count_6,item_occupation_count_6,item_age_count_6,item_gender_count_6,item_occupation_trade_count_6,item_age_trade_count_6,item_gender_trade_count_6,shop_score_6,item_score_6,item_score2_6,item_score3_6,item_hot_6,user_hot_6,shop_hot_6,brand_hot_6,occupation_hot_6,city_hot_6,item_trade_hot_6,user_trade_hot_6,shop_trade_hot_6,brand_trade_hot_6,occupation_trade_hot_6,city_trade_hot_6,user_sell_power_6,user_sell_power_mean_6,user_sell_power_mean_item_minus_6,user_sell_trade_power_6,user_sell_trade_power_mean_6,user_sell_trade_power_mean_item_minus_6,yesterday_6,yesterhour_6,user_day_query_6,user_yesterday_query_6,user_hour_query_6,user_yesterhour_query_6,user_minute_query_6,item_day_query_6,item_hour_query_6,item_minute_query_6,user_item_day_query_6,user_item_hour_query_6,user_item_minute_query_6,min_time_6,user_is_his_6,item_is_his_6,brand_is_his_6,user_is_trade_his_6,item_is_trade_his_6,brand_is_trade_his_6,user_count_6,user_day_count_6,user_hour_count_6,user_minute_count_6,item_trade_percent_6,brand_trade_percent_6,user_trade_percent_6,occupation_trade_percent_6,is_home_6,shop_item_count_6,brand_item_count_6,city_brand_count_6,city_item_count_6,shop_item_count_his_6,brand_item_count_his_6,city_brand_count_his_6,city_item_count_his_6,user_next_count_6,user_last_count_6,user_next_time_6,user_last_time_6,next_time_sub_6,last_time_sub_6,user_item_num_6,user_shop_num_6,user_item_day_num_6,user_shop_day_num_6,user_item_num_next_6,user_item_num_last_6,user_shop_num_next_6,user_shop_num_last_6,user_item_next_time_6,user_item_last_time_6,user_shop_next_time_6,user_shop_last_time_6,user_item_next_time_sub_6,user_item_last_time_sub_6,user_shop_next_time_sub_6,user_shop_last_time_sub_6,user_fisrt_num_6,user_item_fisrt_num_6,user_shop_fisrt_num_6,user_count_first_time_6,user_item_count_first_time_6,user_shop_count_first_time_6,user_count_first_time_sub_6,user_item_count_first_time_sub_6,user_shop_count_first_time_sub_6,max_click_6,is_last_click_6,max_user_item_click_6,is_last_user_item_click_6,max_click_time_6,max_user_item_click_time_6,max_click_time_sub_6,max_user_item_click_time_sub_6,instance_id_full_time,item_category_list_full_time,item_property_list_full_time,predict_category_property_full_time,time_full_time,day_full_time,hour_full_time,minute_full_time,user_query_day_full_time,user_query_day_hour_full_time,user_query_minute_full_time,user_count_full_time,user_day_count_full_time,user_hour_count_full_time,user_minute_count_full_time,user_next_count_full_time,user_last_count_full_time,user_next_time_full_time,user_last_time_full_time,next_time_sub_full_time,last_time_sub_full_time,user_item_num_full_time,user_shop_num_full_time,user_item_day_num_full_time,user_shop_day_num_full_time,user_item_num_next_full_time,user_item_num_last_full_time,user_shop_num_next_full_time,user_shop_num_last_full_time,user_item_next_time_full_time,user_item_last_time_full_time,user_shop_next_time_full_time,user_shop_last_time_full_time,user_item_next_time_sub_full_time,user_item_last_time_sub_full_time,user_shop_next_time_sub_full_time,user_shop_last_time_sub_full_time,user_fisrt_num_full_time,user_item_fisrt_num_full_time,user_shop_fisrt_num_full_time,user_count_first_time_full_time,user_item_count_first_time_full_time,user_shop_count_first_time_full_time,user_count_first_time_sub_full_time,user_item_count_first_time_sub_full_time,user_shop_count_first_time_sub_full_time,max_click_full_time,is_last_click_full_time,max_user_item_click_full_time,is_last_user_item_click_full_time,max_click_time_full_time,max_user_item_click_time_full_time,max_click_time_sub_full_time,max_user_item_click_time_sub_full_time
0,1002640977003914936,4943913163084262584,3801992748557162347,4374800994578205793,7,9,10,17,1493508356721691818,1,1005,2002,3007,1088197280290283759,1536249600,0,5829729320339396622,14,1.000000,13,0.981436,0.980990,0.987401,0,2018-09-07 00:00:00,7,0,5,2,2,1,2,19,3,3,1,1,3.333333,0.500000,2.500000,2.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,77.0,55.0,26.0,0.0,0.0,0.0,25.667487,179,19.888889,9.944444,145.0,0.0,426.0,7564.0,2484989,26039.0,0.0,0.0,0.0,8.0,29558,193.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,2,0.0,2,0.0,1,171,62,8,1,1,1,0.0,1,0,1,1,1,0,0,0,0,0,0.000000,0.105764,0.0,1.189462,0,3,105,70,346,3.0,113.0,108.0,564.0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0,1002640977003914936,2018-09-07 00:00:00,7,0,5,2,2,1,2,19,3,3,1,1,3.333333,0.500000,2.500000,2.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,48.0,43.0,29.0,0.0,0.0,0.0,25.667487,179,19.888889,9.944444,123.0,0.0,272.0,3025.0,664288,9429.0,0.0,0.0,0.0,0.0,3098,26.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,2,0.0,2,0.0,1,171,62,8,1,1,1,0.0,1,0,1,1,1,1,0,0,0,0,0.000000,0.000000,0.0,0.466364,0,3,105,70,346,3.0,92.0,80.0,376.0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0,1002640977003914936,836752724084922533;768579787521575291,367082587220462692;5131280576272319091;8689439...,"836752724084922533:4324484723289924768,3657871...",2018-09-07 00:00:00,7,0,0,2,2,1,0,0,0,0,1,-1,2018-09-07 00:23:35,NaN,1415,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:23:35,2018-09-07 00:00:00,1415,0
1,7563693237648713137,1097656060630949565,8420832032159385750,196257267849351217,7,12,12,20,2535192701541505605,0,1005,2005,3002,4656934049025345586,1536249600,0,1924781308265458391,19,1.000000,18,0.981413,0.981040,0.989620,0,2018-09-07 00:00:00,7,0,5,1,1,1,3,25,1,1,1,0,2.500000,0.000000,5.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3369.0,1275.0,4040.0,2.0,1.0,2.0,35.254001,252,28.000000,14.000000,5376.0,1.0,19723.0,27115.0,4405710,1210626.0,3.0,0.0,30.0,86.0,55540,8360.0,7.0,3.500000,3.500000,0.0,0.0,7.0,6,23,1,0.0,1,0.0,1,723,79,12,1,1,1,0.0,0,0,1,1,0,0,0,0,0,0,0.055804,0.317168,0.0,1.260637,0,52,78,940,5348,85.0,132.0,1189.0,7995.0,1,-1,2018-09-03 13:29:48,NaN,48588,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,7563693237648713137,2018-09-07 00:00:00,7,0,5,1,1,1,3,25,1,1,1,0,2.500000,0.000000,5.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,860.0,304.0,1064.0,0.0,0.0,0.0,35.254001,252,28.000000,14.000000,1413.0,0.0,5612.0,7070.0,1125867,330746.0,0.0,0.0,0.0,2.0,6846,877.0,0.0,0.000000,7.000000,0.0,0.0,7.0,6,23,1,0.0,1,0.0,1,723,79,12,1,1,1,0.0,1,0,1,1,1,0,0,0,0,0,0.000000,0.028289,0.0,0.608065,0,52,78,940,5348,53.0,81.0,952.0,5582.0,1,-1,NaN,NaN,999999,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,7563693237648713137,836752724084922533;3613783563199627217;6370392...,6241534230954727302;367082587220462692;5977512...,"836752724084922533:1405752240728470138,2125982...",2018-09-07 00:00:00,7,0,0,1,1,1,0,0,0,0,1,-1,2018-09-03 13:29:48,NaN,48588,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,0,1,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
2,3325379761110661259,4747706882249246504,6232396831040542357,8519578687848277273,6,14,13,17,8204445143641875432,0,1003,2004,3007,6544635643285905366,1536249600,0,8983666490462246326,23,0.995066,21,0.974091,0.974842,0.967002,0,2018-09-07 00:00:00,7,0,5,2,2,2,2,24,2,1,2,0,6.666667,0.000000,6.666667,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,243.0,410.0,0.0,2.0,2.0,40.298827,235,29.375000,14.687500,546.0,0.0,18742.0,12654.0,412495,71554.0,4.0,0.0,88.0,68.0,4728,563.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,2,0.0,2,0.0,2,364,14,2,1,1,1,0.0,1,0,1,1,0,0,0,0,0,0,0.732601,0.537379,0.0,1.146196,0,176,58,44,509,199.0,72.0,51.0,661.0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,3325379761110661259,2018-09-07 00:00:00,7,0,5,2,2,2,2,24,2,1,2,0,6.666667,0.000000,6.666667,0.000000,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,33.0,328.0,480.0,0.0,0.0,1.0,40.298827,235,29.375000,14.687500,599.0,2.0,10131.0,7157.0,109743,23811.0,1.0,0.0,15.0,13.0,520,65.0,11.0,3.666667,2.333333,0.0,0.0,6.0,6,23,2,0.0,2,0.0,2,364,14,2,1,1,1,0.0,0,0,1,1,0,0,0,0,0,0,0.166945,0.181640,0.0,0.473834,0,176,58,44,509,204.0,65.0,44.0,530.0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,2018-09-06 23:56:27,NaN,2018-09-06 23:56:27,NaN,86187,999999,86187,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,3325379761110661259,836752724084922533;768579787521575291,3540471119339706981;5131280576272319091;302719...,"768579787521575291:3540471119339706981,5131280...",2018-09-07 00:00:00,7,0,0,2,2,2,0,0,0,0,1,-1,2018-09-07 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,2018-09-06 23:56:27,NaN,2018-09-06 23:56:27,NaN,86187,999999,86187,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,1,0,0,1,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0
3,6026863564044534796,6075147184977200133,2143736106091506900,6219110439660858399,6,8,8,16,3370515857303357002,-1,-1,-1,-1,1591753168403833710,1536249600,0,146460612484534365,19,0.979555,17,0.957083,0.958109,0.951751,0,2018-09-07 00:00:00,7,0,5,4,2,2,2,20,6,1,2,0,6.666667,0.000000,2.857143,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,6.0,0.0,0.0,0.0,31.079815,136,17.000000,8.500000,147.0,0.0,6382.0,6861.0,17104,1309878.0,0.0,0.0,63.0,64.0,217,12905.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,4,0.0,2,2.0,2,133,12,1,1,1,1,0.0,1,0,1,1,1,0,0,0,0,0,0.000000,0.932809,0.0,1.268709,0,10,12,1958,6805,14.0,18.0,2497.0,9983.0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0,6026863564044534796,2018-09-07 00:00:00,7,0,5,4,2,2,2,20,6,1,2,0,6.666667,0.000000,2.857143,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,31.079815,136,17.000000,8.500000,80.0,0.0,1257.0,1330.0,4490,342180.0,0.0,0.0,8.0,9.0,45,1554.0,0.0,0.000000,6.000000,0.0,0.0,6.0,6,23,4,0.0,2,2.0,2,133,12,1,1,1,1,0.0,1,0,1,1,1,0,0,0,0,0,0.000000,0.676692,0.0,1.002227,0,10,12,1958,6805,10.0,13.0,1948.0,6822.0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0,6026863564044534796,836752724084922533;1909641874861640857,5977512434884267894;2072967855524022579;263639...,1036082357054043890:-1;8658630417297894718:-1;...,2018-09-07 00:00:00,7,0,0,4,2,2,0,0,0,0,1,-1,2018-09-07 00:00:11,NaN,11,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,3,0,0,1,2018-09-07 23:38:46,2018-09-07 00:00:00,85126,0
4,7074792290685319356,7227779099688226563,8909918568166119776,3122721854741763495,8,13,13,19,4890272292782939403,0,1002,2005,3009,3421390014084173241,1536249600,0,3685789896910492811,17,1.000000,15,0.983497,0.983812,0.986854,0,2018-09-07 00:00:00,7,0,5,3,3,3,2,34,5,2,2,1,6.666667,0.285714,3.333333,3.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,945.0,170.0,1761.0,2.0,0.0,2.0,30.555430,260,26.000000,13.000000,2197.0,2.0,4177.0,4177.0,4405710,133820.0,4.0,0.0,9.0,9.0,55540,1636.0,11.0,3.666667,4.333333,0.0,0.0,8.0,6,23,3,0.0,3,0.0,3,1014,182,15,1,1,1,0.0,0,0,1,1,0,0,0,0,0,0,0.182066,0.215466,0.0,1.260637,0,43,43,152,687,51.0,51.0,190.0,1115.0,1,-1,2018-09-07 00:00:21,NaN,21,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0,7074792290685319356,2018-09-07 00:00:00,7,0,5,3,3,3,2,34,5,2,2,1,6.666667,0.285714,3.333333,3.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,431.0,97.0,796.0,0.0,0.0,0.0,30.555430,260,26.000000,13.000000,1011.0,1.0,2589.0,2589.0,1125867,33116.0,0.0,0.0,2.0,2.0,6846,153.0,6.0,3.000000,5.000000,0.0,0.0,8.0,6,23,3,0.0,3,0.0,3,1014,182,15,1,1,1,0.0,0,0,1,1,1,0,0,0,0,0,0.000000,0.077250,0.0,0.608065,0,43,43,152,687,28.0,28.0,161.0,713.0,1,-1,2018-09-07 00:00:21,NaN,21,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0,7074792290685319356,836752724084922533;768579787521575291,6241534230954727302;3540471119339706981;462193...,768579787521575291:-1;8096917686185033019:9148...,2018-09-07 00:00:00,7,0,0,3,3,3,0,0,0,0,1,-1,2018-09-07 00:00:21,NaN,21,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-07 00:00:00,2018-09-07 00:00:00,2018-09-07 00:00:00,0,0,0,2,0,0,1,2018-09-07 00:00:27,2018-09-07 00:00:00,27,0

In [4]:
origin = [
    'item_price_level', 'item_sales_level', 'item_collected_level',
    'item_pv_level', 'user_gender_id', 'user_age_level', 'user_star_level',
    'context_page_id', 'shop_id', 'shop_review_num_level',
    'shop_review_positive_rate', 'shop_star_level', 'shop_score_service',
    'shop_score_delivery', 'shop_score_description'
]

features_pre5 = [
    'day', 'hour', 'minute', 'user_query_day', 'user_query_day_hour',
    'user_query_minute', 'item_category_split_count',
    'item_property_split_count', 'pred_category_split_count',
    'pred_property_split_count', 'item_pred_category_score',
    'item_pred_property_score', 'item_pred_category_score_item%',
    'item_pred_property_score_item%', 'item_pred_category_score_pred%',
    'item_pred_property_score_pred%', 'user_shop_count', 'user_item_count',
    'user_context_count', 'user_shop_trade_count', 'user_item_trade_count',
    'user_context_trade_count', 'user_brand_count', 'user_city_count',
    'user_brand_trade_count', 'user_city_trade_count', 'item_occupation_count',
    'item_age_count', 'item_gender_count', 'item_occupation_trade_count',
    'item_age_trade_count', 'item_gender_trade_count', 'shop_score',
    'item_score', 'item_score2', 'item_score3', 'item_hot', 'user_hot',
    'shop_hot', 'brand_hot', 'occupation_hot', 'city_hot', 'item_trade_hot',
    'user_trade_hot', 'shop_trade_hot', 'brand_trade_hot',
    'occupation_trade_hot', 'city_trade_hot', 'user_sell_power',
    'user_sell_power_mean', 'user_sell_power_mean_item_minus',
    'user_sell_trade_power', 'user_sell_trade_power_mean',
    'user_sell_trade_power_mean_item_minus', 'yesterday', 'yesterhour',
    'user_day_query', 'user_yesterday_query', 'user_hour_query',
    'user_yesterhour_query', 'user_minute_query', 'item_day_query',
    'item_hour_query', 'item_minute_query', 'user_item_day_query',
    'user_item_hour_query', 'user_item_minute_query', 'min_time',
    'user_is_his', 'item_is_his', 'brand_is_his', 'user_is_trade_his',
    'item_is_trade_his', 'brand_is_trade_his', 'user_count', 'user_day_count',
    'user_hour_count', 'user_minute_count', 'item_trade_percent',
    'brand_trade_percent', 'user_trade_percent', 'occupation_trade_percent',
    'is_home', 'shop_item_count', 'brand_item_count', 'city_brand_count',
    'city_item_count', 'shop_item_count_his', 'brand_item_count_his',
    'city_brand_count_his', 'city_item_count_his', 'next_time_sub',
    'last_time_sub', 'user_item_num', 'user_shop_num', 'user_item_day_num',
    'user_shop_day_num', 'user_item_next_time_sub', 'user_item_last_time_sub',
    'user_shop_next_time_sub', 'user_shop_last_time_sub',
    'user_count_first_time_sub', 'user_item_count_first_time_sub',
    'user_shop_count_first_time_sub', 'max_click', 'is_last_click',
    'max_user_item_click', 'is_last_user_item_click', 'max_click_time_sub',
    'max_user_item_click_time_sub'
]

features_6 = [
    'user_shop_count_6', 'user_item_count_6', 'user_context_count_6',
    'user_shop_trade_count_6', 'user_item_trade_count_6',
    'user_context_trade_count_6', 'user_brand_count_6', 'user_city_count_6',
    'user_brand_trade_count_6', 'user_city_trade_count_6',
    'item_occupation_count_6', 'item_age_count_6', 'item_gender_count_6',
    'item_occupation_trade_count_6', 'item_age_trade_count_6',
    'item_gender_trade_count_6', 'shop_score_6', 'item_score_6',
    'item_score2_6', 'item_score3_6', 'item_hot_6', 'user_hot_6', 'shop_hot_6',
    'brand_hot_6', 'occupation_hot_6', 'city_hot_6', 'item_trade_hot_6',
    'user_trade_hot_6', 'shop_trade_hot_6', 'brand_trade_hot_6',
    'occupation_trade_hot_6', 'city_trade_hot_6', 'user_sell_power_6',
    'user_sell_power_mean_6', 'user_sell_power_mean_item_minus_6',
    'user_sell_trade_power_6', 'user_sell_trade_power_mean_6',
    'user_sell_trade_power_mean_item_minus_6', 'yesterday_6', 'yesterhour_6',
    'user_day_query_6', 'user_yesterday_query_6', 'user_hour_query_6',
    'user_yesterhour_query_6', 'user_minute_query_6', 'item_day_query_6',
    'item_hour_query_6', 'item_minute_query_6', 'user_item_day_query_6',
    'user_item_hour_query_6', 'user_item_minute_query_6', 'min_time_6',
    'user_is_his_6', 'item_is_his_6', 'brand_is_his_6', 'user_is_trade_his_6',
    'item_is_trade_his_6', 'brand_is_trade_his_6', 'user_count_6',
    'user_day_count_6', 'user_hour_count_6', 'user_minute_count_6',
    'item_trade_percent_6', 'brand_trade_percent_6', 'user_trade_percent_6',
    'occupation_trade_percent_6', 'is_home_6', 'shop_item_count_6',
    'brand_item_count_6', 'city_brand_count_6', 'city_item_count_6',
    'shop_item_count_his_6', 'brand_item_count_his_6',
    'city_brand_count_his_6', 'city_item_count_his_6', 'next_time_sub_6',
    'last_time_sub_6', 'user_item_num_6', 'user_shop_num_6',
    'user_item_day_num_6', 'user_shop_day_num_6', 'user_item_next_time_sub_6',
    'user_item_last_time_sub_6', 'user_shop_next_time_sub_6',
    'user_shop_last_time_sub_6', 'user_count_first_time_sub_6',
    'user_item_count_first_time_sub_6', 'user_shop_count_first_time_sub_6',
    'max_click_6', 'is_last_click_6', 'max_user_item_click_6',
    'is_last_user_item_click_6', 'max_click_time_sub_6',
    'max_user_item_click_time_sub_6'
]

features_fulltime = [
    'user_count_full_time', 'user_day_count_full_time',
    'user_hour_count_full_time', 'user_minute_count_full_time',
    'next_time_sub_full_time', 'last_time_sub_full_time',
    'user_item_num_full_time', 'user_shop_num_full_time',
    'user_item_day_num_full_time', 'user_shop_day_num_full_time',
    'user_item_next_time_sub_full_time', 'user_item_last_time_sub_full_time',
    'user_shop_next_time_sub_full_time', 'user_shop_last_time_sub_full_time',
    'user_count_first_time_sub_full_time',
    'user_item_count_first_time_sub_full_time',
    'user_shop_count_first_time_sub_full_time', 'max_click_full_time',
    'is_last_click_full_time', 'max_user_item_click_full_time',
    'is_last_user_item_click_full_time', 'max_user_item_click_time_sub_full_time'
]

target = ['is_trade']

In [5]:
sub_features = []
for i in features_6:
    tmp = str(i[:-2] + '_pre5_6_sub')
    train[tmp] = abs(train[i[:-2]] - train[i])
    sub_features.append(tmp)
len(sub_features)

94

In [13]:
predictors = [
    'brand_hot', 'brand_is_trade_his', 'brand_item_count',
    'brand_item_count_his', 'brand_trade_hot', 'brand_trade_percent',
    'city_brand_count', 'city_brand_count_his', 'city_hot', 'city_item_count',
    'city_item_count_his', 'city_trade_hot', 'hour', 'item_age_trade_count',
    'item_category_split_count', 'item_day_query', 'item_gender_count',
    'item_gender_trade_count', 'item_hot', 'item_is_trade_his',
    'item_minute_query', 'item_occupation_count',
    'item_occupation_trade_count', 'item_pred_category_score',
    'item_pred_category_score_item%', 'item_pred_property_score',
    'item_pred_property_score_item%', 'item_pred_property_score_pred%',
    'item_property_split_count', 'item_trade_hot', 'item_trade_percent',
    'last_time_sub', 'min_time', 'next_time_sub', 'shop_hot',
    'shop_item_count', 'shop_item_count_his', 'shop_score', 'shop_trade_hot',
    'user_brand_count', 'user_city_count', 'user_count', 'user_day_count',
    'user_day_query', 'user_hot', 'user_hour_count', 'user_hour_query',
    'user_is_his', 'user_item_count', 'user_item_day_num',
    'user_item_day_query', 'user_item_hour_query', 'user_item_next_time_sub',
    'user_item_num', 'user_minute_count', 'user_minute_query',
    'user_query_day', 'user_query_day_hour', 'user_query_minute',
    'user_sell_power', 'user_sell_power_mean',
    'user_sell_power_mean_item_minus', 'user_shop_count', 'user_shop_day_num',
    'user_shop_num', 'yesterhour', 'user_item_last_time_sub',
    'user_shop_next_time_sub', 'user_shop_last_time_sub',
    'user_count_first_time_sub', 'user_item_count_first_time_sub',
    'user_shop_count_first_time_sub', 'max_click', 'is_last_click',
    'max_user_item_click', 'is_last_user_item_click', 'max_click_time_sub',
    'max_user_item_click_time_sub', 'user_shop_count_6', 'user_item_count_6',
    'user_brand_count_6', 'user_city_count_6', 'item_gender_count_6',
    'item_occupation_trade_count_6', 'item_age_trade_count_6',
    'item_gender_trade_count_6', 'shop_score_6', 'item_hot_6', 'user_hot_6',
    'shop_hot_6', 'brand_hot_6', 'city_hot_6', 'item_trade_hot_6',
    'shop_trade_hot_6', 'brand_trade_hot_6', 'city_trade_hot_6',
    'user_sell_power_6', 'user_sell_power_mean_6',
    'user_sell_power_mean_item_minus_6', 'yesterhour_6', 'user_day_query_6',
    'user_hour_query_6', 'user_minute_query_6', 'item_day_query_6',
    'item_minute_query_6', 'user_item_day_query_6', 'user_item_hour_query_6',
    'min_time_6', 'user_is_his_6', 'item_is_trade_his_6',
    'brand_is_trade_his_6', 'user_count_6', 'user_day_count_6',
    'user_hour_count_6', 'user_minute_count_6', 'item_trade_percent_6',
    'brand_trade_percent_6', 'shop_item_count_6', 'brand_item_count_6',
    'city_brand_count_6', 'city_item_count_6', 'shop_item_count_his_6',
    'brand_item_count_his_6', 'city_brand_count_his_6',
    'city_item_count_his_6', 'next_time_sub_6', 'last_time_sub_6',
    'user_item_num_6', 'user_shop_num_6', 'user_item_day_num_6',
    'user_shop_day_num_6', 'user_item_next_time_sub_6',
    'user_item_last_time_sub_6', 'user_shop_next_time_sub_6',
    'user_shop_last_time_sub_6', 'user_count_first_time_sub_6',
    'user_item_count_first_time_sub_6', 'user_shop_count_first_time_sub_6',
    'max_click_6', 'is_last_click_6', 'max_user_item_click_6',
    'is_last_user_item_click_6', 'max_click_time_sub_6',
    'max_user_item_click_time_sub_6', 'user_count_full_time',
    'user_day_count_full_time', 'user_hour_count_full_time',
    'user_minute_count_full_time', 'next_time_sub_full_time',
    'last_time_sub_full_time', 'user_item_num_full_time',
    'user_shop_num_full_time', 'user_item_day_num_full_time',
    'user_shop_day_num_full_time', 'user_item_next_time_sub_full_time',
    'user_item_last_time_sub_full_time', 'user_shop_next_time_sub_full_time',
    'user_shop_last_time_sub_full_time', 'user_count_first_time_sub_full_time',
    'user_item_count_first_time_sub_full_time',
    'user_shop_count_first_time_sub_full_time', 'max_click_full_time',
    'is_last_click_full_time', 'max_user_item_click_full_time',
    'is_last_user_item_click_full_time',
    'max_user_item_click_time_sub_full_time', 'user_shop_count_pre5_6_sub',
    'user_item_count_pre5_6_sub', 'user_brand_count_pre5_6_sub',
    'item_occupation_count_pre5_6_sub', 'item_gender_count_pre5_6_sub',
    'item_occupation_trade_count_pre5_6_sub',
    'item_age_trade_count_pre5_6_sub', 'item_gender_trade_count_pre5_6_sub',
    'item_hot_pre5_6_sub', 'user_hot_pre5_6_sub', 'shop_hot_pre5_6_sub',
    'brand_hot_pre5_6_sub', 'city_hot_pre5_6_sub', 'item_trade_hot_pre5_6_sub',
    'user_trade_hot_pre5_6_sub', 'shop_trade_hot_pre5_6_sub',
    'brand_trade_hot_pre5_6_sub', 'city_trade_hot_pre5_6_sub',
    'user_sell_power_pre5_6_sub', 'user_sell_power_mean_pre5_6_sub',
    'user_sell_power_mean_item_minus_pre5_6_sub',
    'brand_is_trade_his_pre5_6_sub', 'item_trade_percent_pre5_6_sub',
    'brand_trade_percent_pre5_6_sub', 'shop_item_count_his_pre5_6_sub',
    'brand_item_count_his_pre5_6_sub', 'city_brand_count_his_pre5_6_sub',
    'city_item_count_his_pre5_6_sub', 'next_time_sub_pre5_6_sub',
    'user_item_next_time_sub_pre5_6_sub', 'user_shop_next_time_sub_pre5_6_sub'
]

len(predictors)

197

In [8]:
test = train[train.is_trade == -1]
val = train[(train.is_trade != -1) & (train.hour >= 10) & (train.hour <= 12)]
train = train[(train.is_trade != -1) & (train.hour < 10)]

test.shape
val.shape
train.shape

(519888, 435)

(269737, 435)

(807438, 435)

In [9]:
#cv
params = {
    'objective': 'binary:logistic',
    'eta': 0.05,
    'colsample_bytree': 0.886,
    'min_child_weight': 1.6,
    'max_depth': 4,
    'subsample': 0.886,
    'gamma': 0.1,
    'lambda': 10,
    'verbose_eval': True,
    'eval_metric': 'logloss',
    'seed': 201803,
    'missing': -1
}

predictors = list(set(predictors + origin))
len(predictors)

xgbtrain = xgb.DMatrix(train[predictors], train[target])

print('Start training')
cv = xgb.cv(
    params,
    dtrain=xgbtrain,
    num_boost_round=5000,
    nfold=3,
    verbose_eval=100,
    early_stopping_rounds=50,
    seed=201803)
print(str(cv.shape[0]) + ':' + str(cv.iloc[-1, :]['test-logloss-mean']))
print('End training')
# 0.170316(241) 0.05*1351
# 0.170302333333(335) 0.05*1228
# 0.170319333333(粗筛) 0.05*1209
# 0.170318(细筛) 0.05*1178

212

Start training
[0]	train-logloss:0.652966+1.52971e-05	test-logloss:0.652968+7.03957e-06
[100]	train-logloss:0.176014+0.000233641	test-logloss:0.176728+0.000421433
[200]	train-logloss:0.172758+0.000241159	test-logloss:0.174421+0.000392249
[300]	train-logloss:0.171232+0.000239318	test-logloss:0.173734+0.000375244
[400]	train-logloss:0.170062+0.000226221	test-logloss:0.173381+0.000370629
[500]	train-logloss:0.169074+0.000212719	test-logloss:0.17319+0.000377873
[600]	train-logloss:0.168203+0.000215988	test-logloss:0.17309+0.000378045
[700]	train-logloss:0.167382+0.000220059	test-logloss:0.173028+0.000381113
[800]	train-logloss:0.1666+0.000227932	test-logloss:0.172978+0.00038055
[900]	train-logloss:0.16589+0.00022387	test-logloss:0.172954+0.000369474
943:0.172946666667
End training

In [16]:
predictors = origin + features_pre5 + features_6 + features_fulltime + sub_features
len(predictors)
len(set(predictors) & set(train.columns))

335

335

In [10]:
#train/test
params = {
    'objective': 'binary:logistic',
    'eta': 0.05,
    'colsample_bytree': 0.886,
    'min_child_weight': 1.6,
    'max_depth': 4,
    'subsample': 0.886,
    'gamma': 0.1,
    'lambda': 10,
    'verbose_eval': True,
    'eval_metric': 'logloss',
    'seed': 201803,
    'missing': -1
}

len(predictors)

xgbtrain = xgb.DMatrix(train[predictors], train[target])
model = xgb.train(params, xgbtrain, num_boost_round=943)

# xgbtest = xgb.DMatrix(test[predictors])
# y_pred = model.predict(xgbtest)
xgbval = xgb.DMatrix(val[predictors])
y_pred = model.predict(xgbval)

# idx = test.instance_id.reset_index()
# idx['predicted_score'] = y_pred
# idx[['instance_id', 'predicted_score']].to_csv(
#     'resultWithHistory_round(335).txt',
#     sep=' ',
#     header=['instance_id', 'predicted_score'],
#     index=False)

212

In [11]:
val['pred'] = list(y_pred)
val[['instance_id', 'pred']].to_csv('pred_model1.csv', index=None)

In [18]:
test_order = pd.read_csv('round2_ijcai_18_test_a_20180425.txt', sep=' ')
test_order = test_order.merge(idx[['instance_id', 'predicted_score']], on=['instance_id'], how='left')

test_order[['instance_id', 'predicted_score']].to_csv(
    'resultWithHistory_round(335_order).txt',
    sep=' ',
    header=['instance_id', 'predicted_score'],
    index=False)

In [19]:
len(y_pred)
idx.shape
idx.head()
test_order.shape
test_order[['instance_id', 'predicted_score']].head()

519888

(519888, 3)

     index          instance_id  predicted_score
0  1077175  1781317115815731318         0.060691
1  1077176  6116634221596372212         0.030702
2  1077177  6875831956810295589         0.013262
3  1077178  6990128147973947372         0.019544
4  1077179  6731403233620820223         0.110400

(519888, 27)

       instance_id  predicted_score
0   93294255633855         0.058890
1  558322259509454         0.010348
2  594573634113186         0.037818
3  667327653735176         0.038146
4  697732672924394         0.042160

# Model2

In [10]:
train_model2 = pd.read_csv('tr_preprocessing_model2_pre4b.csv')
train_model2_fulltime = pd.read_csv('tr_preprocessing_model2_fulltimeb.csv')

train_model2.shape
train_model2.head()
train_model2_fulltime.shape
train_model2_fulltime.head()

(5164691, 155)

,instance_id,item_id,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,time,day,hour,minute,user_query_day,user_query_day_hour,user_query_minute,item_category_split_count,item_property_split_count,pred_category_split_count,pred_property_split_count,item_pred_category_score,item_pred_property_score,item_pred_category_score_item%,item_pred_property_score_item%,item_pred_category_score_pred%,item_pred_property_score_pred%,user_shop_count,user_item_count,user_context_count,user_shop_trade_count,user_item_trade_count,user_context_trade_count,user_brand_count,user_city_count,user_brand_trade_count,user_city_trade_count,item_occupation_count,item_age_count,item_gender_count,item_occupation_trade_count,item_age_trade_count,item_gender_trade_count,shop_score,item_score,item_score2,item_score3,item_hot,user_hot,shop_hot,brand_hot,occupation_hot,city_hot,item_trade_hot,user_trade_hot,shop_trade_hot,brand_trade_hot,occupation_trade_hot,city_trade_hot,user_sell_power,user_sell_power_mean,user_sell_power_mean_item_minus,user_sell_trade_power,user_sell_trade_power_mean,user_sell_trade_power_mean_item_minus,yesterday,yesterhour,user_day_query,user_yesterday_query,user_hour_query,user_yesterhour_query,user_minute_query,item_day_query,item_hour_query,item_minute_query,user_item_day_query,user_item_hour_query,user_item_minute_query,min_time,user_is_his,item_is_his,brand_is_his,user_is_trade_his,item_is_trade_his,brand_is_trade_his,item_trade_percent,brand_trade_percent,user_trade_percent,occupation_trade_percent,is_home,shop_item_count,brand_item_count,city_brand_count,city_item_count,shop_item_count_his,brand_item_count_his,city_brand_count_his,city_item_count_his,user_count,user_day_count,user_hour_count,user_minute_count,user_next_count,user_last_count,user_next_time,user_last_time,next_time_sub,last_time_sub,user_item_num,user_shop_num,user_item_day_num,user_shop_day_num,user_item_num_next,user_item_num_last,user_shop_num_next,user_shop_num_last,user_item_next_time,user_item_last_time,user_shop_next_time,user_shop_last_time,user_item_next_time_sub,user_item_last_time_sub,user_shop_next_time_sub,user_shop_last_time_sub,user_fisrt_num,user_item_fisrt_num,user_shop_fisrt_num,user_count_first_time,user_item_count_first_time,user_shop_count_first_time,user_count_first_time_sub,user_item_count_first_time_sub,user_shop_count_first_time_sub,max_click,is_last_click,max_user_item_click,is_last_user_item_click,max_click_time,max_user_item_click_time,max_click_time_sub,max_user_item_click_time_sub
0,141832830997226270,7359303084916720285,5631250215466519070,7534238860363577544,6,15,15,17,5603784582591486743,-1,1000,2005,3001,9213680238923972016,1535990400,1,4134879672586982774,18,0.996117,16,0.962431,0.958869,0.959592,0,2018-09-04 00:00:00,4,0,5,1,1,1,3,70,4,4,2,1,5.000000,0.140845,4.000000,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,959.0,46.0,44.0,43.0,0.0,0.0,30.046967,270,33.750000,11.250000,1338.0,1.0,3031.0,1437.0,2997852,208574.0,66.0,0.0,124.0,67.0,40047,3966.0,7.0,3.500000,2.500000,0.0,0.0,6.0,3,23,1,0.0,1,0.0,1,203,2,1,1,1,1,0.0,0,0,1,1,0,0,4.932735,4.662491,0.0,1.335856,0,5,6,561,2714,5.0,5.0,569.0,2634.0,0,0,0,0,1,-1,2018-09-04 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-01 19:54:11,2018-09-04 00:00:00,2018-09-04 00:00:00,14749,0,0,0,1,0,1,2018-09-04 00:00:00,2018-09-04 00:00:00,0,0
1,590920614464250290,8881909419334931441,4705482073675971767,1019055478500227370,7,13,16,22,3859049292494974351,0,1006,2002,3002,1416415346500941023,1535990400,0,5947226530120998462,18,1.000000,16,0.967846,0.969209,0.976134,0,2018-09-04 00:00:00,4,0,5,1,1,1,2,43,2,1,2,1,6.666667,0.227273,6.666667,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3078.0,357.0,6679.0,27.0,6.0,52.0,31.132365,365,40.555556,20.277778,8557.0,0.0,9225.0,9225.0,1702859,421956.0,68.0,0.0,79.0,79.0,21677,5992.0,0.0,0.000000,7.000000,0.0,0.0,7.0,3,23,1,0.0,1,0.0,1,2786,41,11,1,1,1,0.0,1,0,1,1,0,0,0.794671,0.856369,0.0,1.272977,0,3,3,926,6553,3.0,3.0,916.0,6404.0,0,0,0,0,1,-1,NaN,NaN,999999,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-04 00:00:00,2018-09-04 00:00:00,2018-09-04 00:00:00,0,0,0,0,1,0,1,2018-09-04 00:00:00,2018-09-04 00:00:00,0,0
2,8274988120765843024,5806392056010953222,6986537875200332659,196257267849351217,7,12,15,21,4829202368741791671,0,1006,2005,3000,2588323872794207953,1535990400,0,3910379687645822028,21,1.000000,19,0.978998,0.981289,0.982634,0,2018-09-04 00:00:00,4,0,5,2,2,2,3,43,2,1,1,0,2.500000,0.000000,3.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2994.0,392.0,5665.0,5.0,0.0,9.0,37.759857,327,36.333333,18.166667,7026.0,1.0,101729.0,104927.0,2997852,825857.0,11.0,0.0,53.0,61.0,40047,6213.0,7.0,3.500000,3.500000,0.0,0.0,7.0,3,23,2,0.0,2,0.0,2,1892,75,26,1,1,1,0.0,0,0,1,1,0,0,0.156561,0.058136,0.0,1.335856,0,715,818,1156,7503,704.0,806.0,1102.0,7128.0,0,0,0,0,1,-1,2018-09-04 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,2018-09-04 00:00:00,NaN,999999,999999,0,999999,0,0,0,2018-08-31 15:24:34,2018-09-04 00:00:00,2018-09-04 00:00:00,30926,0,0,3,0,0,1,2018-09-07 15:19:40,2018-09-04 00:00:00,55180,0
3,3168805145622878188,873639012512938724,3278298609936947467,6219110439660858399,9,6,10,15,5249969673780098660,0,1003,2002,3008,1229276498646649308,1535990400,16,8608531554386229235,17,1.000000,15,0.978186,0.976467,0.984106,0,2018-09-04 00:00:00,4,0,5,1,1,1,3,22,6,2,3,0,7.500000,0.000000,4.285714,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,53.0,69.0,125.0,0.0,0.0,0.0,30.079509,156,14.181818,0.787879,148.0,3.0,4244.0,4678.0,1702859,894646.0,0.0,0.0,3.0,4.0,21677,9391.0,28.0,7.000000,2.000000,0.0,0.0,9.0,3,23,1,0.0,1,0.0,1,58,1,1,1,1,1,0.0,0,0,1,1,1,0,0.000000,0.085507,0.0,1.272977,0,20,26,2441,9325,17.0,25.0,2325.0,8957.0,0,0,0,0,1,-1,2018-09-03 23:58:52,NaN,86332,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-03 23:57:06,2018-09-04 00:00:00,2018-09-04 00:00:00,174,0,0,9,0,0,1,2018-09-07 14:49:03,2018-09-04 00:00:00,53343,0
4,4811858053894378966,4758769524630365053,5390915051549817288,196257267849351217,8,12,17,21,7187733876813247686,0,1003,2005,3006,2476769382213195482,1535990400,0,3377660265655473170,20,1.000000,18,0.978100,0.979769,0.981270,0,2018-09-04 00:00:00,4,0,5,1,1,1,3,50,1,1,1,0,2.500000,0.000000,5.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,6.0,0.0,0.0,2552.0,2667.0,4502.0,1.0,1.0,4.0,35.733791,369,36.900000,18.450000,5658.0,8.0,48938.0,49488.0,2997852,825857.0,4.0,0.0,24.0,27.0,40047,6213.0,57.0,6.333333,1.666667,0.0,0.0,8.0,3,23,1,0.0,1,0.0,1,533,2,2,1,1,1,0.0,0,0,1,1,0,0,0.070696,0.054559,0.0,1.335856,0,60,68,1156,7503,61.0,72.0,1102.0,7128.0,0,0,0,0,1,-1,2018-09-02 11:16:14,NaN,40574,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,2018-09-04 00:00:00,NaN,999999,999999,0,999999,0,0,0,2018-09-02 11:14:45,2018-09-04 00:00:00,2018-09-02 11:24:46,45915,0,45314,3,0,0,1,2018-09-07 00:29:14,2018-09-04 00:00:00,1754,0

(5164691, 77)

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_id,user_gender_id,user_age_level,user_occupation_id,user_star_level,context_id,context_timestamp,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,time,day,hour,minute,user_query_day,user_query_day_hour,user_query_minute,user_count,user_day_count,user_hour_count,user_minute_count,user_next_count,user_last_count,user_next_time,user_last_time,next_time_sub,last_time_sub,user_item_num,user_shop_num,user_item_day_num,user_shop_day_num,user_item_num_next,user_item_num_last,user_shop_num_next,user_shop_num_last,user_item_next_time,user_item_last_time,user_shop_next_time,user_shop_last_time,user_item_next_time_sub,user_item_last_time_sub,user_shop_next_time_sub,user_shop_last_time_sub,user_fisrt_num,user_item_fisrt_num,user_shop_fisrt_num,user_count_first_time,user_item_count_first_time,user_shop_count_first_time,user_count_first_time_sub,user_item_count_first_time_sub,user_shop_count_first_time_sub,max_click,is_last_click,max_user_item_click,is_last_user_item_click,max_click_time,max_user_item_click_time,max_click_time_sub,max_user_item_click_time_sub
0,141832830997226270,7359303084916720285,836752724084922533;2871729383671301763;3492642...,4621934203383159480;3145741777362890024;316326...,5631250215466519070,7534238860363577544,6,15,15,17,5603784582591486743,-1,1000,2005,3001,9213680238923972016,1535990400,4002,3492642177859571113:9011444777478954178;667052...,4134879672586982774,18,0.996117,5015,0.962431,0.958869,0.959592,0,2018-09-04 00:00:00,4,0,0,1,1,1,0,0,0,0,1,-1,2018-09-04 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-01 19:54:11,2018-09-04 00:00:00,2018-09-04 00:00:00,14749,0,0,0,1,0,1,2018-09-04 00:00:00,2018-09-04 00:00:00,0,0
1,590920614464250290,8881909419334931441,836752724084922533;6693726201323251689,4621934203383159480;3163265386149801264;734498...,4705482073675971767,1019055478500227370,7,13,16,22,3859049292494974351,0,1006,2002,3002,1416415346500941023,1535990400,4001,6693726201323251689:-1;836752724084922533:1972...,5947226530120998462,18,1.000000,5015,0.967846,0.969209,0.976134,0,2018-09-04 00:00:00,4,0,0,1,1,1,0,0,0,0,1,-1,2018-09-06 12:46:28,NaN,45988,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-06 12:46:06,2018-09-04 00:00:00,2018-09-04 00:00:00,40434,0,0,0,1,0,1,2018-09-04 00:00:00,2018-09-04 00:00:00,0,0
2,8274988120765843024,5806392056010953222,836752724084922533;3613783563199627217;1036082...,6241534230954727302;367082587220462692;5977512...,6986537875200332659,196257267849351217,7,12,15,21,4829202368741791671,0,1006,2005,3000,2588323872794207953,1535990400,4001,3348197449185791127:-1;836752724084922533:2962...,3910379687645822028,21,1.000000,5018,0.978998,0.981289,0.982634,0,2018-09-04 00:00:00,4,0,0,2,2,2,0,0,0,0,1,-1,2018-09-04 00:00:00,NaN,0,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,2018-09-04 00:00:00,NaN,999999,999999,0,999999,0,0,0,2018-08-31 15:24:34,2018-09-04 00:00:00,2018-09-04 00:00:00,30926,0,0,3,0,0,1,2018-09-07 15:19:40,2018-09-04 00:00:00,55180,0
3,3168805145622878188,873639012512938724,836752724084922533;5685690139879409547;7497531...,6241534230954727302;367082587220462692;2636395...,3278298609936947467,6219110439660858399,9,6,10,15,5249969673780098660,0,1003,2002,3008,1229276498646649308,1535990400,4017,7497531498747093265:-1;8077497621372666304:-1;...,8608531554386229235,17,1.000000,5014,0.978186,0.976467,0.984106,0,2018-09-04 00:00:00,4,0,0,1,1,1,0,0,0,0,1,-1,2018-09-03 23:58:52,NaN,86332,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,NaN,NaN,999999,999999,999999,999999,0,0,0,2018-09-03 23:57:06,2018-09-04 00:00:00,2018-09-04 00:00:00,174,0,0,9,0,0,1,2018-09-07 14:49:03,2018-09-04 00:00:00,53343,0
4,4811858053894378966,4758769524630365053,836752724084922533;5685690139879409547;7497531...,6241534230954727302;5131280576272319091;263639...,5390915051549817288,196257267849351217,8,12,17,21,7187733876813247686,0,1003,2005,3006,2476769382213195482,1535990400,4001,"836752724084922533:3453233748255132286,7213917...",3377660265655473170,20,1.000000,5017,0.978100,0.979769,0.981270,0,2018-09-04 00:00:00,4,0,0,1,1,1,0,0,0,0,1,-1,2018-09-02 11:16:14,NaN,40574,999999,0,0,0,0,1,-1,1,-1,NaN,NaN,2018-09-04 00:00:00,NaN,999999,999999,0,999999,0,0,0,2018-09-02 11:14:45,2018-09-04 00:00:00,2018-09-02 11:24:46,45915,0,45314,3,0,0,1,2018-09-07 00:29:14,2018-09-04 00:00:00,1754,0

In [3]:
# train_model2_cjy = pd.read_csv('cjy_goodfeas_457th_05_11.csv')

# train_model2_cjy.shape
# train_model2_cjy.head()

(5164691, 21)

,instance_id,item_cat_vec0,item_cat_vec1,item_cat_vec2,item_cat_vec3,item_cat_vec4,item_cat_vec5,item_cat_vec6,item_cat_vec7,item_cat_vec8,item_cat_vec9,item_cat_vec10,item_cat_vec11,item_cat_vec12,item_cat_vec13,item_cat_vec14,item_cat_vec15,shop_item_cnt,shop_brand_cnt,item_pred_cat_cos,item_pred_ppt_cos
0,135318204268396,3.923043,21.191767,-6.776930,-3.605523,-2.918667,-7.421790,5.295996,5.052433,0.000461,-1.280783,-0.163851,2.246237,2.015467,0.266977,4.850313,-5.827004,39,1,0.766765,0.452022
1,467064713704441,25.073053,76.867767,-3.083711,59.983883,41.272203,30.524767,-14.909112,-16.287827,25.732607,14.769645,-25.178250,15.196313,43.804878,-38.757003,62.843380,-77.139267,3,1,0.797558,0.366451
2,479649319359792,1.223688,1.798606,-1.217799,1.965156,-1.405942,-0.808671,0.418516,-1.047460,0.623090,-2.297618,-1.298148,1.435356,-0.009850,-1.264188,1.376216,-0.463102,6,1,1.000000,0.132716
3,535627308908402,2.908267,9.944833,-1.211511,7.402290,2.134520,-0.008112,0.583675,-2.904420,4.403877,-1.935972,-5.021527,3.271667,3.519664,-3.624803,2.993237,-4.022160,24,1,0.991071,0.443928
4,561801501778309,2.858350,4.592705,-1.961135,3.922060,-2.210635,-1.789895,1.161689,-2.530705,0.787896,-4.328265,-2.049780,2.218760,0.081945,-1.977165,2.771605,-0.868366,8,1,0.999703,0.444669

In [4]:
# features_cjy = list(train_model2_cjy.columns)
# features_cjy.remove('instance_id')

In [12]:
drop_col = [
    'day', 'user_hour_count', 'user_item_fisrt_num', 'user_minute_count',
    'item_collected_level', 'item_id', 'user_item_last_time', 'user_day_count',
    'user_gender_id', 'user_shop_count_first_time', 'item_pv_level',
    'user_item_num_next', 'shop_id', 'max_user_item_click_time',
    'user_query_day', 'shop_star_level', 'shop_score_service',
    'user_shop_next_time', 'user_last_time', 'context_timestamp',
    'user_count_first_time', 'user_shop_num_next', 'user_fisrt_num',
    'user_query_minute', 'max_click_time', 'context_id', 'is_trade', 'hour',
    'user_occupation_id', 'item_price_level', 'user_next_count',
    'item_brand_id', 'shop_review_positive_rate', 'user_next_time',
    'user_star_level', 'item_city_id', 'user_id', 'user_count',
    'user_last_count', 'user_query_day_hour', 'user_item_next_time',
    'user_item_num_last', 'user_age_level', 'user_shop_fisrt_num',
    'item_sales_level', 'user_item_num', 'user_item_count_first_time',
    'user_shop_last_time', 'context_page_id', 'shop_score_delivery',
    'shop_review_num_level', 'shop_score_description', 'time', 'minute',
    'user_shop_num_last', 'item_category_list', 'item_property_list',
    'predict_category_property'
]

train_model2_fulltime = train_model2_fulltime.drop(drop_col, axis=1)
# val_model2_fulltime = val_model2_fulltime.drop(drop_col, axis=1)

In [13]:
train_model2_fulltime_col = []
for i in train_model2_fulltime.columns:
    train_model2_fulltime_col.append(i + '_full_time')
    
train_model2_fulltime.columns = train_model2_fulltime_col
# val_model2_fulltime.columns = train_model2_fulltime_col
# train_model2_fulltime.head()

In [14]:
train = train_model2.merge(train_model2_fulltime, left_on=['instance_id'], right_on=['instance_id_full_time'], how='left')
# val = val_model2.merge(val_model2_fulltime, left_on=['instance_id'], right_on=['instance_id_fulltime'], how='left')

In [15]:
train.to_csv('train_zero_model2_b.csv', index=None)
# val.to_csv('val_zero_model2.csv', index=None)

del train_model2
del train_model2_fulltime
# del val_model2
# del val_model2_fulltime

In [5]:
train = pd.read_csv('train_zero_model2.csv', usecols=no_leak_feature)

train.shape
train.head()

(2877748, 120)

,instance_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,user_gender_id,user_age_level,user_star_level,context_page_id,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade,day,hour,minute,user_query_day,user_query_day_hour,user_query_minute,item_category_split_count,item_property_split_count,pred_category_split_count,pred_property_split_count,item_pred_category_score,item_pred_property_score,item_pred_category_score_item%,item_pred_property_score_item%,item_pred_category_score_pred%,item_pred_property_score_pred%,user_shop_count,user_item_count,user_context_count,user_brand_count,user_city_count,item_occupation_count,item_age_count,item_gender_count,shop_score,item_score,item_score2,item_score3,item_hot,user_hot,shop_hot,brand_hot,occupation_hot,city_hot,user_sell_power,user_sell_power_mean,user_sell_power_mean_item_minus,yesterday,yesterhour,user_day_query,user_yesterday_query,user_hour_query,user_yesterhour_query,user_minute_query,item_day_query,item_hour_query,item_minute_query,user_item_day_query,user_item_hour_query,user_item_minute_query,min_time,user_is_his,item_is_his,brand_is_his,is_home,shop_item_count,brand_item_count,city_brand_count,city_item_count,shop_item_count_his,brand_item_count_his,city_brand_count_his,city_item_count_his,user_count,user_day_count,user_hour_count,user_minute_count,next_time_sub,last_time_sub,user_item_num,user_shop_num,user_item_day_num,user_shop_day_num,user_item_next_time_sub,user_item_last_time_sub,user_shop_next_time_sub,user_shop_last_time_sub,user_count_first_time_sub,user_item_count_first_time_sub,user_shop_count_first_time_sub,max_click,is_last_click,max_user_item_click,is_last_user_item_click,max_click_time_sub,max_user_item_click_time_sub,next_time_sub_full_time,last_time_sub_full_time,user_shop_num_full_time,user_item_day_num_full_time,user_shop_day_num_full_time,user_item_next_time_sub_full_time,user_item_last_time_sub_full_time,user_shop_next_time_sub_full_time,user_shop_last_time_sub_full_time,user_count_first_time_sub_full_time,user_item_count_first_time_sub_full_time,user_shop_count_first_time_sub_full_time,max_click_full_time,is_last_click_full_time,max_user_item_click_full_time,is_last_user_item_click_full_time,max_user_item_click_time_sub_full_time
0,3301974838081842019,6,10,12,16,0,1004,3002,10,3697448581765982326,18,1.0,16,0.974200,0.974506,0.980671,0,4,0,5,5,5,5,2,25,1,1,1,0,3.333333,0.000000,5.000000,0.000000,0.0,0.0,0.0,0.0,0.0,75.0,59.0,111.0,31.654479,202,25.250000,2.104167,139.0,0.0,1996.0,1996.0,2997852,93033.0,0.0,0.00,6.00,3,23,5,0.0,5,0.0,5,39,3,2,1,1,1,0.0,1,0,1,0,13,13,167,870,16.0,16.0,182.0,978.0,0,0,0,0,137,999999,0,0,0,0,999999,999999,999999,999999,0,0,0,4,0,0,1,446,0,137,999999,0,0,0,999999,999999,999999,999999,0,0,0,4,0,0,1,0
1,540197740040353487,8,10,15,19,0,1006,3000,0,3910379687645822028,21,1.0,19,0.978998,0.981289,0.982634,0,4,0,5,2,2,2,2,25,2,1,1,0,3.333333,0.000000,3.333333,0.000000,0.0,0.0,0.0,0.0,0.0,688.0,53.0,1072.0,37.759857,295,29.500000,14.750000,1285.0,1.0,101729.0,104927.0,2997852,825857.0,7.0,3.50,4.50,3,23,2,0.0,2,0.0,2,253,7,3,1,1,1,0.0,0,0,1,0,589,668,1062,6553,704.0,806.0,1102.0,7128.0,0,0,0,0,0,999999,0,0,0,0,999999,999999,0,999999,0,0,0,1,0,0,1,0,0,0,999999,0,0,0,999999,999999,0,999999,0,0,0,1,0,0,1,0
2,3168805145622878188,9,6,10,15,0,1003,3008,16,8608531554386229235,17,1.0,15,0.978186,0.976467,0.984106,0,4,0,5,1,1,1,3,22,6,2,3,0,7.500000,0.000000,4.285714,0.000000,0.0,0.0,0.0,0.0,0.0,53.0,69.0,125.0,30.079509,156,14.181818,0.787879,148.0,3.0,4244.0,4678.0,1702859,894646.0,28.0,7.00,2.00,3,23,1,0.0,1,0.0,1,58,1,1,1,1,1,0.0,0,0,1,0,19,25,2239,8138,17.0,25.0,2325.0,8957.0,0,0,0,0,52614,999999,0,0,0,0,999999,999999,999999,999999,0,0,0,4,0,0,1,53343,0,52614,999999,0,0,0,999999,999999,999999,999999,0,0,0,4,0,0,1,0
3,3729208652705676332,8,10,15,21,0,1003,3003,10,3910379687645822028,21,1.0,19,0.978998,0.981289,0.982634,0,4,0,5,3,3,3,3,18,3,2,2,1,5.000000,0.526316,5.000000,3.333333,0.0,0.0,0.0,0.0,0.0,2641.0,2399.0,4850.0,37.759857,325,32.500000,2.708333,5821.0,3.0,101729.0,104927.0,2997852,825857.0,21.0,5.25,2.75,3,23,3,0.0,3,0.0,3,935,44,13,1,1,1,0.0,0,0,1,0,589,668,1062,6553,704.0,806.0,1102.0,7128.0,0,0,0,0,208,999999,0,0,0,0,999999,999999,999999,999999,0,0,0,2,0,0,1,432,0,208,999999,0,0,0,999999,999999,999999,999999,0,0,0,2,0,0,1,0
4,4837242473436970219,7,-1,13,17,0,1005,3007,1,8595315798269462858,20,1.0,18,0.981356,0.982242,0.987758,0,4,0,5,1,1,1,3,19,6,1,2,0,5.000000,0.000000,2.857143,0.000000,0.0,0.0,0.0,0.0,0.0,283.0,116.0,510.0,36.180890,220,24.444444,8.148148,591.0,0.0,12580.0,12918.0,1702859,247441.0,0.0,0.00,7.00,3,23,1,0.0,1,0.0,1,161,6,1,1,1,1,0.0,1,0,1,0,176,222,735,3529,174.0,212.0,788.0,3838.0,0,0,0,0,999999,999999,0,0,0,0,999999,999999,999999,999999,0,0,0,0,1,0,1,0,0,999999,999999,0,0,0,999999,999999,999999,999999,0,0,0,0,1,0,1,0

In [7]:
train = train_model2.merge(train_model2_cjy, on=['instance_id'], how='left')

del train_model2
del train_model2_cjy
gc.collect()

58

In [ ]:
train.to_csv('tr_mix2(zerocjy_b).csv', index=None)

In [8]:
import sys
sys.path.append('/Users/zero/xgboost/python-package')
import xgboost as xgb
import gc
# import lightgbm as lgb

from sklearn.model_selection import GridSearchCV
from sklearn.cross_validation import KFold
from sklearn.metrics import log_loss

/opt/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [10]:
origin = [
    'item_price_level', 'item_sales_level', 'item_collected_level',
    'item_pv_level', 'user_gender_id', 'user_age_level', 'user_star_level',
    'context_page_id', 'shop_id', 'shop_review_num_level',
    'shop_review_positive_rate', 'shop_star_level', 'shop_score_service',
    'shop_score_delivery', 'shop_score_description'
]

features = [
    'day', 'hour', 'minute', 'user_query_day', 'user_query_day_hour',
    'user_query_minute', 'item_category_split_count',
    'item_property_split_count', 'pred_category_split_count',
    'pred_property_split_count', 'item_pred_category_score',
    'item_pred_property_score', 'item_pred_category_score_item%',
    'item_pred_property_score_item%', 'item_pred_category_score_pred%',
    'item_pred_property_score_pred%', 'user_shop_count', 'user_item_count',
    'user_context_count', 'user_shop_trade_count', 'user_item_trade_count',
    'user_context_trade_count', 'user_brand_count', 'user_city_count',
    'user_brand_trade_count', 'user_city_trade_count', 'item_occupation_count',
    'item_age_count', 'item_gender_count', 'item_occupation_trade_count',
    'item_age_trade_count', 'item_gender_trade_count', 'shop_score',
    'item_score', 'item_score2', 'item_score3', 'item_hot', 'user_hot',
    'shop_hot', 'brand_hot', 'occupation_hot', 'city_hot', 'item_trade_hot',
    'user_trade_hot', 'shop_trade_hot', 'brand_trade_hot',
    'occupation_trade_hot', 'city_trade_hot', 'user_sell_power',
    'user_sell_power_mean', 'user_sell_power_mean_item_minus',
    'user_sell_trade_power', 'user_sell_trade_power_mean',
    'user_sell_trade_power_mean_item_minus', 'yesterday', 'yesterhour',
    'user_day_query', 'user_yesterday_query', 'user_hour_query',
    'user_yesterhour_query', 'user_minute_query', 'item_day_query',
    'item_hour_query', 'item_minute_query', 'user_item_day_query',
    'user_item_hour_query', 'user_item_minute_query', 'min_time',
    'user_is_his', 'item_is_his', 'brand_is_his', 'user_is_trade_his',
    'item_is_trade_his', 'brand_is_trade_his', 'user_count', 'user_day_count',
    'user_hour_count', 'user_minute_count', 'item_trade_percent',
    'brand_trade_percent', 'user_trade_percent', 'occupation_trade_percent',
    'is_home', 'shop_item_count', 'brand_item_count', 'city_brand_count',
    'city_item_count', 'shop_item_count_his', 'brand_item_count_his',
    'city_brand_count_his', 'city_item_count_his', 'next_time_sub',
    'last_time_sub', 'user_item_num', 'user_shop_num', 'user_item_day_num',
    'user_shop_day_num', 'user_item_next_time_sub', 'user_item_last_time_sub',
    'user_shop_next_time_sub', 'user_shop_last_time_sub',
    'user_count_first_time_sub', 'user_item_count_first_time_sub',
    'user_shop_count_first_time_sub', 'max_click', 'is_last_click',
    'max_user_item_click', 'is_last_user_item_click', 'max_click_time_sub',
    'max_user_item_click_time_sub'
]

features_fulltime = [
    'next_time_sub_full_time', 'last_time_sub_full_time',
    'user_shop_num_full_time',
    'user_item_day_num_full_time', 'user_shop_day_num_full_time',
    'user_item_next_time_sub_full_time', 'user_item_last_time_sub_full_time',
    'user_shop_next_time_sub_full_time', 'user_shop_last_time_sub_full_time',
    'user_count_first_time_sub_full_time',
    'user_item_count_first_time_sub_full_time',
    'user_shop_count_first_time_sub_full_time', 'max_click_full_time',
    'is_last_click_full_time', 'max_user_item_click_full_time',
    'is_last_user_item_click_full_time', 'max_user_item_click_time_sub_full_time'
]

features_cjy = ['item_cat_vec0',
 'item_cat_vec1',
 'item_cat_vec2',
 'item_cat_vec3',
 'item_cat_vec4',
 'item_cat_vec5',
 'item_cat_vec6',
 'item_cat_vec7',
 'item_cat_vec8',
 'item_cat_vec9',
 'item_cat_vec10',
 'item_cat_vec11',
 'item_cat_vec12',
 'item_cat_vec13',
 'item_cat_vec14',
 'item_cat_vec15',
 'shop_item_cnt',
 'shop_brand_cnt',
 'item_pred_cat_cos',
 'item_pred_ppt_cos']

target = ['is_trade']

In [11]:
predictors = list(set(origin + features + features_cjy))
len(predictors)

145

In [12]:
test = train[train.is_trade == -1]
train = train[train.is_trade != -1]
# val_model2 = val_model2[val_model2.is_trade != -1]

test.shape
train.shape
# val_model2.shape

(1729656, 175)

(3435035, 175)

In [13]:
#cv
params = {
    'objective': 'binary:logistic',
    'eta': 0.05,
    'colsample_bytree': 0.886,
    'min_child_weight': 1.6,
    'max_depth': 4,
    'subsample': 0.886,
    'gamma': 0.1,
    'lambda': 10,
    'verbose_eval': True,
    'eval_metric': 'logloss',
    'seed': 201803,
    'missing': -1
}

len(predictors)

xgbtrain = xgb.DMatrix(train[predictors], train[target])
del train
gc.collect()

print('Start training')
cv = xgb.cv(
    params,
    dtrain=xgbtrain,
    num_boost_round=5000,
    nfold=3,
    verbose_eval=100,
    early_stopping_rounds=50,
    seed=201803)
print(str(cv.shape[0]) + ':' + str(cv.iloc[-1, :]['test-logloss-mean']))
print('End training')
# 1032:0.050188(full)

145

12

Start training
[0]	train-logloss:0.648425+6.97615e-06	test-logloss:0.648426+5.71548e-06
[100]	train-logloss:0.0914203+0.000111876	test-logloss:0.09156+0.000219824
[200]	train-logloss:0.088891+0.000118679	test-logloss:0.0892503+0.000235183

KeyboardInterrupt:

In [ ]:
#train/test
params = {
    'objective': 'binary:logistic',
    'eta': 0.05,
    'colsample_bytree': 0.886,
    'min_child_weight': 1.6,
    'max_depth': 4,
    'subsample': 0.886,
    'gamma': 0.1,
    'lambda': 10,
    'verbose_eval': True,
    'eval_metric': 'logloss',
    'seed': 201803,
    'missing': -1
}

# predictors = list(set(predictors) - set(['instance_id', 'is_trade']))
len(predictors)

# xgbtrain = xgb.DMatrix(train[predictors], train[target])
# xgbval = xgb.DMatrix(val_model2[predictors])
xgbtest = xgb.DMatrix(test[predictors])
model = xgb.train(params, xgbtrain, num_boost_round=cv.shape[0])

y_pred = model.predict(xgbtest)
# y_pred = model.predict(xgbval)
# print(str(log_loss(val_model2.is_trade, y_pred)))

idx = test.instance_id.reset_index()
idx['predicted_score'] = y_pred
idx[['instance_id', 'predicted_score']].to_csv(
    'resultWithHistory_round(model2_b).txt',
    sep=' ',
    header=['instance_id', 'predicted_score'],
    index=False)

In [16]:
val_model2['pred'] = list(y_pred)

val_model2[['instance_id', 'pred']].to_csv('pred_model2.csv', index=None)

In [39]:
idx.shape
idx.head()

(519888, 3)

     index          instance_id  predicted_score
0  2357860  1781317115815731318         0.019761
1  2357861  6116634221596372212         0.006037
2  2357862  6875831956810295589         0.009598
3  2357863  6990128147973947372         0.000102
4  2357864  6731403233620820223         0.047891

In [2]:
idx1 = pd.read_csv('resultWithHistory_round(241_order14696).txt', sep=' ')
idx2 = pd.read_csv('resultWithHistory_round(335_order14702).txt', sep=' ')
idx3 = pd.read_csv('resultWithHistory_round(final15_mix14454).txt', sep=' ')

idx1.predicted_score.mean() # 14696
idx2.predicted_score.mean() # 14702
idx3.predicted_score.mean() # 14454

0.051909991175910594

0.05217016303083417

0.04370436719458593

In [2]:
idx = pd.read_csv('resultWithHistory_round(model2).txt', sep=' ')

In [3]:
pred_model2 = idx[['instance_id', 'predicted_score']]
pred_model2.columns = ['instance_id', 'predicted_score2']
pred_model1 = pd.read_csv('resultWithHistory_round(mix_no_leak_order).txt', sep=' ')
pred = pred_model1.merge(pred_model2, on=['instance_id'], how='left')

# for i in [0:0.05:1]:
#     pred['final_result'] = i * pred.predicted_score + (1 - i) * predicted_score2
#     print(str(i) + ':' + str(log_loss(val.is_trade, pred['final_result'])))

pred['final_result'] = 0.85 * pred.predicted_score + 0.15 * pred.predicted_score2
pred[['instance_id', 'final_result']].to_csv(
    'resultWithHistory_round(final15_mix_no_leak).txt',
    sep=' ',
    header=['instance_id', 'predicted_score'],
    index=False)

In [7]:
pred.shape
pred.head()

(519888, 4)

       instance_id  predicted_score  predicted_score2  final_result
0   93294255633855         0.038247          0.001659      0.032759
1  558322259509454         0.010289          0.000128      0.008765
2  594573634113186         0.033406          0.009034      0.029750
3  667327653735176         0.030000          0.011091      0.027164
4  697732672924394         0.037763          0.000221      0.032132